# Nanopore mapping analysis for PRJEB88111

In [24]:
import polars as pl
import matplotlib.pyplot as plt

In [2]:
depth_df = (
    pl.scan_csv('reps/bams/*.x.all-core.depth.csv')
).collect()

In [3]:
contigs_species_df = pl.read_csv('reps/contigs_to_species.csv')

In [4]:
depth_df

shape: (167_616, 7)
┌─────────────┬──────────────────────┬───────┬───────┬──────────┬───────────┬───────────┐
│ metag       ┆ gene                 ┆ len   ┆ hits  ┆ breadth  ┆ depth_all ┆ depth_cov │
│ ---         ┆ ---                  ┆ ---   ┆ ---   ┆ ---      ┆ ---       ┆ ---       │
│ str         ┆ str                  ┆ i64   ┆ i64   ┆ f64      ┆ f64       ┆ f64       │
╞═════════════╪══════════════════════╪═══════╪═══════╪══════════╪═══════════╪═══════════╡
│ ERR15909852 ┆ FR882202.1           ┆ 72839 ┆ 5938  ┆ 0.081522 ┆ 0.088785  ┆ 1.089087  │
│ ERR15909852 ┆ SFNX01000131.1       ┆ 4530  ┆ 0     ┆ 0.0      ┆ 0.0       ┆ NaN       │
│ ERR15909852 ┆ NZ_JAFBIX010000025.1 ┆ 46446 ┆ 8035  ┆ 0.172997 ┆ 0.416268  ┆ 2.406223  │
│ ERR15909852 ┆ JALFRH010000010.1    ┆ 9875  ┆ 105   ┆ 0.010633 ┆ 0.031899  ┆ 3.0       │
│ ERR15909852 ┆ JALFNN010000087.1    ┆ 63285 ┆ 24763 ┆ 0.391293 ┆ 0.56511   ┆ 1.444211  │
│ …           ┆ …                    ┆ …     ┆ …     ┆ …        ┆ …         ┆ …         │
│ ERR15942255 ┆ SFNX01000182.1       ┆ 3218  ┆ 0     ┆ 0.0      ┆ 0.0       ┆ NaN       │
│ ERR15942255 ┆ JALFNN010000085.1    ┆ 4012  ┆ 0     ┆ 0.0      ┆ 0.0       ┆ NaN       │
│ ERR15942255 ┆ SFNX01000139.1       ┆ 3818  ┆ 0     ┆ 0.0      ┆ 0.0       ┆ NaN       │
│ ERR15942255 ┆ SFNX01000024.1       ┆ 21689 ┆ 0     ┆ 0.0      ┆ 0.0       ┆ NaN       │
│ ERR15942255 ┆ JALFNN010000079.1    ┆ 18212 ┆ 0     ┆ 0.0      ┆ 0.0       ┆ NaN       │
└─────────────┴──────────────────────┴───────┴───────┴──────────┴───────────┴───────────┘

In [5]:
contigs_species_df.head()

shape: (5, 3)
┌────────────────┬─────────────────────────────────┬─────────────────┐
│ contig         ┆ species                         ┆ acc             │
│ ---            ┆ ---                             ┆ ---             │
│ str            ┆ str                             ┆ str             │
╞════════════════╪═════════════════════════════════╪═════════════════╡
│ UREV01000001.1 ┆ s__Cryptobacteroides sp9005469… ┆ GCA_900546925.1 │
│ UREV01000002.1 ┆ s__Cryptobacteroides sp9005469… ┆ GCA_900546925.1 │
│ UREV01000003.1 ┆ s__Cryptobacteroides sp9005469… ┆ GCA_900546925.1 │
│ UREV01000004.1 ┆ s__Cryptobacteroides sp9005469… ┆ GCA_900546925.1 │
│ UREV01000005.1 ┆ s__Cryptobacteroides sp9005469… ┆ GCA_900546925.1 │
└────────────────┴─────────────────────────────────┴─────────────────┘

In [6]:
join_df = depth_df.join(contigs_species_df, left_on='gene', right_on='contig', how='inner')
join_df

shape: (167_616, 9)
┌─────────────┬─────────────┬───────┬───────┬───┬───────────┬───────────┬─────────────┬────────────┐
│ metag       ┆ gene        ┆ len   ┆ hits  ┆ … ┆ depth_all ┆ depth_cov ┆ species     ┆ acc        │
│ ---         ┆ ---         ┆ ---   ┆ ---   ┆   ┆ ---       ┆ ---       ┆ ---         ┆ ---        │
│ str         ┆ str         ┆ i64   ┆ i64   ┆   ┆ f64       ┆ f64       ┆ str         ┆ str        │
╞═════════════╪═════════════╪═══════╪═══════╪═══╪═══════════╪═══════════╪═════════════╪════════════╡
│ ERR15909852 ┆ FR882202.1  ┆ 72839 ┆ 5938  ┆ … ┆ 0.088785  ┆ 1.089087  ┆ s__Cryptoba ┆ GCA_000434 │
│             ┆             ┆       ┆       ┆   ┆           ┆           ┆ cteroides   ┆ 935.1      │
│             ┆             ┆       ┆       ┆   ┆           ┆           ┆ sp0004349…  ┆            │
│ ERR15909852 ┆ SFNX0100013 ┆ 4530  ┆ 0     ┆ … ┆ 0.0       ┆ NaN       ┆ s__UBA2868  ┆ GCA_004552 │
│             ┆ 1.1         ┆       ┆       ┆   ┆           ┆           ┆ sp004552595 ┆ 595.1      │
│ ERR15909852 ┆ NZ_JAFBIX01 ┆ 46446 ┆ 8035  ┆ … ┆ 0.416268  ┆ 2.406223  ┆ s__JAFBIX01 ┆ GCF_021531 │
│             ┆ 0000025.1   ┆       ┆       ┆   ┆           ┆           ┆ sp021531895 ┆ 895.1      │
│ ERR15909852 ┆ JALFRH01000 ┆ 9875  ┆ 105   ┆ … ┆ 0.031899  ┆ 3.0       ┆ s__Ornithos ┆ GCA_022785 │
│             ┆ 0010.1      ┆       ┆       ┆   ┆           ┆           ┆ pirochaeta  ┆ 155.1      │
│             ┆             ┆       ┆       ┆   ┆           ┆           ┆ sp022785…   ┆            │
│ ERR15909852 ┆ JALFNN01000 ┆ 63285 ┆ 24763 ┆ … ┆ 0.56511   ┆ 1.444211  ┆ s__Bariatri ┆ GCA_022774 │
│             ┆ 0087.1      ┆       ┆       ┆   ┆           ┆           ┆ cus         ┆ 325.1      │
│             ┆             ┆       ┆       ┆   ┆           ┆           ┆ sp004560705 ┆            │
│ …           ┆ …           ┆ …     ┆ …     ┆ … ┆ …         ┆ …         ┆ …           ┆ …          │
│ ERR15942255 ┆ SFNX0100018 ┆ 3218  ┆ 0     ┆ … ┆ 0.0       ┆ NaN       ┆ s__UBA2868  ┆ GCA_004552 │
│             ┆ 2.1         ┆       ┆       ┆   ┆           ┆           ┆ sp004552595 ┆ 595.1      │
│ ERR15942255 ┆ JALFNN01000 ┆ 4012  ┆ 0     ┆ … ┆ 0.0       ┆ NaN       ┆ s__Bariatri ┆ GCA_022774 │
│             ┆ 0085.1      ┆       ┆       ┆   ┆           ┆           ┆ cus         ┆ 325.1      │
│             ┆             ┆       ┆       ┆   ┆           ┆           ┆ sp004560705 ┆            │
│ ERR15942255 ┆ SFNX0100013 ┆ 3818  ┆ 0     ┆ … ┆ 0.0       ┆ NaN       ┆ s__UBA2868  ┆ GCA_004552 │
│             ┆ 9.1         ┆       ┆       ┆   ┆           ┆           ┆ sp004552595 ┆ 595.1      │
│ ERR15942255 ┆ SFNX0100002 ┆ 21689 ┆ 0     ┆ … ┆ 0.0       ┆ NaN       ┆ s__UBA2868  ┆ GCA_004552 │
│             ┆ 4.1         ┆       ┆       ┆   ┆           ┆           ┆ sp004552595 ┆ 595.1      │
│ ERR15942255 ┆ JALFNN01000 ┆ 18212 ┆ 0     ┆ … ┆ 0.0       ┆ NaN       ┆ s__Bariatri ┆ GCA_022774 │
│             ┆ 0079.1      ┆       ┆       ┆   ┆           ┆           ┆ cus         ┆ 325.1      │
│             ┆             ┆       ┆       ┆   ┆           ┆           ┆ sp004560705 ┆            │
└─────────────┴─────────────┴───────┴───────┴───┴───────────┴───────────┴─────────────┴────────────┘

In [7]:
join2_df = join_df.with_columns(
    weighted_depth=(pl.col('len') * pl.col('depth_all')),
    weighted_breadth=(pl.col('len') * pl.col('breadth')),
)
join2_df

shape: (167_616, 11)
┌─────────────┬────────────┬───────┬───────┬───┬────────────┬────────────┬────────────┬────────────┐
│ metag       ┆ gene       ┆ len   ┆ hits  ┆ … ┆ species    ┆ acc        ┆ weighted_d ┆ weighted_b │
│ ---         ┆ ---        ┆ ---   ┆ ---   ┆   ┆ ---        ┆ ---        ┆ epth       ┆ readth     │
│ str         ┆ str        ┆ i64   ┆ i64   ┆   ┆ str        ┆ str        ┆ ---        ┆ ---        │
│             ┆            ┆       ┆       ┆   ┆            ┆            ┆ f64        ┆ f64        │
╞═════════════╪════════════╪═══════╪═══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ ERR15909852 ┆ FR882202.1 ┆ 72839 ┆ 5938  ┆ … ┆ s__Cryptob ┆ GCA_000434 ┆ 6467.0     ┆ 5938.0     │
│             ┆            ┆       ┆       ┆   ┆ acteroides ┆ 935.1      ┆            ┆            │
│             ┆            ┆       ┆       ┆   ┆ sp0004349… ┆            ┆            ┆            │
│ ERR15909852 ┆ SFNX010001 ┆ 4530  ┆ 0     ┆ … ┆ s__UBA2868 ┆ GCA_004552 ┆ 0.0        ┆ 0.0        │
│             ┆ 31.1       ┆       ┆       ┆   ┆ sp00455259 ┆ 595.1      ┆            ┆            │
│             ┆            ┆       ┆       ┆   ┆ 5          ┆            ┆            ┆            │
│ ERR15909852 ┆ NZ_JAFBIX0 ┆ 46446 ┆ 8035  ┆ … ┆ s__JAFBIX0 ┆ GCF_021531 ┆ 19334.0    ┆ 8035.0     │
│             ┆ 10000025.1 ┆       ┆       ┆   ┆ 1 sp021531 ┆ 895.1      ┆            ┆            │
│             ┆            ┆       ┆       ┆   ┆ 895        ┆            ┆            ┆            │
│ ERR15909852 ┆ JALFRH0100 ┆ 9875  ┆ 105   ┆ … ┆ s__Ornitho ┆ GCA_022785 ┆ 315.0      ┆ 105.0      │
│             ┆ 00010.1    ┆       ┆       ┆   ┆ spirochaet ┆ 155.1      ┆            ┆            │
│             ┆            ┆       ┆       ┆   ┆ a          ┆            ┆            ┆            │
│             ┆            ┆       ┆       ┆   ┆ sp022785…  ┆            ┆            ┆            │
│ ERR15909852 ┆ JALFNN0100 ┆ 63285 ┆ 24763 ┆ … ┆ s__Bariatr ┆ GCA_022774 ┆ 35763.0    ┆ 24763.0    │
│             ┆ 00087.1    ┆       ┆       ┆   ┆ icus sp004 ┆ 325.1      ┆            ┆            │
│             ┆            ┆       ┆       ┆   ┆ 560705     ┆            ┆            ┆            │
│ …           ┆ …          ┆ …     ┆ …     ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ ERR15942255 ┆ SFNX010001 ┆ 3218  ┆ 0     ┆ … ┆ s__UBA2868 ┆ GCA_004552 ┆ 0.0        ┆ 0.0        │
│             ┆ 82.1       ┆       ┆       ┆   ┆ sp00455259 ┆ 595.1      ┆            ┆            │
│             ┆            ┆       ┆       ┆   ┆ 5          ┆            ┆            ┆            │
│ ERR15942255 ┆ JALFNN0100 ┆ 4012  ┆ 0     ┆ … ┆ s__Bariatr ┆ GCA_022774 ┆ 0.0        ┆ 0.0        │
│             ┆ 00085.1    ┆       ┆       ┆   ┆ icus sp004 ┆ 325.1      ┆            ┆            │
│             ┆            ┆       ┆       ┆   ┆ 560705     ┆            ┆            ┆            │
│ ERR15942255 ┆ SFNX010001 ┆ 3818  ┆ 0     ┆ … ┆ s__UBA2868 ┆ GCA_004552 ┆ 0.0        ┆ 0.0        │
│             ┆ 39.1       ┆       ┆       ┆   ┆ sp00455259 ┆ 595.1      ┆            ┆            │
│             ┆            ┆       ┆       ┆   ┆ 5          ┆            ┆            ┆            │
│ ERR15942255 ┆ SFNX010000 ┆ 21689 ┆ 0     ┆ … ┆ s__UBA2868 ┆ GCA_004552 ┆ 0.0        ┆ 0.0        │
│             ┆ 24.1       ┆       ┆       ┆   ┆ sp00455259 ┆ 595.1      ┆            ┆            │
│             ┆            ┆       ┆       ┆   ┆ 5          ┆            ┆            ┆            │
│ ERR15942255 ┆ JALFNN0100 ┆ 18212 ┆ 0     ┆ … ┆ s__Bariatr ┆ GCA_022774 ┆ 0.0        ┆ 0.0        │
│             ┆ 00079.1    ┆       ┆       ┆   ┆ icus sp004 ┆ 325.1      ┆            ┆            │
│             ┆            ┆       ┆       ┆   ┆ 560705     ┆            ┆            ┆            │
└─────────────┴────────────┴───────┴───────┴───┴────────────┴────────────┴────────────┴────────────┘

In [8]:
sum_df = join2_df.group_by(['metag', 'species']).agg(
    depth_all=pl.col('weighted_depth').sum() / pl.col('len').sum(),
    breadth=pl.col('weighted_breadth').sum() / pl.col('len').sum(),
)
sum_df.sort('breadth')

shape: (1_728, 4)
┌─────────────┬─────────────────────────────────┬─────────────┬──────────┐
│ metag       ┆ species                         ┆ depth_all   ┆ breadth  │
│ ---         ┆ ---                             ┆ ---         ┆ ---      │
│ str         ┆ str                             ┆ f64         ┆ f64      │
╞═════════════╪═════════════════════════════════╪═════════════╪══════════╡
│ ERR15942159 ┆ s__Cryptobacteroides sp0004326… ┆ 0.0         ┆ 0.0      │
│ ERR15941747 ┆ s__Cryptobacteroides sp0004326… ┆ 0.0         ┆ 0.0      │
│ ERR15941693 ┆ s__Cryptobacteroides sp0340892… ┆ 0.0         ┆ 0.0      │
│ ERR15942217 ┆ s__Cryptobacteroides sp0004349… ┆ 0.0         ┆ 0.0      │
│ ERR15942182 ┆ s__Cryptobacteroides sp0004349… ┆ 0.0         ┆ 0.0      │
│ …           ┆ …                               ┆ …           ┆ …        │
│ ERR15935028 ┆ s__JAFBIX01 sp021531895         ┆ 137.764068  ┆ 0.992922 │
│ ERR15934940 ┆ s__Bariatricus sp004560705      ┆ 108.242687  ┆ 0.99321  │
│ ERR15934725 ┆ s__Bariatricus sp004560705      ┆ 102.132863  ┆ 0.993625 │
│ ERR15934877 ┆ s__Lactobacillus amylovorus     ┆ 5257.163197 ┆ 0.994524 │
│ ERR15938761 ┆ s__JAFBIX01 sp021531895         ┆ 245.597313  ┆ 0.995247 │
└─────────────┴─────────────────────────────────┴─────────────┴──────────┘

In [16]:
mf_df = (
    pl.read_csv('PRJEB88111.mf.csv', skip_lines=1)
    .select(["name", "n_hashes"])
)

In [30]:
sum2_df = sum_df.join(mf_df, left_on='metag', right_on='name', how='inner')
sum2_df

shape: (5_184, 5)
┌─────────────┬────────────────────────────┬───────────┬──────────┬──────────┐
│ metag       ┆ species                    ┆ depth_all ┆ breadth  ┆ n_hashes │
│ ---         ┆ ---                        ┆ ---       ┆ ---      ┆ ---      │
│ str         ┆ str                        ┆ f64       ┆ f64      ┆ i64      │
╞═════════════╪════════════════════════════╪═══════════╪══════════╪══════════╡
│ ERR15938761 ┆ s__Colivicinus sp002299675 ┆ 16.095733 ┆ 0.980172 ┆ 4792317  │
│ ERR15938761 ┆ s__Colivicinus sp002299675 ┆ 16.095733 ┆ 0.980172 ┆ 6015297  │
│ ERR15938761 ┆ s__Colivicinus sp002299675 ┆ 16.095733 ┆ 0.980172 ┆ 7952050  │
│ ERR15942168 ┆ s__Colivicinus sp002299675 ┆ 0.007576  ┆ 0.000122 ┆ 88739    │
│ ERR15942168 ┆ s__Colivicinus sp002299675 ┆ 0.007576  ┆ 0.000122 ┆ 120320   │
│ …           ┆ …                          ┆ …         ┆ …        ┆ …        │
│ ERR15936647 ┆ s__Colivicinus sp002299675 ┆ 6.362538  ┆ 0.96648  ┆ 2764116  │
│ ERR15936647 ┆ s__Colivicinus sp002299675 ┆ 6.362538  ┆ 0.96648  ┆ 3293610  │
│ ERR15942126 ┆ s__Floccifex porci         ┆ 1.153239  ┆ 0.008441 ┆ 94604    │
│ ERR15942126 ┆ s__Floccifex porci         ┆ 1.153239  ┆ 0.008441 ┆ 130997   │
│ ERR15942126 ┆ s__Floccifex porci         ┆ 1.153239  ┆ 0.008441 ┆ 198888   │
└─────────────┴────────────────────────────┴───────────┴──────────┴──────────┘

In [29]:
filt_df = sum2_df.filter(pl.col('n_hashes') > 4e6)
filt_df

shape: (1_264, 5)
┌─────────────┬─────────────────────────────────┬───────────┬──────────┬──────────┐
│ metag       ┆ species                         ┆ depth_all ┆ breadth  ┆ n_hashes │
│ ---         ┆ ---                             ┆ ---       ┆ ---      ┆ ---      │
│ str         ┆ str                             ┆ f64       ┆ f64      ┆ i64      │
╞═════════════╪═════════════════════════════════╪═══════════╪══════════╪══════════╡
│ ERR15938761 ┆ s__Colivicinus sp002299675      ┆ 16.095733 ┆ 0.980172 ┆ 4792317  │
│ ERR15938761 ┆ s__Colivicinus sp002299675      ┆ 16.095733 ┆ 0.980172 ┆ 6015297  │
│ ERR15938761 ┆ s__Colivicinus sp002299675      ┆ 16.095733 ┆ 0.980172 ┆ 7952050  │
│ ERR15935141 ┆ s__Prevotella sp000434975       ┆ 79.086944 ┆ 0.933354 ┆ 6369270  │
│ ERR15935141 ┆ s__Prevotella sp000434975       ┆ 79.086944 ┆ 0.933354 ┆ 7920196  │
│ …           ┆ …                               ┆ …         ┆ …        ┆ …        │
│ ERR15934506 ┆ s__Prevotella sp000434975       ┆ 76.334309 ┆ 0.924323 ┆ 7079510  │
│ ERR15934506 ┆ s__Prevotella sp000434975       ┆ 76.334309 ┆ 0.924323 ┆ 9149952  │
│ ERR15934877 ┆ s__Cryptobacteroides sp0004349… ┆ 4.72089   ┆ 0.800611 ┆ 5579319  │
│ ERR15934877 ┆ s__Cryptobacteroides sp0004349… ┆ 4.72089   ┆ 0.800611 ┆ 7089492  │
│ ERR15934877 ┆ s__Cryptobacteroides sp0004349… ┆ 4.72089   ┆ 0.800611 ┆ 9521552  │
└─────────────┴─────────────────────────────────┴───────────┴──────────┴──────────┘

In [44]:
by_species = filt_df.group_by('species').agg(
    min_breadth=pl.col('breadth').min().round(3),
    med_breadth=pl.col('breadth').median().round(3),
    max_breadth=pl.col('breadth').max().round(3),
    min_depth=pl.col('depth_all').min().round(2),
    med_depth=pl.col('depth_all').median().round(1),
    max_depth=pl.col('depth_all').max().round(1),
)

In [45]:
with pl.Config(tbl_rows=-1):
    print(by_species.sort('min_breadth'))

shape: (16, 7)
┌────────────────────┬─────────────┬─────────────┬─────────────┬───────────┬───────────┬───────────┐
│ species            ┆ min_breadth ┆ med_breadth ┆ max_breadth ┆ min_depth ┆ med_depth ┆ max_depth │
│ ---                ┆ ---         ┆ ---         ┆ ---         ┆ ---       ┆ ---       ┆ ---       │
│ str                ┆ f64         ┆ f64         ┆ f64         ┆ f64       ┆ f64       ┆ f64       │
╞════════════════════╪═════════════╪═════════════╪═════════════╪═══════════╪═══════════╪═══════════╡
│ s__UBA2868         ┆ 0.33        ┆ 0.798       ┆ 0.929       ┆ 5.66      ┆ 19.6      ┆ 52.3      │
│ sp004552595        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Floccifex porci ┆ 0.45        ┆ 0.944       ┆ 0.97        ┆ 11.98     ┆ 31.4      ┆ 67.1      │
│ s__Mogibacterium_A ┆ 0.484       ┆ 0.963       ┆ 0.991       ┆ 8.89      ┆ 24.9      ┆ 80.4      │
│ kristiansen…       ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Ornithospirocha ┆ 0.507       ┆ 0.903       ┆ 0.978       ┆ 1.4       ┆ 5.2       ┆ 14.1      │
│ eta sp022785…      ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Prevotella      ┆ 0.665       ┆ 0.964       ┆ 0.98        ┆ 6.45      ┆ 24.0      ┆ 330.3     │
│ sp002251295        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Cryptobacteroid ┆ 0.681       ┆ 0.841       ┆ 0.887       ┆ 2.13      ┆ 7.2       ┆ 30.9      │
│ es sp0004349…      ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Cryptobacteroid ┆ 0.701       ┆ 0.903       ┆ 0.935       ┆ 2.72      ┆ 7.1       ┆ 18.3      │
│ es sp0004326…      ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__JAFBIX01        ┆ 0.714       ┆ 0.964       ┆ 0.995       ┆ 16.21     ┆ 77.5      ┆ 256.1     │
│ sp021531895        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Fimisoma        ┆ 0.731       ┆ 0.932       ┆ 0.953       ┆ 7.77      ┆ 24.1      ┆ 78.0      │
│ sp002320005        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Colivicinus     ┆ 0.802       ┆ 0.978       ┆ 0.986       ┆ 5.76      ┆ 17.1      ┆ 47.2      │
│ sp002299675        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Prevotella      ┆ 0.838       ┆ 0.901       ┆ 0.951       ┆ 14.67     ┆ 41.0      ┆ 613.9     │
│ sp000434975        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Cryptobacteroid ┆ 0.91        ┆ 0.978       ┆ 0.986       ┆ 3.62      ┆ 11.8      ┆ 67.9      │
│ es sp9005469…      ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Cryptobacteroid ┆ 0.913       ┆ 0.983       ┆ 0.991       ┆ 6.09      ┆ 16.9      ┆ 61.5      │
│ es sp0340892…      ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Lactobacillus   ┆ 0.921       ┆ 0.979       ┆ 0.995       ┆ 38.31     ┆ 1570.7    ┆ 5257.2    │
│ amylovorus         ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Bariatricus     ┆ 0.941       ┆ 0.983       ┆ 0.994       ┆ 17.29     ┆ 58.3      ┆ 193.9     │
│ sp004560705        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Sodaliphilus    ┆ 0.965       ┆ 0.976       ┆ 0.983       ┆ 22.86     ┆ 62.6      ┆ 311.4     │
│ sp004557565        ┆             ┆             ┆             ┆           ┆           ┆           │
└────────────────────┴─────────────┴─────────────┴─────────────┴───────────┴───────────┴───────────┘