# Explore the 'other' category of branchwater matches

In [1]:
import polars as pl

## Load list of accessions with some minimum number of core species in them

In [2]:
# produced by branchwater-figure.ipynb
found_df = pl.read_csv('../outputs.branchwater/branchwater_8species_other.csv')
min_count = found_df['count'].min()

print(f"loaded {len(found_df)} accessions with at least (>=) {min_count} of the 16 core species in them.")

loaded 1677 accessions with at least (>=) 8 of the 16 core species in them.

## Load metadata

In [3]:
# get metadata, only compare WGS
metadata_df = (
    pl.scan_parquet("/group/ctbrowngrp5/sra-metagenomes/20241128-metadata.parquet")
    .filter(pl.col("acc") != "NP")
    .filter(pl.col("assay_type") == "WGS")
#    .select(["acc", "organism", "bioproject", "mbases", "host", "project_name"]) 
    .collect()
)
print(f"found metadata records for {len(metadata_df)} WGS metagenome data sets from the SRA")

found metadata records for 703916 WGS metagenome data sets from the SRA

In [16]:
mgnify_df = pl.read_csv('../mgnify_bioproj.csv').unique()

## Join 'other' list with metadata

In [5]:
found_df2 = found_df.join(metadata_df, on=['acc', 'bioproject', 'organism'], how='inner', validate="1:m")
assert len(found_df) == len(found_df2)
assert found_df['count'].min() == 8

In [17]:
mgnify_df

shape: (705, 4)
┌─────────────┬─────────────────────────────┬────────────────────────┬─────────────────────────────┐
│ bioproject  ┆ title                       ┆ biome.biome_name       ┆ biome.lineage               │
│ ---         ┆ ---                         ┆ ---                    ┆ ---                         │
│ str         ┆ str                         ┆ str                    ┆ str                         │
╞═════════════╪═════════════════════════════╪════════════════════════╪═════════════════════════════╡
│ PRJNA330008 ┆ Marine microbial            ┆ Marine                 ┆ root:Environmental:Aquatic: │
│             ┆ communities f…              ┆                        ┆ Mar…                        │
│ PRJNA997379 ┆ A Longitudinal Metagenomic  ┆ Oral                   ┆ root:Host-associated:Human: │
│             ┆ Com…                        ┆                        ┆ Dig…                        │
│ PRJEB26567  ┆ Passalid Beetle             ┆ Gut                    ┆ root:Host-associated:Arthro │
│             ┆                             ┆                        ┆ pod…                        │
│ PRJEB16362  ┆ Oyster and water samples    ┆ Coastal                ┆ root:Environmental:Aquatic: │
│             ┆ from …                      ┆                        ┆ Mar…                        │
│ PRJEB13831  ┆ Global surveillance of      ┆ Water and sludge       ┆ root:Engineered:Wastewater: │
│             ┆ infecti…                    ┆                        ┆ Wat…                        │
│ …           ┆ …                           ┆ …                      ┆ …                           │
│ PRJEB8716   ┆ Experimental Metagenome on  ┆ Simulated communities  ┆ root:Engineered:Modeled:Sim │
│             ┆ Min…                        ┆ (DNA mix…              ┆ ula…                        │
│ PRJEB15535  ┆ Viral metagenome of Lake    ┆ Lake                   ┆ root:Environmental:Aquatic: │
│             ┆ Soyan…                      ┆                        ┆ Fre…                        │
│ PRJEB5860   ┆ Structure and functions of  ┆ Rhizosphere            ┆ root:Host-associated:Plants │
│             ┆ the…                        ┆                        ┆ :Rh…                        │
│ PRJEB52002  ┆ Metagenomics insights into  ┆ Salt crystallizer pond ┆ root:Environmental:Aquatic: │
│             ┆ Phy…                        ┆                        ┆ Non…                        │
│ PRJEB14811  ┆ Freshwater shotgun          ┆ Freshwater             ┆ root:Environmental:Aquatic: │
│             ┆ metagenome …                ┆                        ┆ Fre…                        │
└─────────────┴─────────────────────────────┴────────────────────────┴─────────────────────────────┘

In [18]:
found_df3 = found_df2.join(mgnify_df, on='bioproject', how='inner')

In [19]:
found_df3

shape: (257, 75)
┌────────────┬────────────┬────────────┬───────┬───┬───────────┬───────────┬───────────┬───────────┐
│ acc        ┆ bioproject ┆ organism   ┆ count ┆ … ┆ primary_s ┆ title     ┆ biome.bio ┆ biome.lin │
│ ---        ┆ ---        ┆ ---        ┆ ---   ┆   ┆ earch     ┆ ---       ┆ me_name   ┆ eage      │
│ str        ┆ str        ┆ str        ┆ i64   ┆   ┆ ---       ┆ str       ┆ ---       ┆ ---       │
│            ┆            ┆            ┆       ┆   ┆ str       ┆           ┆ str       ┆ str       │
╞════════════╪════════════╪════════════╪═══════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ ERR2586125 ┆ PRJEB26788 ┆ air        ┆ 13    ┆ … ┆ "19256833 ┆ Investiga ┆ Soil      ┆ root:Envi │
│            ┆            ┆ metagenome ┆       ┆   ┆ "         ┆ tion of   ┆           ┆ ronmental │
│            ┆            ┆            ┆       ┆   ┆           ┆ the micro ┆           ┆ :Terrestr │
│            ┆            ┆            ┆       ┆   ┆           ┆ bial…     ┆           ┆ ial…      │
│ ERR2683129 ┆ PRJEB27621 ┆ wastewater ┆ 11    ┆ … ┆ "15425662 ┆ Global    ┆ Wastewate ┆ root:Engi │
│            ┆            ┆ metagenome ┆       ┆   ┆ "         ┆ surveilla ┆ r         ┆ neered:Wa │
│            ┆            ┆            ┆       ┆   ┆           ┆ nce of    ┆           ┆ stewater  │
│            ┆            ┆            ┆       ┆   ┆           ┆ antimic…  ┆           ┆           │
│ ERR3574843 ┆ PRJEB34634 ┆ sediment   ┆ 16    ┆ … ┆ "15416878 ┆ Detailed  ┆ Mixed     ┆ root:Mixe │
│            ┆            ┆ metagenome ┆       ┆   ┆ "         ┆ study at  ┆           ┆ d         │
│            ┆            ┆            ┆       ┆   ┆           ┆ the       ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ genetic … ┆           ┆           │
│ SRR6425774 ┆ PRJNA42765 ┆ sheep      ┆ 8     ┆ … ┆ "427653"  ┆ Comprehen ┆ Mixed     ┆ root:Mixe │
│            ┆ 3          ┆ metagenome ┆       ┆   ┆           ┆ sive Meta ┆           ┆ d         │
│            ┆            ┆            ┆       ┆   ┆           ┆ genomic   ┆           ┆           │
│ ERR3574765 ┆ PRJEB34634 ┆ sediment   ┆ 16    ┆ … ┆ "15416878 ┆ Detailed  ┆ Mixed     ┆ root:Mixe │
│            ┆            ┆ metagenome ┆       ┆   ┆ "         ┆ study at  ┆           ┆ d         │
│            ┆            ┆            ┆       ┆   ┆           ┆ the       ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ genetic … ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …     ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ ERR3574838 ┆ PRJEB34634 ┆ sediment   ┆ 16    ┆ … ┆ "15416878 ┆ Detailed  ┆ Mixed     ┆ root:Mixe │
│            ┆            ┆ metagenome ┆       ┆   ┆ "         ┆ study at  ┆           ┆ d         │
│            ┆            ┆            ┆       ┆   ┆           ┆ the       ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ genetic … ┆           ┆           │
│ ERR3574488 ┆ PRJEB34634 ┆ sediment   ┆ 15    ┆ … ┆ "15416878 ┆ Detailed  ┆ Mixed     ┆ root:Mixe │
│            ┆            ┆ metagenome ┆       ┆   ┆ "         ┆ study at  ┆           ┆ d         │
│            ┆            ┆            ┆       ┆   ┆           ┆ the       ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ genetic … ┆           ┆           │
│ ERR3574477 ┆ PRJEB34634 ┆ sediment   ┆ 15    ┆ … ┆ "15416878 ┆ Detailed  ┆ Mixed     ┆ root:Mixe │
│            ┆            ┆ metagenome ┆       ┆   ┆ "         ┆ study at  ┆           ┆ d         │
│            ┆            ┆            ┆       ┆   ┆           ┆ the       ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ genetic … ┆           ┆           │
│ ERR3574486 ┆ PRJEB34634 ┆ sediment   ┆ 15    ┆ … ┆ "15416878 ┆ Detailed  ┆ Mixed     ┆ root:Mixe │
│            ┆            ┆ metagenome ┆       ┆   ┆ "         ┆ study at  ┆           ┆ d         │
│            ┆            ┆            ┆       ┆   ┆           ┆ the       ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ genetic … ┆           ┆           │
│ ERR3574517 ┆ PRJEB34634 ┆ sediment   ┆ 16    ┆ … ┆ "15416878 ┆ Detailed  ┆ Mixed     ┆ root:Mixe │
│            ┆            ┆ metagenome ┆       ┆   ┆ "         ┆ study at  ┆           ┆ d         │
│            ┆            ┆            ┆       ┆   ┆           ┆ the       ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ genetic … ┆           ┆           │
└────────────┴────────────┴────────────┴───────┴───┴───────────┴───────────┴───────────┴───────────┘

In [21]:
print(len(found_df2), len(found_df3))

1677 257

In [7]:
# Do some nice reporting out of samples belong to a particular bioproject

class ReportOnBioProject:
    def __init__(self, *, by_acc, metadata_df):
        self.found_df = found_df
        self.metadata_df = metadata_df

        # how many in each bioproject are below cutoff?
        self.found_count_df = (
            by_acc
            .join(metadata_df, on='acc', how='inner')
            .group_by('bioproject').agg(n_found=pl.len())
        )

        # how many were in the SRA to begin with?
        self.sra_count_df = (
            metadata_df.group_by('bioproject').agg(n_sra=pl.len())
        )

    def report(self, *bioprojects, sort='n_found', retdf=False):
        xx_df = (
            self.found_count_df
            .join(self.sra_count_df, on='bioproject', how='inner')
        )

        xx_df = xx_df.filter(pl.col('bioproject').is_in(set(list(bioprojects)))).sort(sort)
        print(xx_df)
        if(retdf):
            return xx_df

reporter = ReportOnBioProject(by_acc=found_df, metadata_df=metadata_df)
reporter.report('PRJEB34634')

shape: (1, 3)
┌────────────┬─────────┬───────┐
│ bioproject ┆ n_found ┆ n_sra │
│ ---        ┆ ---     ┆ ---   │
│ str        ┆ u32     ┆ u32   │
╞════════════╪═════════╪═══════╡
│ PRJEB34634 ┆ 187     ┆ 2076  │
└────────────┴─────────┴───────┘

In [8]:
# for _all_ bioprojects in the metadata, do foo. CTB replace with reporting?
all_bioproject_sum_df = metadata_df.group_by('bioproject').agg(
    n_acc_total=pl.len(),
    orgs=pl.col('organism').unique(),   # list of "organism" annotations
)

In [9]:
summary_df = found_df2.group_by('bioproject').agg(
    n_acc_matched=pl.len(),
).join(all_bioproject_sum_df, on='bioproject', how='inner').sort('n_acc_matched')

summary_df.filter(pl.col('n_acc_matched') > 2).style

GT(_tbl_data=shape: (84, 4)
┌─────────────┬───────────────┬─────────────┬─────────────────────────────────┐
│ bioproject  ┆ n_acc_matched ┆ n_acc_total ┆ orgs                            │
│ ---         ┆ ---           ┆ ---         ┆ ---                             │
│ str         ┆ u32           ┆ u32         ┆ list[str]                       │
╞═════════════╪═══════════════╪═════════════╪═════════════════════════════════╡
│ PRJEB40816  ┆ 3             ┆ 142         ┆ ["wastewater metagenome"]       │
│ PRJNA608274 ┆ 3             ┆ 73          ┆ ["soil metagenome", "rhizosphe… │
│ PRJNA934407 ┆ 3             ┆ 36          ┆ ["runoff metagenome"]           │
│ PRJNA427653 ┆ 3             ┆ 81          ┆ ["sheep metagenome", "gut meta… │
│ PRJNA956982 ┆ 3             ┆ 18          ┆ ["bovine gut metagenome"]       │
│ …           ┆ …             ┆ …           ┆ …                               │
│ PRJNA623064 ┆ 49            ┆ 84          ┆ ["dust metagenome"]             │
│ PRJNA982563 ┆ 54            ┆ 232         ┆ ["skin metagenome", "dust meta… │
│ PRJNA379303 ┆ 61            ┆ 128         ┆ ["terrestrial metagenome"]      │
│ PRJNA356291 ┆ 72            ┆ 72          ┆ ["bovine gut metagenome"]       │
│ PRJEB34634  ┆ 187           ┆ 2076        ┆ ["sediment metagenome"]         │
└─────────────┴───────────────┴─────────────┴─────────────────────────────────┘, _body=<great_tables._gt_data.Body object at 0x7ed282476360>, _boxhead=Boxhead([ColInfo(var='bioproject', type=<ColInfoTypeEnum.default: 1>, column_label='bioproject', column_align='left', column_width=None), ColInfo(var='n_acc_matched', type=<ColInfoTypeEnum.default: 1>, column_label='n_acc_matched', column_align='right', column_width=None), ColInfo(var='n_acc_total', type=<ColInfoTypeEnum.default: 1>, column_label='n_acc_total', column_align='right', column_width=None), ColInfo(var='orgs', type=<ColInfoTypeEnum.default: 1>, column_label='orgs', column_align='center', column_width=None)]), _stub=<great_tables._gt_data.Stub object at 0x7ed281734c80>, _spanners=Spanners([]), _heading=Heading(title=None, subtitle=None, preheader=None), _stubhead=None, _summary_rows=<great_tables._gt_data.SummaryRows object at 0x7ed2817b5eb0>, _summary_rows_grand=<great_tables._gt_data.SummaryRows object at 0x7ed281735df0>, _source_notes=[], _footnotes=[], _styles=[], _locale=<great_tables._gt_data.Locale object at 0x7ed245a3e8a0>, _formats=[], _substitutions=[], _col_merge=[], _transforms=[], _options=Options(table_id=OptionsInfo(scss=False, category='table', type='value', value=None), table_caption=OptionsInfo(scss=False, category='table', type='value', value=None), table_width=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_layout=OptionsInfo(scss=True, category='table', type='value', value='fixed'), table_margin_left=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_margin_right=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_background_color=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_additional_css=OptionsInfo(scss=False, category='table', type='values', value=[]), table_font_names=OptionsInfo(scss=False, category='table', type='values', value=['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Helvetica Neue', 'Fira Sans', 'Droid Sans', 'Arial', 'sans-serif']), table_font_size=OptionsInfo(scss=True, category='table', type='px', value='16px'), table_font_weight=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_style=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_color=OptionsInfo(scss=True, category='table', type='value', value='#333333'), table_font_color_light=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_border_top_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_top_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_top_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_top_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_right_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_right_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_right_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), table_border_bottom_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_bottom_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_bottom_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_bottom_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_left_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_left_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_left_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), heading_background_color=OptionsInfo(scss=True, category='heading', type='value', value=None), heading_align=OptionsInfo(scss=True, category='heading', type='value', value='center'), heading_title_font_size=OptionsInfo(scss=True, category='heading', type='px', value='125%'), heading_title_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_subtitle_font_size=OptionsInfo(scss=True, category='heading', type='px', value='85%'), heading_subtitle_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_padding=OptionsInfo(scss=True, category='heading', type='px', value='4px'), heading_padding_horizontal=OptionsInfo(scss=True, category='heading', type='px', value='5px'), heading_border_bottom_style=OptionsInfo(scss=True, category='heading', type='value', value='solid'), heading_border_bottom_width=OptionsInfo(scss=True, category='heading', type='px', value='2px'), heading_border_bottom_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), heading_border_lr_style=OptionsInfo(scss=True, category='heading', type='value', value='none'), heading_border_lr_width=OptionsInfo(scss=True, category='heading', type='px', value='1px'), heading_border_lr_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), column_labels_background_color=OptionsInfo(scss=True, category='column_labels', type='value', value=None), column_labels_font_size=OptionsInfo(scss=True, category='column_labels', type='px', value='100%'), column_labels_font_weight=OptionsInfo(scss=True, category='column_labels', type='value', value='normal'), column_labels_text_transform=OptionsInfo(scss=True, category='column_labels', type='value', value='inherit'), column_labels_padding=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_padding_horizontal=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), column_labels_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), column_labels_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), column_labels_border_top_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_top_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_top_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_bottom_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_bottom_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_bottom_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_lr_style=OptionsInfo(scss=True, category='column_labels', type='value', value='none'), column_labels_border_lr_width=OptionsInfo(scss=True, category='column_labels', type='px', value='1px'), column_labels_border_lr_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_hidden=OptionsInfo(scss=False, category='column_labels', type='boolean', value=False), row_group_background_color=OptionsInfo(scss=True, category='row_group', type='value', value=None), row_group_font_size=OptionsInfo(scss=True, category='row_group', type='px', value='100%'), row_group_font_weight=OptionsInfo(scss=True, category='row_group', type='value', value='initial'), row_group_text_transform=OptionsInfo(scss=True, category='row_group', type='value', value='inherit'), row_group_padding=OptionsInfo(scss=True, category='row_group', type='px', value='8px'), row_group_padding_horizontal=OptionsInfo(scss=True, category='row_group', type='px', value='5px'), row_group_border_top_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_top_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_top_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_right_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_right_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_right_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_bottom_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_bottom_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_bottom_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_left_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_left_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_left_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_as_column=OptionsInfo(scss=False, category='row_group', type='boolean', value=False), table_body_hlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_hlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_hlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), table_body_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_top_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_top_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_top_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_bottom_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_bottom_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_bottom_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), data_row_padding=OptionsInfo(scss=True, category='data_row', type='px', value='8px'), data_row_padding_horizontal=OptionsInfo(scss=True, category='data_row', type='px', value='5px'), stub_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), stub_indent_length=OptionsInfo(scss=True, category='stub', type='px', value='5px'), stub_row_group_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_row_group_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_row_group_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_row_group_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_row_group_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_row_group_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_row_group_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), summary_row_padding=OptionsInfo(scss=True, category='summary_row', type='px', value='8px'), summary_row_padding_horizontal=OptionsInfo(scss=True, category='summary_row', type='px', value='5px'), summary_row_background_color=OptionsInfo(scss=True, category='summary_row', type='value', value=None), summary_row_text_transform=OptionsInfo(scss=True, category='summary_row', type='value', value='inherit'), summary_row_border_style=OptionsInfo(scss=True, category='summary_row', type='value', value='solid'), summary_row_border_width=OptionsInfo(scss=True, category='summary_row', type='px', value='2px'), summary_row_border_color=OptionsInfo(scss=True, category='summary_row', type='value', value='#D3D3D3'), grand_summary_row_padding=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='8px'), grand_summary_row_padding_horizontal=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='5px'), grand_summary_row_background_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value=None), grand_summary_row_text_transform=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='inherit'), grand_summary_row_border_style=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='double'), grand_summary_row_border_width=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='6px'), grand_summary_row_border_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='#D3D3D3'), footnotes_marks=OptionsInfo(scss=False, category='footnotes', type='values', value='numbers'), source_notes_padding=OptionsInfo(scss=True, category='source_notes', type='px', value='4px'), source_notes_padding_horizontal=OptionsInfo(scss=True, category='source_notes', type='px', value='5px'), source_notes_background_color=OptionsInfo(scss=True, category='source_notes', type='value', value=None), source_notes_font_size=OptionsInfo(scss=True, category='source_notes', type='px', value='90%'), source_notes_border_bottom_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_bottom_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_bottom_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_border_lr_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_lr_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_lr_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_multiline=OptionsInfo(scss=False, category='source_notes', type='boolean', value=True), source_notes_sep=OptionsInfo(scss=False, category='source_notes', type='value', value=' '), row_striping_background_color=OptionsInfo(scss=True, category='row', type='value', value='#F4F4F4'), row_striping_include_stub=OptionsInfo(scss=False, category='row', type='boolean', value=False), row_striping_include_table_body=OptionsInfo(scss=False, category='row', type='boolean', value=False), container_width=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_height=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_padding_x=OptionsInfo(scss=False, category='container', type='px', value='0px'), container_padding_y=OptionsInfo(scss=False, category='container', type='px', value='10px'), container_overflow_x=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), container_overflow_y=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), quarto_disable_processing=OptionsInfo(scss=False, category='quarto', type='logical', value=False), quarto_use_bootstrap=OptionsInfo(scss=False, category='quarto', type='logical', value=False), ihtml_active=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_pagination=OptionsInfo(scss=False, category='ihtml', type='boolean', value=True), ihtml_use_pagination_info=OptionsInfo(scss=False, category='ihtml', type='boolean', value=True), ihtml_use_sorting=OptionsInfo(scss=False, category='ihtml', type='boolean', value=True), ihtml_use_search=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_filters=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_resizers=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_highlight=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_compact_mode=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_text_wrapping=OptionsInfo(scss=False, category='ihtml', type='boolean', value=True), ihtml_use_page_size_select=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_page_size_default=OptionsInfo(scss=False, category='ihtml', type='value', value=10), ihtml_page_size_values=OptionsInfo(scss=False, category='ihtml', type='values', value=[10, 25, 50, 100]), ihtml_pagination_type=OptionsInfo(scss=False, category='ihtml', type='value', value='numbers'), ihtml_height=OptionsInfo(scss=False, category='ihtml', type='value', value='auto'), ihtml_selection_mode=OptionsInfo(scss=False, category='ihtml', type='value', value=None)), _google_font_imports=GoogleFontImports(imports=frozenset()), _has_built=False)

## Explore PRJNA892010, compost metagenome

Microbiome in swine manure composting Genome sequencing and assembly

https://www.sciencedirect.com/science/article/abs/pii/S0956053X2400059X uses this data but is maybe not the author?

In [10]:
reporter.report('PRJNA892010')

shape: (1, 3)
┌─────────────┬─────────┬───────┐
│ bioproject  ┆ n_found ┆ n_sra │
│ ---         ┆ ---     ┆ ---   │
│ str         ┆ u32     ┆ u32   │
╞═════════════╪═════════╪═══════╡
│ PRJNA892010 ┆ 17      ┆ 27    │
└─────────────┴─────────┴───────┘

In [7]:
found_df2.filter(pl.col('bioproject') == 'PRJNA892010')

shape: (17, 72)
┌────────────┬────────────┬────────────┬───────┬───┬───────────┬───────────┬───────────┬───────────┐
│ acc        ┆ bioproject ┆ organism   ┆ count ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_s │
│ ---        ┆ ---        ┆ ---        ┆ ---   ┆   ┆ ---       ┆ create_da ┆ version   ┆ earch     │
│ str        ┆ str        ┆ str        ┆ i64   ┆   ┆ str       ┆ te        ┆ ---       ┆ ---       │
│            ┆            ┆            ┆       ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│            ┆            ┆            ┆       ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR2201353 ┆ PRJNA89201 ┆ compost    ┆ 16    ┆ … ┆ 345134781 ┆ "2022-10- ┆ null      ┆ "31373637 │
│ 3          ┆ 0          ┆ metagenome ┆       ┆   ┆ 7         ┆ 22T15:56: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR2201353 ┆ PRJNA89201 ┆ compost    ┆ 16    ┆ … ┆ 327966787 ┆ "2022-10- ┆ null      ┆ "31373638 │
│ 2          ┆ 0          ┆ metagenome ┆       ┆   ┆ 9         ┆ 22T15:45: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR2201351 ┆ PRJNA89201 ┆ compost    ┆ 10    ┆ … ┆ 321357296 ┆ "2022-10- ┆ null      ┆ "31373652 │
│ 7          ┆ 0          ┆ metagenome ┆       ┆   ┆ 2         ┆ 22T15:39: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR2201352 ┆ PRJNA89201 ┆ compost    ┆ 16    ┆ … ┆ 320782505 ┆ "2022-10- ┆ null      ┆ "31373646 │
│ 4          ┆ 0          ┆ metagenome ┆       ┆   ┆ 5         ┆ 22T15:36: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR2201353 ┆ PRJNA89201 ┆ compost    ┆ 16    ┆ … ┆ 335209883 ┆ "2022-10- ┆ null      ┆ "31373627 │
│ 5          ┆ 0          ┆ metagenome ┆       ┆   ┆ 6         ┆ 22T15:55: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …     ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ SRR2201352 ┆ PRJNA89201 ┆ compost    ┆ 16    ┆ … ┆ 379830927 ┆ "2022-10- ┆ null      ┆ "31373647 │
│ 2          ┆ 0          ┆ metagenome ┆       ┆   ┆ 0         ┆ 22T15:47: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR2201352 ┆ PRJNA89201 ┆ compost    ┆ 16    ┆ … ┆ 312367372 ┆ "2022-10- ┆ null      ┆ "31373629 │
│ 3          ┆ 0          ┆ metagenome ┆       ┆   ┆ 0         ┆ 22T15:38: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR2201352 ┆ PRJNA89201 ┆ compost    ┆ 8     ┆ … ┆ 322982314 ┆ "2022-10- ┆ null      ┆ "31373643 │
│ 7          ┆ 0          ┆ metagenome ┆       ┆   ┆ 8         ┆ 22T15:41: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR2201351 ┆ PRJNA89201 ┆ compost    ┆ 8     ┆ … ┆ 326762569 ┆ "2022-10- ┆ null      ┆ "31373635 │
│ 0          ┆ 0          ┆ metagenome ┆       ┆   ┆ 6         ┆ 22T15:58: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR2201352 ┆ PRJNA89201 ┆ compost    ┆ 16    ┆ … ┆ 435226061 ┆ "2022-10- ┆ null      ┆ "31373641 │
│ 9          ┆ 0          ┆ metagenome ┆       ┆   ┆ 1         ┆ 22T15:49: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
└────────────┴────────────┴────────────┴───────┴───┴───────────┴───────────┴───────────┴───────────┘

## Explore PRJNA292471, bovine metagenome

The purpose of this study was to describe the beef production metagenome and resistome as pens of cattle moved through the feeding period, slaughter and fabrication. Longitudinal, pooled samples from 8 pens of cattle were collected at arrival in and exit from 4 feedlots (feces, soil and drinking water); from the transport trucks used to transport cattle to 2 abattoirs (sponges); from the holding pens at 2 abattoirs (feces and drinking water); and from fabrication belts (sponges) and trimmings (rinsates) at the end of the fabrication process.

paper: [Resistome diversity in cattle and the environment decreases during beef production](https://elifesciences.org/articles/13195), Noyes et al, 2016.

some feces_exit and some feces_holding.

In [8]:
found_df2.filter(pl.col('bioproject') == 'PRJNA292471')

shape: (40, 72)
┌────────────┬────────────┬────────────┬───────┬───┬───────────┬───────────┬───────────┬───────────┐
│ acc        ┆ bioproject ┆ organism   ┆ count ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_s │
│ ---        ┆ ---        ┆ ---        ┆ ---   ┆   ┆ ---       ┆ create_da ┆ version   ┆ earch     │
│ str        ┆ str        ┆ str        ┆ i64   ┆   ┆ str       ┆ te        ┆ ---       ┆ ---       │
│            ┆            ┆            ┆       ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│            ┆            ┆            ┆       ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR3053217 ┆ PRJNA29247 ┆ bovine     ┆ 8     ┆ … ┆ 539583263 ┆ "2015-12- ┆ null      ┆ "292471"  │
│            ┆ 1          ┆ metagenome ┆       ┆   ┆           ┆ 28T17:21: ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR3053182 ┆ PRJNA29247 ┆ bovine     ┆ 12    ┆ … ┆ 228691651 ┆ "2015-12- ┆ null      ┆ "292471"  │
│            ┆ 1          ┆ metagenome ┆       ┆   ┆ 0         ┆ 28T21:13: ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR3053170 ┆ PRJNA29247 ┆ bovine     ┆ 9     ┆ … ┆ 138887056 ┆ "2015-12- ┆ null      ┆ "292471"  │
│            ┆ 1          ┆ metagenome ┆       ┆   ┆ 4         ┆ 28T21:09: ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR3053138 ┆ PRJNA29247 ┆ bovine     ┆ 10    ┆ … ┆ 256977755 ┆ "2015-12- ┆ null      ┆ "292471"  │
│            ┆ 1          ┆ metagenome ┆       ┆   ┆ 5         ┆ 23T16:35: ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR3053162 ┆ PRJNA29247 ┆ bovine     ┆ 9     ┆ … ┆ 205068111 ┆ "2016-01- ┆ null      ┆ "292471"  │
│            ┆ 1          ┆ metagenome ┆       ┆   ┆ 5         ┆ 07T09:46: ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …     ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ SRR3053153 ┆ PRJNA29247 ┆ bovine     ┆ 10    ┆ … ┆ 274760486 ┆ "2015-12- ┆ null      ┆ "292471"  │
│            ┆ 1          ┆ metagenome ┆       ┆   ┆ 0         ┆ 23T16:43: ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR3053208 ┆ PRJNA29247 ┆ bovine     ┆ 10    ┆ … ┆ 945478112 ┆ "2015-12- ┆ null      ┆ "292471"  │
│            ┆ 1          ┆ metagenome ┆       ┆   ┆           ┆ 28T18:23: ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR3053146 ┆ PRJNA29247 ┆ bovine     ┆ 8     ┆ … ┆ 117043815 ┆ "2015-12- ┆ null      ┆ "292471"  │
│            ┆ 1          ┆ metagenome ┆       ┆   ┆ 9         ┆ 23T16:37: ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR3053206 ┆ PRJNA29247 ┆ bovine     ┆ 11    ┆ … ┆ 208797323 ┆ "2015-12- ┆ null      ┆ "292471"  │
│            ┆ 1          ┆ metagenome ┆       ┆   ┆ 9         ┆ 28T18:31: ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR3053215 ┆ PRJNA29247 ┆ bovine     ┆ 9     ┆ … ┆ 746591220 ┆ "2015-12- ┆ null      ┆ "292471"  │
│            ┆ 1          ┆ metagenome ┆       ┆   ┆           ┆ 28T17:22: ┆           ┆           │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
└────────────┴────────────┴────────────┴───────┴───┴───────────┴───────────┴───────────┴───────────┘

## Explore PRJNA506496, fermentation metagenome

This study aims to investigate what microbes capable of utilizing plant cell wall polysaccharides and their functions. The submitted metagenomic sequences include three in vitro fermentation experiments (P1, P2 & H). Of P1, wheat arabinoxylan and rye arabinoxylan were fermented for up to 48 h with a porcine faecal inoculum. Of P2, wheat arabinoxylan and tamarind galactoxyloglucan were fermented for up 72 h with a porcine fecal inoculum. For H, wheat arabinoxylan and tamarind galactoxyloglucan were fermented for up 48 h with a human fecal inoculum. The polysaccharides were the only carbon source in the medium for microbial growth.

all 32 pig (P1 and P2) were found; all 7 H not.

In [9]:
found_df2.filter(pl.col('bioproject') == 'PRJNA506496')

shape: (32, 72)
┌────────────┬────────────┬────────────┬───────┬───┬───────────┬───────────┬───────────┬───────────┐
│ acc        ┆ bioproject ┆ organism   ┆ count ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_s │
│ ---        ┆ ---        ┆ ---        ┆ ---   ┆   ┆ ---       ┆ create_da ┆ version   ┆ earch     │
│ str        ┆ str        ┆ str        ┆ i64   ┆   ┆ str       ┆ te        ┆ ---       ┆ ---       │
│            ┆            ┆            ┆       ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│            ┆            ┆            ┆       ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR8242829 ┆ PRJNA50649 ┆ fermentati ┆ 16    ┆ … ┆ 595478324 ┆ "2018-11- ┆ null      ┆ "10461889 │
│            ┆ 6          ┆ on         ┆       ┆   ┆           ┆ 26T13:39: ┆           ┆ "         │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR8242822 ┆ PRJNA50649 ┆ fermentati ┆ 10    ┆ … ┆ 484418357 ┆ "2018-11- ┆ null      ┆ "10461870 │
│            ┆ 6          ┆ on         ┆       ┆   ┆           ┆ 26T13:37: ┆           ┆ "         │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR8242852 ┆ PRJNA50649 ┆ fermentati ┆ 12    ┆ … ┆ 612632202 ┆ "2018-11- ┆ null      ┆ "10461884 │
│            ┆ 6          ┆ on         ┆       ┆   ┆           ┆ 26T13:42: ┆           ┆ "         │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR8242826 ┆ PRJNA50649 ┆ fermentati ┆ 16    ┆ … ┆ 628406126 ┆ "2018-11- ┆ null      ┆ "10461874 │
│            ┆ 6          ┆ on         ┆       ┆   ┆           ┆ 26T13:39: ┆           ┆ "         │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR8242827 ┆ PRJNA50649 ┆ fermentati ┆ 14    ┆ … ┆ 489367506 ┆ "2018-11- ┆ null      ┆ "10461873 │
│            ┆ 6          ┆ on         ┆       ┆   ┆           ┆ 26T13:39: ┆           ┆ "         │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …     ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ SRR8242824 ┆ PRJNA50649 ┆ fermentati ┆ 16    ┆ … ┆ 564996261 ┆ "2018-11- ┆ null      ┆ "10461872 │
│            ┆ 6          ┆ on         ┆       ┆   ┆           ┆ 26T13:37: ┆           ┆ "         │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR8242828 ┆ PRJNA50649 ┆ fermentati ┆ 16    ┆ … ┆ 623216576 ┆ "2018-11- ┆ null      ┆ "10461890 │
│            ┆ 6          ┆ on         ┆       ┆   ┆           ┆ 26T13:39: ┆           ┆ "         │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR8242856 ┆ PRJNA50649 ┆ fermentati ┆ 16    ┆ … ┆ 522624631 ┆ "2018-11- ┆ null      ┆ "10461880 │
│            ┆ 6          ┆ on         ┆       ┆   ┆           ┆ 26T13:41: ┆           ┆ "         │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR8242847 ┆ PRJNA50649 ┆ fermentati ┆ 12    ┆ … ┆ 603830837 ┆ "2018-11- ┆ null      ┆ "10461885 │
│            ┆ 6          ┆ on         ┆       ┆   ┆           ┆ 26T13:41: ┆           ┆ "         │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR8242855 ┆ PRJNA50649 ┆ fermentati ┆ 16    ┆ … ┆ 497984275 ┆ "2018-11- ┆ null      ┆ "10461879 │
│            ┆ 6          ┆ on         ┆       ┆   ┆           ┆ 26T13:41: ┆           ┆ "         │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
└────────────┴────────────┴────────────┴───────┴───┴───────────┴───────────┴───────────┴───────────┘

In [10]:
found_df2.filter(pl.col('bioproject') == 'PRJNA506496').with_columns(
    exp=pl.col('library_name').str.split('_').list.get(0)
).sort('exp')['exp'].unique()

shape: (2,)
Series: 'exp' [str]
[
	"P1"
	"P2"
]

In [11]:
metadata_df.filter(pl.col('bioproject') == 'PRJNA506496').with_columns(
    exp=pl.col('library_name').str.split('_').list.get(0)
)['exp'].value_counts()

shape: (3, 2)
┌─────┬───────┐
│ exp ┆ count │
│ --- ┆ ---   │
│ str ┆ u32   │
╞═════╪═══════╡
│ P2  ┆ 19    │
│ P1  ┆ 13    │
│ H   ┆ 7     │
└─────┴───────┘

## Explore PRJEB34634, sediment metagenome

We do not fully understand how important types (species) of bacteria and packages of genetic material (genes) coding for antibiotic resistance move between humans, animals and the environment, or where, how and why antibiotic resistance emerges. This study aims to look in detail at the genetic level at bacteria in farm animals, human/animal sewage, sewage treatment works and rivers, to work out the complex network of transmission of important antibiotic-resistant bacteria and antibiotic resistance genes. We will use this information to work out how best to slow down the spread of antibiotic resistance between humans, livestock and the environment.

Publication: [Dissemination and persistence of antimicrobial resistance (AMR) along the wastewater-river continuum](https://www.sciencedirect.com/science/article/pii/S0043135424011035)

In [12]:
found_df2.filter(pl.col('bioproject') == 'PRJEB34634').head(1)['center_name'].item()

'CENTRE FOR ECOLOGY AND HYDROLOGY'

In [13]:
found_df2.filter(pl.col('bioproject') == 'PRJEB34634')

shape: (187, 72)
┌────────────┬────────────┬────────────┬───────┬───┬───────────┬───────────┬───────────┬───────────┐
│ acc        ┆ bioproject ┆ organism   ┆ count ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_s │
│ ---        ┆ ---        ┆ ---        ┆ ---   ┆   ┆ ---       ┆ create_da ┆ version   ┆ earch     │
│ str        ┆ str        ┆ str        ┆ i64   ┆   ┆ str       ┆ te        ┆ ---       ┆ ---       │
│            ┆            ┆            ┆       ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│            ┆            ┆            ┆       ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ ERR3574843 ┆ PRJEB34634 ┆ sediment   ┆ 16    ┆ … ┆ 631562187 ┆ "2020-08- ┆ null      ┆ "15416878 │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 03T15:11: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ ERR3574765 ┆ PRJEB34634 ┆ sediment   ┆ 16    ┆ … ┆ 695261972 ┆ "2020-08- ┆ null      ┆ "15416878 │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 03T14:09: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ ERR3574468 ┆ PRJEB34634 ┆ sediment   ┆ 16    ┆ … ┆ 836986557 ┆ "2020-08- ┆ null      ┆ "15416878 │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 03T16:47: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ ERR3574662 ┆ PRJEB34634 ┆ sediment   ┆ 16    ┆ … ┆ 882060742 ┆ "2020-08- ┆ null      ┆ "15416878 │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 03T15:33: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ ERR3574466 ┆ PRJEB34634 ┆ sediment   ┆ 16    ┆ … ┆ 833371811 ┆ "2020-08- ┆ null      ┆ "15416878 │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 03T16:46: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …     ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ ERR3574838 ┆ PRJEB34634 ┆ sediment   ┆ 16    ┆ … ┆ 632616070 ┆ "2020-08- ┆ null      ┆ "15416878 │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 03T15:15: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ ERR3574488 ┆ PRJEB34634 ┆ sediment   ┆ 15    ┆ … ┆ 742896474 ┆ "2020-08- ┆ null      ┆ "15416878 │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 03T16:42: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ ERR3574477 ┆ PRJEB34634 ┆ sediment   ┆ 15    ┆ … ┆ 704018595 ┆ "2020-08- ┆ null      ┆ "15416878 │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 03T16:43: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ ERR3574486 ┆ PRJEB34634 ┆ sediment   ┆ 15    ┆ … ┆ 796950279 ┆ "2020-08- ┆ null      ┆ "15416878 │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 03T16:48: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ ERR3574517 ┆ PRJEB34634 ┆ sediment   ┆ 16    ┆ … ┆ 995165273 ┆ "2020-08- ┆ null      ┆ "15416878 │
│            ┆            ┆ metagenome ┆       ┆   ┆           ┆ 03T17:31: ┆           ┆ "         │
│            ┆            ┆            ┆       ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
└────────────┴────────────┴────────────┴───────┴───┴───────────┴───────────┴───────────┴───────────┘