# Core species analysis - primary notebook.

Explores both GTDB and GTDB+MAGs searches

In [1]:
import polars as pl

In [2]:
INTERSECT_THRESHOLD=20
PVAL_THRESHOLD=1e-6
FREQ_THRESHOLD=0.95

## Load the two sets of filtered manysearch results

In [3]:
gtdb_df = (
   pl.scan_parquet('../outputs.cds3/gtdb.cds3.x.3216.filtered.pvals.parquet')
    .filter(pl.col('pval') <= PVAL_THRESHOLD)
    .filter(pl.col('intersect_hashes') >= INTERSECT_THRESHOLD)
    .with_columns(
        species_name=pl.col('query_name').str.split(' ').list.slice(1, 2).list.join(" "),
    )
).collect()

In [4]:
mags_df = (
    pl.scan_parquet('../outputs.cds3/mag+gtdb.cds3.x.3216.filtered.pvals.parquet')
    .filter(pl.col('pval') <= PVAL_THRESHOLD)
    .filter(pl.col('intersect_hashes') >= INTERSECT_THRESHOLD)
    .with_columns(
        species_name=pl.col('query_name').str.split(' ').list.slice(1, 2).list.join(" "),
    )
).collect()

## Calculate query (species) frequencies for both

In [5]:
n_acc = gtdb_df['match_name'].n_unique()
gtdb_by_species = gtdb_df.group_by('species_name').agg(
    p_gtdb=pl.len() / n_acc * 100
)
mags_by_species = mags_df.group_by('species_name').agg(
    p_mags=pl.len() / n_acc * 100
)

## Join and filter

In [6]:
combo_df = (
    mags_by_species
    .join(gtdb_by_species, on='species_name', how='full', coalesce=True)
    .filter((pl.col('p_gtdb') >= FREQ_THRESHOLD*100) |
            (pl.col('p_mags') >= FREQ_THRESHOLD*100))
    .sort('p_mags', descending=True)
)
combo_df

shape: (18, 3)
┌─────────────────────────────────┬───────────┬───────────┐
│ species_name                    ┆ p_mags    ┆ p_gtdb    │
│ ---                             ┆ ---       ┆ ---       │
│ str                             ┆ f64       ┆ f64       │
╞═════════════════════════════════╪═══════════╪═══════════╡
│ s__Sodaliphilus sp004557565     ┆ 99.067164 ┆ 99.03607  │
│ s__Lactobacillus amylovorus     ┆ 99.03607  ┆ 97.636816 │
│ s__UBA2868 sp004552595          ┆ 97.916667 ┆ 82.431592 │
│ s__Cryptobacteroides sp9005469… ┆ 97.854478 ┆ 97.885572 │
│ s__Mogibacterium_A kristiansen… ┆ 97.7301   ┆ 91.884328 │
│ …                               ┆ …         ┆ …         │
│ s__Ornithospirochaeta sp022785… ┆ 95.522388 ┆ 95.615672 │
│ s__Cryptobacteroides sp0004326… ┆ 95.242537 ┆ 95.646766 │
│ s__Prevotella sp000434975       ┆ 95.05597  ┆ 96.0199   │
│ s__Prevotella sp900548195       ┆ 94.900498 ┆ 95.05597  │
│ s__CAG-170 sp002404795          ┆ 94.558458 ┆ 95.118159 │
└─────────────────────────────────┴───────────┴───────────┘

In [8]:
combo_df.with_row_index('n', offset=1).style.fmt_number(columns=["p_mags", "p_gtdb"], decimals=2)

GT(_tbl_data=shape: (18, 4)
┌─────┬─────────────────────────────────┬───────────┬───────────┐
│ n   ┆ species_name                    ┆ p_mags    ┆ p_gtdb    │
│ --- ┆ ---                             ┆ ---       ┆ ---       │
│ u32 ┆ str                             ┆ f64       ┆ f64       │
╞═════╪═════════════════════════════════╪═══════════╪═══════════╡
│ 1   ┆ s__Sodaliphilus sp004557565     ┆ 99.067164 ┆ 99.03607  │
│ 2   ┆ s__Lactobacillus amylovorus     ┆ 99.03607  ┆ 97.636816 │
│ 3   ┆ s__UBA2868 sp004552595          ┆ 97.916667 ┆ 82.431592 │
│ 4   ┆ s__Cryptobacteroides sp9005469… ┆ 97.854478 ┆ 97.885572 │
│ 5   ┆ s__Mogibacterium_A kristiansen… ┆ 97.7301   ┆ 91.884328 │
│ …   ┆ …                               ┆ …         ┆ …         │
│ 14  ┆ s__Ornithospirochaeta sp022785… ┆ 95.522388 ┆ 95.615672 │
│ 15  ┆ s__Cryptobacteroides sp0004326… ┆ 95.242537 ┆ 95.646766 │
│ 16  ┆ s__Prevotella sp000434975       ┆ 95.05597  ┆ 96.0199   │
│ 17  ┆ s__Prevotella sp900548195       ┆ 94.900498 ┆ 95.05597  │
│ 18  ┆ s__CAG-170 sp002404795          ┆ 94.558458 ┆ 95.118159 │
└─────┴─────────────────────────────────┴───────────┴───────────┘, _body=<great_tables._gt_data.Body object at 0x7e95c416d490>, _boxhead=Boxhead([ColInfo(var='n', type=<ColInfoTypeEnum.default: 1>, column_label='n', column_align='right', column_width=None), ColInfo(var='species_name', type=<ColInfoTypeEnum.default: 1>, column_label='species_name', column_align='left', column_width=None), ColInfo(var='p_mags', type=<ColInfoTypeEnum.default: 1>, column_label='p_mags', column_align='right', column_width=None), ColInfo(var='p_gtdb', type=<ColInfoTypeEnum.default: 1>, column_label='p_gtdb', column_align='right', column_width=None)]), _stub=<great_tables._gt_data.Stub object at 0x7e95d811dfd0>, _spanners=Spanners([]), _heading=Heading(title=None, subtitle=None, preheader=None), _stubhead=None, _summary_rows=<great_tables._gt_data.SummaryRows object at 0x7e956c9fa2a0>, _summary_rows_grand=<great_tables._gt_data.SummaryRows object at 0x7e956ca37e30>, _source_notes=[], _footnotes=[], _styles=[], _locale=<great_tables._gt_data.Locale object at 0x7e956ca57350>, _formats=[<great_tables._gt_data.FormatInfo object at 0x7e956ca363c0>], _substitutions=[], _col_merge=[], _transforms=[], _options=Options(table_id=OptionsInfo(scss=False, category='table', type='value', value=None), table_caption=OptionsInfo(scss=False, category='table', type='value', value=None), table_width=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_layout=OptionsInfo(scss=True, category='table', type='value', value='fixed'), table_margin_left=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_margin_right=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_background_color=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_additional_css=OptionsInfo(scss=False, category='table', type='values', value=[]), table_font_names=OptionsInfo(scss=False, category='table', type='values', value=['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Helvetica Neue', 'Fira Sans', 'Droid Sans', 'Arial', 'sans-serif']), table_font_size=OptionsInfo(scss=True, category='table', type='px', value='16px'), table_font_weight=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_style=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_color=OptionsInfo(scss=True, category='table', type='value', value='#333333'), table_font_color_light=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_border_top_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_top_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_top_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_top_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_right_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_right_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_right_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), table_border_bottom_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_bottom_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_bottom_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_bottom_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_left_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_left_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_left_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), heading_background_color=OptionsInfo(scss=True, category='heading', type='value', value=None), heading_align=OptionsInfo(scss=True, category='heading', type='value', value='center'), heading_title_font_size=OptionsInfo(scss=True, category='heading', type='px', value='125%'), heading_title_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_subtitle_font_size=OptionsInfo(scss=True, category='heading', type='px', value='85%'), heading_subtitle_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_padding=OptionsInfo(scss=True, category='heading', type='px', value='4px'), heading_padding_horizontal=OptionsInfo(scss=True, category='heading', type='px', value='5px'), heading_border_bottom_style=OptionsInfo(scss=True, category='heading', type='value', value='solid'), heading_border_bottom_width=OptionsInfo(scss=True, category='heading', type='px', value='2px'), heading_border_bottom_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), heading_border_lr_style=OptionsInfo(scss=True, category='heading', type='value', value='none'), heading_border_lr_width=OptionsInfo(scss=True, category='heading', type='px', value='1px'), heading_border_lr_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), column_labels_background_color=OptionsInfo(scss=True, category='column_labels', type='value', value=None), column_labels_font_size=OptionsInfo(scss=True, category='column_labels', type='px', value='100%'), column_labels_font_weight=OptionsInfo(scss=True, category='column_labels', type='value', value='normal'), column_labels_text_transform=OptionsInfo(scss=True, category='column_labels', type='value', value='inherit'), column_labels_padding=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_padding_horizontal=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), column_labels_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), column_labels_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), column_labels_border_top_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_top_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_top_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_bottom_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_bottom_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_bottom_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_lr_style=OptionsInfo(scss=True, category='column_labels', type='value', value='none'), column_labels_border_lr_width=OptionsInfo(scss=True, category='column_labels', type='px', value='1px'), column_labels_border_lr_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_hidden=OptionsInfo(scss=False, category='column_labels', type='boolean', value=False), row_group_background_color=OptionsInfo(scss=True, category='row_group', type='value', value=None), row_group_font_size=OptionsInfo(scss=True, category='row_group', type='px', value='100%'), row_group_font_weight=OptionsInfo(scss=True, category='row_group', type='value', value='initial'), row_group_text_transform=OptionsInfo(scss=True, category='row_group', type='value', value='inherit'), row_group_padding=OptionsInfo(scss=True, category='row_group', type='px', value='8px'), row_group_padding_horizontal=OptionsInfo(scss=True, category='row_group', type='px', value='5px'), row_group_border_top_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_top_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_top_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_right_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_right_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_right_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_bottom_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_bottom_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_bottom_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_left_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_left_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_left_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_as_column=OptionsInfo(scss=False, category='row_group', type='boolean', value=False), table_body_hlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_hlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_hlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), table_body_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_top_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_top_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_top_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_bottom_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_bottom_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_bottom_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), data_row_padding=OptionsInfo(scss=True, category='data_row', type='px', value='8px'), data_row_padding_horizontal=OptionsInfo(scss=True, category='data_row', type='px', value='5px'), stub_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), stub_indent_length=OptionsInfo(scss=True, category='stub', type='px', value='5px'), stub_row_group_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_row_group_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_row_group_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_row_group_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_row_group_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_row_group_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_row_group_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), summary_row_padding=OptionsInfo(scss=True, category='summary_row', type='px', value='8px'), summary_row_padding_horizontal=OptionsInfo(scss=True, category='summary_row', type='px', value='5px'), summary_row_background_color=OptionsInfo(scss=True, category='summary_row', type='value', value=None), summary_row_text_transform=OptionsInfo(scss=True, category='summary_row', type='value', value='inherit'), summary_row_border_style=OptionsInfo(scss=True, category='summary_row', type='value', value='solid'), summary_row_border_width=OptionsInfo(scss=True, category='summary_row', type='px', value='2px'), summary_row_border_color=OptionsInfo(scss=True, category='summary_row', type='value', value='#D3D3D3'), grand_summary_row_padding=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='8px'), grand_summary_row_padding_horizontal=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='5px'), grand_summary_row_background_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value=None), grand_summary_row_text_transform=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='inherit'), grand_summary_row_border_style=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='double'), grand_summary_row_border_width=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='6px'), grand_summary_row_border_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='#D3D3D3'), footnotes_marks=OptionsInfo(scss=False, category='footnotes', type='values', value='numbers'), source_notes_padding=OptionsInfo(scss=True, category='source_notes', type='px', value='4px'), source_notes_padding_horizontal=OptionsInfo(scss=True, category='source_notes', type='px', value='5px'), source_notes_background_color=OptionsInfo(scss=True, category='source_notes', type='value', value=None), source_notes_font_size=OptionsInfo(scss=True, category='source_notes', type='px', value='90%'), source_notes_border_bottom_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_bottom_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_bottom_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_border_lr_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_lr_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_lr_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_multiline=OptionsInfo(scss=False, category='source_notes', type='boolean', value=True), source_notes_sep=OptionsInfo(scss=False, category='source_notes', type='value', value=' '), row_striping_background_color=OptionsInfo(scss=True, category='row', type='value', value='#F4F4F4'), row_striping_include_stub=OptionsInfo(scss=False, category='row', type='boolean', value=False), row_striping_include_table_body=OptionsInfo(scss=False, category='row', type='boolean', value=False), container_width=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_height=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_padding_x=OptionsInfo(scss=False, category='container', type='px', value='0px'), container_padding_y=OptionsInfo(scss=False, category='container', type='px', value='10px'), container_overflow_x=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), container_overflow_y=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), quarto_disable_processing=OptionsInfo(scss=False, category='quarto', type='logical', value=False), quarto_use_bootstrap=OptionsInfo(scss=False, category='quarto', type='logical', value=False), ihtml_active=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_pagination=OptionsInfo(scss=False, category='ihtml', type='boolean', value=True), ihtml_use_pagination_info=OptionsInfo(scss=False, category='ihtml', type='boolean', value=True), ihtml_use_sorting=OptionsInfo(scss=False, category='ihtml', type='boolean', value=True), ihtml_use_search=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_filters=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_resizers=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_highlight=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_compact_mode=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_text_wrapping=OptionsInfo(scss=False, category='ihtml', type='boolean', value=True), ihtml_use_page_size_select=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_page_size_default=OptionsInfo(scss=False, category='ihtml', type='value', value=10), ihtml_page_size_values=OptionsInfo(scss=False, category='ihtml', type='values', value=[10, 25, 50, 100]), ihtml_pagination_type=OptionsInfo(scss=False, category='ihtml', type='value', value='numbers'), ihtml_height=OptionsInfo(scss=False, category='ihtml', type='value', value='auto'), ihtml_selection_mode=OptionsInfo(scss=False, category='ihtml', type='value', value=None)), _google_font_imports=GoogleFontImports(imports=frozenset()), _has_built=False)

In [9]:
for s in combo_df['species_name']:
    print(f"xx.append(dict(name=\'{s}\', descr=\'\'))")

xx.append(dict(name='s__Sodaliphilus sp004557565', descr=''))
xx.append(dict(name='s__Lactobacillus amylovorus', descr=''))
xx.append(dict(name='s__UBA2868 sp004552595', descr=''))
xx.append(dict(name='s__Cryptobacteroides sp900546925', descr=''))
xx.append(dict(name='s__Mogibacterium_A kristiansenii', descr=''))
xx.append(dict(name='s__JAFBIX01 sp021531895', descr=''))
xx.append(dict(name='s__Fimisoma sp002320005', descr=''))
xx.append(dict(name='s__Prevotella sp002251295', descr=''))
xx.append(dict(name='s__Floccifex porci', descr=''))
xx.append(dict(name='s__Cryptobacteroides sp034089285', descr=''))
xx.append(dict(name='s__Bariatricus sp004560705', descr=''))
xx.append(dict(name='s__Colivicinus sp002299675', descr=''))
xx.append(dict(name='s__Cryptobacteroides sp000434935', descr=''))
xx.append(dict(name='s__Ornithospirochaeta sp022785155', descr=''))
xx.append(dict(name='s__Cryptobacteroides sp000432655', descr=''))
xx.append(dict(name='s__Prevotella sp000434975', descr=''))
xx.append(dict(name='s__Prevotella sp900548195', descr=''))
xx.append(dict(name='s__CAG-170 sp002404795', descr=''))

In [10]:
xx = []
xx.append(dict(species_name='s__Escherichia coli',
               descr='well-known gut-associated'))
xx.append(dict(species_name='s__Sodaliphilus sp004557565', descr='genus is pig gut associated'))
xx.append(dict(species_name='s__Lactobacillus amylovorus', descr='well-known pig associated species'))
xx.append(dict(species_name='s__UBA2868 sp004552595', descr=''))
xx.append(dict(species_name='s__Cryptobacteroides sp900546925', descr=''))
xx.append(dict(species_name='s__Mogibacterium_A kristiansenii', descr='well-known pig associated species'))
xx.append(dict(species_name='s__JAFBIX01 sp021531895', descr=''))
xx.append(dict(species_name='s__Fimisoma sp002320005', descr='genus is found in chicken gut'))
xx.append(dict(species_name='s__Prevotella sp002251295', descr='genus is human gut associated'))
xx.append(dict(species_name='s__Cryptobacteroides sp034089285', descr='genus is human gut associated'))
xx.append(dict(species_name='s__Floccifex porci', descr='well-known pig-associated'))
xx.append(dict(species_name='s__Bariatricus sp004560705', descr='genus is human gut associated'))
xx.append(dict(species_name='s__Colivicinus sp002299675', descr='genus is human gut associated'))
xx.append(dict(species_name='s__Cryptobacteroides sp000434935', descr='genus is human gut associated'))
xx.append(dict(species_name='s__Ornithospirochaeta sp022785155', descr='genus found in chicken gut'))
xx.append(dict(species_name='s__Cryptobacteroides sp000432655', descr='genus is human gut associated'))
xx.append(dict(species_name='s__Prevotella sp000434975', descr='genus is human gut associated'))
xx.append(dict(species_name='s__Prevotella sp900548195', descr='genus is human gut associated'))
xx.append(dict(species_name='s__CAG-170 sp002404795', descr=''))
descr_df = pl.DataFrame(xx)
descr_df

shape: (19, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ species_name                    ┆ descr                           │
│ ---                             ┆ ---                             │
│ str                             ┆ str                             │
╞═════════════════════════════════╪═════════════════════════════════╡
│ s__Escherichia coli             ┆ well-known gut-associated       │
│ s__Sodaliphilus sp004557565     ┆ genus is pig gut associated     │
│ s__Lactobacillus amylovorus     ┆ well-known pig associated spec… │
│ s__UBA2868 sp004552595          ┆                                 │
│ s__Cryptobacteroides sp9005469… ┆                                 │
│ …                               ┆ …                               │
│ s__Ornithospirochaeta sp022785… ┆ genus found in chicken gut      │
│ s__Cryptobacteroides sp0004326… ┆ genus is human gut associated   │
│ s__Prevotella sp000434975       ┆ genus is human gut associated   │
│ s__Prevotella sp900548195       ┆ genus is human gut associated   │
│ s__CAG-170 sp002404795          ┆                                 │
└─────────────────────────────────┴─────────────────────────────────┘

In [11]:
explain_df = combo_df.join(descr_df, on='species_name', how='left')

In [12]:
from great_tables import style, loc, GT

xx = GT(explain_df, rowname_col="species_name")
(xx
 .fmt_number(columns=["p_mags", "p_gtdb"], decimals=1)
 .cols_label({ 'p_mags': '% GTDB+MAGs', 'p_gtdb': '% (GTDB only)', 'descr': 'description'})
)

GT(_tbl_data=shape: (18, 4)
┌─────────────────────────────────┬───────────┬───────────┬─────────────────────────────────┐
│ species_name                    ┆ p_mags    ┆ p_gtdb    ┆ descr                           │
│ ---                             ┆ ---       ┆ ---       ┆ ---                             │
│ str                             ┆ f64       ┆ f64       ┆ str                             │
╞═════════════════════════════════╪═══════════╪═══════════╪═════════════════════════════════╡
│ s__Sodaliphilus sp004557565     ┆ 99.067164 ┆ 99.03607  ┆ genus is pig gut associated     │
│ s__Lactobacillus amylovorus     ┆ 99.03607  ┆ 97.636816 ┆ well-known pig associated spec… │
│ s__UBA2868 sp004552595          ┆ 97.916667 ┆ 82.431592 ┆                                 │
│ s__Cryptobacteroides sp9005469… ┆ 97.854478 ┆ 97.885572 ┆                                 │
│ s__Mogibacterium_A kristiansen… ┆ 97.7301   ┆ 91.884328 ┆ well-known pig associated spec… │
│ …                               ┆ …         ┆ …         ┆ …                               │
│ s__Ornithospirochaeta sp022785… ┆ 95.522388 ┆ 95.615672 ┆ genus found in chicken gut      │
│ s__Cryptobacteroides sp0004326… ┆ 95.242537 ┆ 95.646766 ┆ genus is human gut associated   │
│ s__Prevotella sp000434975       ┆ 95.05597  ┆ 96.0199   ┆ genus is human gut associated   │
│ s__Prevotella sp900548195       ┆ 94.900498 ┆ 95.05597  ┆ genus is human gut associated   │
│ s__CAG-170 sp002404795          ┆ 94.558458 ┆ 95.118159 ┆                                 │
└─────────────────────────────────┴───────────┴───────────┴─────────────────────────────────┘, _body=<great_tables._gt_data.Body object at 0x7e95d811d850>, _boxhead=Boxhead([ColInfo(var='species_name', type=<ColInfoTypeEnum.stub: 2>, column_label='species_name', column_align='left', column_width=None), ColInfo(var='p_mags', type=<ColInfoTypeEnum.default: 1>, column_label='% GTDB+MAGs', column_align='right', column_width=None), ColInfo(var='p_gtdb', type=<ColInfoTypeEnum.default: 1>, column_label='% (GTDB only)', column_align='right', column_width=None), ColInfo(var='descr', type=<ColInfoTypeEnum.default: 1>, column_label='description', column_align='left', column_width=None)]), _stub=<great_tables._gt_data.Stub object at 0x7e956ca56b10>, _spanners=Spanners([]), _heading=Heading(title=None, subtitle=None, preheader=None), _stubhead=None, _summary_rows=<great_tables._gt_data.SummaryRows object at 0x7e95d811dc10>, _summary_rows_grand=<great_tables._gt_data.SummaryRows object at 0x7e956c9adc70>, _source_notes=[], _footnotes=[], _styles=[], _locale=<great_tables._gt_data.Locale object at 0x7e956c0e9520>, _formats=[<great_tables._gt_data.FormatInfo object at 0x7e956c0e92b0>], _substitutions=[], _col_merge=[], _transforms=[], _options=Options(table_id=OptionsInfo(scss=False, category='table', type='value', value=None), table_caption=OptionsInfo(scss=False, category='table', type='value', value=None), table_width=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_layout=OptionsInfo(scss=True, category='table', type='value', value='fixed'), table_margin_left=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_margin_right=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_background_color=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_additional_css=OptionsInfo(scss=False, category='table', type='values', value=[]), table_font_names=OptionsInfo(scss=False, category='table', type='values', value=['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Helvetica Neue', 'Fira Sans', 'Droid Sans', 'Arial', 'sans-serif']), table_font_size=OptionsInfo(scss=True, category='table', type='px', value='16px'), table_font_weight=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_style=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_color=OptionsInfo(scss=True, category='table', type='value', value='#333333'), table_font_color_light=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_border_top_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_top_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_top_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_top_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_right_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_right_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_right_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), table_border_bottom_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_bottom_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_bottom_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_bottom_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_left_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_left_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_left_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), heading_background_color=OptionsInfo(scss=True, category='heading', type='value', value=None), heading_align=OptionsInfo(scss=True, category='heading', type='value', value='center'), heading_title_font_size=OptionsInfo(scss=True, category='heading', type='px', value='125%'), heading_title_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_subtitle_font_size=OptionsInfo(scss=True, category='heading', type='px', value='85%'), heading_subtitle_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_padding=OptionsInfo(scss=True, category='heading', type='px', value='4px'), heading_padding_horizontal=OptionsInfo(scss=True, category='heading', type='px', value='5px'), heading_border_bottom_style=OptionsInfo(scss=True, category='heading', type='value', value='solid'), heading_border_bottom_width=OptionsInfo(scss=True, category='heading', type='px', value='2px'), heading_border_bottom_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), heading_border_lr_style=OptionsInfo(scss=True, category='heading', type='value', value='none'), heading_border_lr_width=OptionsInfo(scss=True, category='heading', type='px', value='1px'), heading_border_lr_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), column_labels_background_color=OptionsInfo(scss=True, category='column_labels', type='value', value=None), column_labels_font_size=OptionsInfo(scss=True, category='column_labels', type='px', value='100%'), column_labels_font_weight=OptionsInfo(scss=True, category='column_labels', type='value', value='normal'), column_labels_text_transform=OptionsInfo(scss=True, category='column_labels', type='value', value='inherit'), column_labels_padding=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_padding_horizontal=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), column_labels_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), column_labels_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), column_labels_border_top_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_top_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_top_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_bottom_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_bottom_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_bottom_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_lr_style=OptionsInfo(scss=True, category='column_labels', type='value', value='none'), column_labels_border_lr_width=OptionsInfo(scss=True, category='column_labels', type='px', value='1px'), column_labels_border_lr_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_hidden=OptionsInfo(scss=False, category='column_labels', type='boolean', value=False), row_group_background_color=OptionsInfo(scss=True, category='row_group', type='value', value=None), row_group_font_size=OptionsInfo(scss=True, category='row_group', type='px', value='100%'), row_group_font_weight=OptionsInfo(scss=True, category='row_group', type='value', value='initial'), row_group_text_transform=OptionsInfo(scss=True, category='row_group', type='value', value='inherit'), row_group_padding=OptionsInfo(scss=True, category='row_group', type='px', value='8px'), row_group_padding_horizontal=OptionsInfo(scss=True, category='row_group', type='px', value='5px'), row_group_border_top_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_top_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_top_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_right_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_right_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_right_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_bottom_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_bottom_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_bottom_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_left_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_left_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_left_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_as_column=OptionsInfo(scss=False, category='row_group', type='boolean', value=False), table_body_hlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_hlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_hlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), table_body_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_top_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_top_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_top_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_bottom_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_bottom_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_bottom_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), data_row_padding=OptionsInfo(scss=True, category='data_row', type='px', value='8px'), data_row_padding_horizontal=OptionsInfo(scss=True, category='data_row', type='px', value='5px'), stub_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), stub_indent_length=OptionsInfo(scss=True, category='stub', type='px', value='5px'), stub_row_group_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_row_group_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_row_group_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_row_group_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_row_group_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_row_group_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_row_group_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), summary_row_padding=OptionsInfo(scss=True, category='summary_row', type='px', value='8px'), summary_row_padding_horizontal=OptionsInfo(scss=True, category='summary_row', type='px', value='5px'), summary_row_background_color=OptionsInfo(scss=True, category='summary_row', type='value', value=None), summary_row_text_transform=OptionsInfo(scss=True, category='summary_row', type='value', value='inherit'), summary_row_border_style=OptionsInfo(scss=True, category='summary_row', type='value', value='solid'), summary_row_border_width=OptionsInfo(scss=True, category='summary_row', type='px', value='2px'), summary_row_border_color=OptionsInfo(scss=True, category='summary_row', type='value', value='#D3D3D3'), grand_summary_row_padding=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='8px'), grand_summary_row_padding_horizontal=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='5px'), grand_summary_row_background_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value=None), grand_summary_row_text_transform=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='inherit'), grand_summary_row_border_style=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='double'), grand_summary_row_border_width=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='6px'), grand_summary_row_border_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='#D3D3D3'), footnotes_marks=OptionsInfo(scss=False, category='footnotes', type='values', value='numbers'), source_notes_padding=OptionsInfo(scss=True, category='source_notes', type='px', value='4px'), source_notes_padding_horizontal=OptionsInfo(scss=True, category='source_notes', type='px', value='5px'), source_notes_background_color=OptionsInfo(scss=True, category='source_notes', type='value', value=None), source_notes_font_size=OptionsInfo(scss=True, category='source_notes', type='px', value='90%'), source_notes_border_bottom_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_bottom_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_bottom_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_border_lr_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_lr_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_lr_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_multiline=OptionsInfo(scss=False, category='source_notes', type='boolean', value=True), source_notes_sep=OptionsInfo(scss=False, category='source_notes', type='value', value=' '), row_striping_background_color=OptionsInfo(scss=True, category='row', type='value', value='#F4F4F4'), row_striping_include_stub=OptionsInfo(scss=False, category='row', type='boolean', value=False), row_striping_include_table_body=OptionsInfo(scss=False, category='row', type='boolean', value=False), container_width=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_height=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_padding_x=OptionsInfo(scss=False, category='container', type='px', value='0px'), container_padding_y=OptionsInfo(scss=False, category='container', type='px', value='10px'), container_overflow_x=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), container_overflow_y=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), quarto_disable_processing=OptionsInfo(scss=False, category='quarto', type='logical', value=False), quarto_use_bootstrap=OptionsInfo(scss=False, category='quarto', type='logical', value=False), ihtml_active=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_pagination=OptionsInfo(scss=False, category='ihtml', type='boolean', value=True), ihtml_use_pagination_info=OptionsInfo(scss=False, category='ihtml', type='boolean', value=True), ihtml_use_sorting=OptionsInfo(scss=False, category='ihtml', type='boolean', value=True), ihtml_use_search=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_filters=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_resizers=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_highlight=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_compact_mode=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_text_wrapping=OptionsInfo(scss=False, category='ihtml', type='boolean', value=True), ihtml_use_page_size_select=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_page_size_default=OptionsInfo(scss=False, category='ihtml', type='value', value=10), ihtml_page_size_values=OptionsInfo(scss=False, category='ihtml', type='values', value=[10, 25, 50, 100]), ihtml_pagination_type=OptionsInfo(scss=False, category='ihtml', type='value', value='numbers'), ihtml_height=OptionsInfo(scss=False, category='ihtml', type='value', value='auto'), ihtml_selection_mode=OptionsInfo(scss=False, category='ihtml', type='value', value=None)), _google_font_imports=GoogleFontImports(imports=frozenset()), _has_built=False)