# Explore the metagenome accessions missing some or all of the core microbes

In [1]:
import polars as pl

## Load the manysearch results and filter at our default threshold of 20

In [2]:
df = (
    pl.scan_parquet('../outputs.cds3/pq/mag+gtdb.cds3.x.3216.manysearch.parquet')
    .filter(pl.col('intersect_hashes') >= 20)
).collect()

In [3]:
df

shape: (2_357_261, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ average_c ┆ max_conta ┆ n_weighte ┆ total_we │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ ontainmen ┆ inment_an ┆ d_found   ┆ ighted_h │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ t_ani     ┆ i         ┆ ---       ┆ ashes    │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ GCA_96360 ┆ 98787da90 ┆ SRR111833 ┆ 0.18467   ┆ … ┆ 0.831609  ┆ 0.922713  ┆ 4656      ┆ 1066419  │
│ 6895 s__M ┆ 33ca08f4a ┆ 30        ┆           ┆   ┆           ┆           ┆           ┆          │
│ ethanocat ┆ 8e0e553cd ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ell…      ┆ 3be…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCF_90216 ┆ ca79ba3d2 ┆ SRR111833 ┆ 0.003933  ┆ … ┆ 0.720727  ┆ 0.768183  ┆ 103       ┆ 1066419  │
│ 3005 s__E ┆ b584c0ffd ┆ 30        ┆           ┆   ┆           ┆           ┆           ┆          │
│ nterococc ┆ c81940fc1 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ us …      ┆ 984…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCF_00125 ┆ 2e7f136ca ┆ SRR111833 ┆ 0.017325  ┆ … ┆ 0.809462  ┆ 0.824381  ┆ 22416     ┆ 1066419  │
│ 6715 s__E ┆ e1634a43c ┆ 30        ┆           ┆   ┆           ┆           ┆           ┆          │
│ scherichi ┆ 52b78cb97 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ a c…      ┆ 0e0…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_90051 ┆ caef9e116 ┆ SRR111833 ┆ 0.000643  ┆ … ┆ 0.675688  ┆ 0.704729  ┆ 105       ┆ 1066419  │
│ 3975 s__K ┆ e27e60950 ┆ 30        ┆           ┆   ┆           ┆           ┆           ┆          │
│ lebsiella ┆ 2c15f8f56 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ pn…       ┆ 877…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_03411 ┆ c670dcee3 ┆ SRR111833 ┆ 0.101147  ┆ … ┆ 0.810399  ┆ 0.896637  ┆ 631       ┆ 1066419  │
│ 8145 s__B ┆ e5cbe4262 ┆ 30        ┆           ┆   ┆           ┆           ┆           ┆          │
│ utyricimo ┆ 71f4a3a7b ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ nas…      ┆ 589…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ GCA_04167 ┆ 03f6ba47d ┆ SRR143691 ┆ 0.025259  ┆ … ┆ 0.723287  ┆ 0.839315  ┆ 196       ┆ 7255242  │
│ 5925 s__P ┆ e50e2dd2a ┆ 46        ┆           ┆   ┆           ┆           ┆           ┆          │
│ aracholep ┆ 1ff2d60c2 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ las…      ┆ 4a5…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_01750 ┆ 61144402e ┆ SRR143691 ┆ 0.134986  ┆ … ┆ 0.756227  ┆ 0.909045  ┆ 67        ┆ 7255242  │
│ 8245      ┆ 05944f3e9 ┆ 46        ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__NHYM01 ┆ 7c3969a96 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ sp0175…   ┆ 231…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_93429 ┆ 6fa54e46f ┆ SRR143691 ┆ 0.018105  ┆ … ┆ 0.718621  ┆ 0.82611   ┆ 102       ┆ 7255242  │
│ 5335 s__E ┆ 6187a0282 ┆ 46        ┆           ┆   ┆           ┆           ┆           ┆          │
│ ubacteriu ┆ c6cddc1d3 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ m_F…      ┆ 048…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_94707 ┆ 353411538 ┆ SRR143691 ┆ 0.627321  ┆ … ┆ 0.836401  ┆ 0.97804   ┆ 21631     ┆ 7255242  │
│ 2185 s__C ┆ 20c9ef1f6 ┆ 46        ┆           ┆   ┆           ┆           ┆           ┆          │
│ lostridiu ┆ 55092a011 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ m s…      ┆ 354…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_02161 ┆ 1d4ec9840 ┆ SRR143691 ┆ 0.227723  ┆ … ┆ 0.782937  ┆ 0.931967  ┆ 320       ┆ 7255242  │
│ 6655 s__U ┆ 361f4f7b1 ┆ 46        ┆           ┆   ┆           ┆           ┆           ┆          │
│ BA2903    ┆ c9fc3945c ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ sp900…    ┆ 62b…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Summarize by species to get core

In [4]:
n_acc = df['match_name'].n_unique()
by_species = df.group_by('query_name').agg(
    freq=pl.len() / n_acc
)

In [5]:
with pl.Config(tbl_rows=-1):
    print(by_species.sort('freq', descending=True).filter(pl.col('freq') >= 0.95))

shape: (17, 2)
┌─────────────────────────────────┬──────────┐
│ query_name                      ┆ freq     │
│ ---                             ┆ ---      │
│ str                             ┆ f64      │
╞═════════════════════════════════╪══════════╡
│ GCF_001256715 s__Escherichia c… ┆ 0.992537 │
│ GCA_945834365 s__Sodaliphilus … ┆ 0.990983 │
│ GCF_028308525 s__Lactobacillus… ┆ 0.990361 │
│ GCA_946007015 s__UBA2868 sp004… ┆ 0.979167 │
│ GCA_927798655 s__Cryptobactero… ┆ 0.978545 │
│ GCA_034171835 s__Mogibacterium… ┆ 0.977301 │
│ GCA_945872445 s__JAFBIX01 sp02… ┆ 0.974502 │
│ GCA_946408405 s__Fimisoma sp00… ┆ 0.973259 │
│ GCA_945501735 s__Prevotella sp… ┆ 0.968595 │
│ GCA_945876695 s__Floccifex por… ┆ 0.968284 │
│ GCA_004561115 s__Cryptobactero… ┆ 0.968284 │
│ GCA_945877245 s__Bariatricus s… ┆ 0.966418 │
│ GCA_022781365 s__Colivicinus s… ┆ 0.958333 │
│ GCA_945932635 s__Cryptobactero… ┆ 0.956468 │
│ GCA_945938975 s__Ornithospiroc… ┆ 0.955224 │
│ GCA_934726065 s__Cryptobactero… ┆ 0.952425 │
│ GCA_028727695 s__Prevotella sp… ┆ 0.95056  │
└─────────────────────────────────┴──────────┘

In [6]:
CORE_NAMES = set(by_species.sort('freq', descending=True).filter(pl.col('freq') >= 0.95)['query_name'])
assert len(CORE_NAMES) == 17
print(CORE_NAMES)

{'GCA_927798655 s__Cryptobacteroides sp900546925 singlehash', 'GCA_022781365 s__Colivicinus sp002299675 singlehash', 'GCF_001256715 s__Escherichia coli singlehash', 'GCA_946408405 s__Fimisoma sp002320005 singlehash', 'GCA_945501735 s__Prevotella sp002251295 singlehash', 'GCA_945938975 s__Ornithospirochaeta sp022785155 singlehash', 'GCA_946007015 s__UBA2868 sp004552595 singlehash', 'GCF_028308525 s__Lactobacillus amylovorus singlehash', 'GCA_945877245 s__Bariatricus sp004560705 singlehash', 'GCA_945872445 s__JAFBIX01 sp021531895 singlehash', 'GCA_945876695 s__Floccifex porci singlehash', 'GCA_934726065 s__Cryptobacteroides sp000432655 singlehash', 'GCA_028727695 s__Prevotella sp000434975 singlehash', 'GCA_945834365 s__Sodaliphilus sp004557565 singlehash', 'GCA_004561115 s__Cryptobacteroides sp034089285 singlehash', 'GCA_945932635 s__Cryptobacteroides sp000434935 singlehash', 'GCA_034171835 s__Mogibacterium_A kristiansenii singlehash'}

## Ask questions about core species by metagenome

In [7]:
by_acc = (
    df
    .filter(pl.col('query_name').is_in(CORE_NAMES))
    .group_by('match_name').agg(
        n_core=pl.len()
    )
).sort('n_core')

In [8]:
by_acc

shape: (3_216, 2)
┌─────────────┬────────┐
│ match_name  ┆ n_core │
│ ---         ┆ ---    │
│ str         ┆ u32    │
╞═════════════╪════════╡
│ SRR12795790 ┆ 1      │
│ SRR12795785 ┆ 1      │
│ ERR3212036  ┆ 1      │
│ ERR3212024  ┆ 1      │
│ ERR3212025  ┆ 1      │
│ …           ┆ …      │
│ SRR11126092 ┆ 17     │
│ SRR8960407  ┆ 17     │
│ SRR14812355 ┆ 17     │
│ ERR1135210  ┆ 17     │
│ ERR1135341  ┆ 17     │
└─────────────┴────────┘

In [9]:
by_acc_16 = by_acc.filter(pl.col('n_core') == 16)
with pl.Config(tbl_rows=-1):
    print(df
 .filter(pl.col('query_name').is_in(CORE_NAMES))
 ['query_name'].value_counts().sort('count')
)
print(df['match_name'].n_unique())

shape: (17, 2)
┌─────────────────────────────────┬───────┐
│ query_name                      ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ GCA_028727695 s__Prevotella sp… ┆ 3057  │
│ GCA_934726065 s__Cryptobactero… ┆ 3063  │
│ GCA_945938975 s__Ornithospiroc… ┆ 3072  │
│ GCA_945932635 s__Cryptobactero… ┆ 3076  │
│ GCA_022781365 s__Colivicinus s… ┆ 3082  │
│ GCA_945877245 s__Bariatricus s… ┆ 3108  │
│ GCA_004561115 s__Cryptobactero… ┆ 3114  │
│ GCA_945876695 s__Floccifex por… ┆ 3114  │
│ GCA_945501735 s__Prevotella sp… ┆ 3115  │
│ GCA_946408405 s__Fimisoma sp00… ┆ 3130  │
│ GCA_945872445 s__JAFBIX01 sp02… ┆ 3134  │
│ GCA_034171835 s__Mogibacterium… ┆ 3143  │
│ GCA_927798655 s__Cryptobactero… ┆ 3147  │
│ GCA_946007015 s__UBA2868 sp004… ┆ 3149  │
│ GCF_028308525 s__Lactobacillus… ┆ 3185  │
│ GCA_945834365 s__Sodaliphilus … ┆ 3187  │
│ GCF_001256715 s__Escherichia c… ┆ 3192  │
└─────────────────────────────────┴───────┘
3216

## What's our distribution of numbers?

In [35]:
with pl.Config(tbl_rows=-1):
    print(by_acc['n_core'].value_counts())

print(len(by_acc.filter(pl.col('n_core') < 17)))

shape: (17, 2)
┌────────┬───────┐
│ n_core ┆ count │
│ ---    ┆ ---   │
│ u32    ┆ u32   │
╞════════╪═══════╡
│ 1      ┆ 6     │
│ 2      ┆ 12    │
│ 3      ┆ 3     │
│ 4      ┆ 5     │
│ 5      ┆ 8     │
│ 6      ┆ 3     │
│ 7      ┆ 7     │
│ 8      ┆ 5     │
│ 9      ┆ 5     │
│ 10     ┆ 9     │
│ 11     ┆ 10    │
│ 12     ┆ 15    │
│ 13     ┆ 32    │
│ 14     ┆ 38    │
│ 15     ┆ 109   │
│ 16     ┆ 279   │
│ 17     ┆ 2670  │
└────────┴───────┘
546

## Let's pick 10 as an arbitrary cutoff

In [11]:
low_core_acc = by_acc.filter(pl.col('n_core') < 10)
len(low_core_acc)

54

## Load in the SRA metadata

In [12]:
metadata_df = (
    pl.scan_parquet("/group/ctbrowngrp5/sra-metagenomes/20241128-metadata.parquet")
    .filter(pl.col("acc") != "NP")
    .filter(pl.col("assay_type") == "WGS")
#    .select(["acc", "organism", "bioproject", "mbases", "host", "project_name"]) 
    .collect()
)

In [13]:
low_core_acc = low_core_acc.rename({'match_name': 'acc'})

In [14]:
low_core_acc2 = low_core_acc.join(metadata_df, on='acc', how='left')
low_core_acc2

shape: (54, 68)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ acc        ┆ n_core ┆ sample_nam ┆ sample_na ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_s │
│ ---        ┆ ---    ┆ e          ┆ me_sam    ┆   ┆ ---       ┆ create_da ┆ version   ┆ earch     │
│ str        ┆ u32    ┆ ---        ┆ ---       ┆   ┆ str       ┆ te        ┆ ---       ┆ ---       │
│            ┆        ┆ str        ┆ list[str] ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│            ┆        ┆            ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR1279579 ┆ 1      ┆ pig_colon_ ┆ []        ┆ … ┆ 389259080 ┆ "2020-10- ┆ null      ┆ "16396817 │
│ 0          ┆        ┆ 405        ┆           ┆   ┆ 7         ┆ 08T12:38: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1279578 ┆ 1      ┆ pig_colon_ ┆ []        ┆ … ┆ 273201724 ┆ "2020-10- ┆ null      ┆ "16396804 │
│ 5          ┆        ┆ 403        ┆           ┆   ┆ 0         ┆ 08T12:38: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ ERR3212036 ┆ 1      ┆ SAMEA54146 ┆ ["DTU2018 ┆ … ┆ 704684139 ┆ "2021-11- ┆ null      ┆ "11156638 │
│            ┆        ┆ 82         ┆ _MG_1516_ ┆   ┆           ┆ 04T10:00: ┆           ┆ "         │
│            ┆        ┆            ┆ LPSX_NX2N ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│            ┆        ┆            ┆ S_P…      ┆   ┆           ┆           ┆           ┆           │
│ ERR3212024 ┆ 1      ┆ SAMEA54146 ┆ ["DTU2018 ┆ … ┆ 835005957 ┆ "2021-11- ┆ null      ┆ "11156626 │
│            ┆        ┆ 70         ┆ _MG_1468_ ┆   ┆           ┆ 04T09:07: ┆           ┆ "         │
│            ┆        ┆            ┆ LPSX_NX1N ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│            ┆        ┆            ┆ S_P…      ┆   ┆           ┆           ┆           ┆           │
│ ERR3212025 ┆ 1      ┆ SAMEA54146 ┆ ["DTU2018 ┆ … ┆ 105388401 ┆ "2021-11- ┆ null      ┆ "11156627 │
│            ┆        ┆ 71         ┆ _MG_1469_ ┆   ┆ 1         ┆ 04T09:07: ┆           ┆ "         │
│            ┆        ┆            ┆ LPSX_NX1N ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│            ┆        ┆            ┆ S_P…      ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …      ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ SRR1804890 ┆ 9      ┆ Berberine4 ┆ []        ┆ … ┆ 352673980 ┆ "2022-02- ┆ null      ┆ "25980741 │
│ 1          ┆        ┆            ┆           ┆   ┆ 2         ┆ 18T08:27: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR5240741 ┆ 9      ┆ 2016_CRC_S ┆ []        ┆ … ┆ 181714007 ┆ "2017-02- ┆ null      ┆ "2016_CRC │
│            ┆        ┆ P2         ┆           ┆   ┆ 3         ┆ 09T10:58: ┆           ┆ _SP2"     │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1118353 ┆ 9      ┆ Ja31/29792 ┆ []        ┆ … ┆ 332399481 ┆ "2020-02- ┆ null      ┆ "11097709 │
│ 3          ┆        ┆            ┆           ┆   ┆           ┆ 26T03:24: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1112538 ┆ 9      ┆ Ja31/29792 ┆ []        ┆ … ┆ 306296301 ┆ "2020-02- ┆ null      ┆ "11097709 │
│ 8          ┆        ┆            ┆           ┆   ┆           ┆ 20T21:13: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1804890 ┆ 9      ┆ Berberine3 ┆ []        ┆ … ┆ 344807609 ┆ "2022-02- ┆ null      ┆ "25980740 │
│ 2          ┆        ┆            ┆           ┆   ┆ 5         ┆ 18T08:14: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Summarize by bioproject

In [15]:
missing_sum_df = low_core_acc2.group_by('bioproject').agg(
    n_missing=pl.len()
).sort('n_missing')
missing_sum_df

shape: (9, 2)
┌─────────────┬───────────┐
│ bioproject  ┆ n_missing │
│ ---         ┆ ---       │
│ str         ┆ u32       │
╞═════════════╪═══════════╡
│ PRJNA741980 ┆ 1         │
│ PRJNA471402 ┆ 1         │
│ PRJNA629856 ┆ 1         │
│ PRJNA408025 ┆ 3         │
│ PRJNA807368 ┆ 4         │
│ PRJNA526405 ┆ 8         │
│ PRJNA373834 ┆ 8         │
│ PRJEB31650  ┆ 9         │
│ PRJNA668104 ┆ 19        │
└─────────────┴───────────┘

## 9 bioprojects are responsible for the 54 samples with 9 or fewer core species

In [16]:
# how many samples in bioprojects total??
total_sum_df = (
    metadata_df
    .join(low_core_acc2, on='bioproject', how='semi')
    .filter(pl.col('organism') == 'pig gut metagenome')
    .group_by('bioproject')
    .agg(total=pl.len(), org=pl.col('organism').unique())
)
total_sum_df

shape: (9, 3)
┌─────────────┬───────┬────────────────────────┐
│ bioproject  ┆ total ┆ org                    │
│ ---         ┆ ---   ┆ ---                    │
│ str         ┆ u32   ┆ list[str]              │
╞═════════════╪═══════╪════════════════════════╡
│ PRJNA668104 ┆ 40    ┆ ["pig gut metagenome"] │
│ PRJNA807368 ┆ 12    ┆ ["pig gut metagenome"] │
│ PRJNA408025 ┆ 47    ┆ ["pig gut metagenome"] │
│ PRJEB31650  ┆ 287   ┆ ["pig gut metagenome"] │
│ PRJNA629856 ┆ 179   ┆ ["pig gut metagenome"] │
│ PRJNA373834 ┆ 22    ┆ ["pig gut metagenome"] │
│ PRJNA471402 ┆ 39    ┆ ["pig gut metagenome"] │
│ PRJNA526405 ┆ 3423  ┆ ["pig gut metagenome"] │
│ PRJNA741980 ┆ 14    ┆ ["pig gut metagenome"] │
└─────────────┴───────┴────────────────────────┘

In [17]:
join_df = (
    missing_sum_df.join(total_sum_df, how='inner', on='bioproject')
    .with_columns(f_missing=pl.col('n_missing') / pl.col('total'))
    .sort(by='f_missing')
)
join_df

shape: (9, 5)
┌─────────────┬───────────┬───────┬────────────────────────┬───────────┐
│ bioproject  ┆ n_missing ┆ total ┆ org                    ┆ f_missing │
│ ---         ┆ ---       ┆ ---   ┆ ---                    ┆ ---       │
│ str         ┆ u32       ┆ u32   ┆ list[str]              ┆ f64       │
╞═════════════╪═══════════╪═══════╪════════════════════════╪═══════════╡
│ PRJNA526405 ┆ 8         ┆ 3423  ┆ ["pig gut metagenome"] ┆ 0.002337  │
│ PRJNA629856 ┆ 1         ┆ 179   ┆ ["pig gut metagenome"] ┆ 0.005587  │
│ PRJNA471402 ┆ 1         ┆ 39    ┆ ["pig gut metagenome"] ┆ 0.025641  │
│ PRJEB31650  ┆ 9         ┆ 287   ┆ ["pig gut metagenome"] ┆ 0.031359  │
│ PRJNA408025 ┆ 3         ┆ 47    ┆ ["pig gut metagenome"] ┆ 0.06383   │
│ PRJNA741980 ┆ 1         ┆ 14    ┆ ["pig gut metagenome"] ┆ 0.071429  │
│ PRJNA807368 ┆ 4         ┆ 12    ┆ ["pig gut metagenome"] ┆ 0.333333  │
│ PRJNA373834 ┆ 8         ┆ 22    ┆ ["pig gut metagenome"] ┆ 0.363636  │
│ PRJNA668104 ┆ 19        ┆ 40    ┆ ["pig gut metagenome"] ┆ 0.475     │
└─────────────┴───────────┴───────┴────────────────────────┴───────────┘

In [18]:
descriptions = {}
descriptions['PRJNA668104'] = 'Fecal microbiota transplantation on necrotizing enterocolitis in preterm piglets'
descriptions['PRJNA373834'] = 'intestinal microbiome in feces from sows, five days after farrowing, their piglets during suckling and two weeks after weaning, 5-day old artificially reared and formula-fed siblings, and FP infected with Clostridium difficile.'
descriptions['PRJNA807368'] = 'This study aimed to investigate the microbial structure and function in the rectum of weaned piglets with berberine supplementation.'
descriptions['PRJEB31650'] = 'Based on 4 samples processed differently...'
descriptions['PRJNA526405'] = 'Study of pig microbiome in response to antibiotic'

## Explore PRJNA526405 (big Australian study)

TODO: add papers, link to metadata

[ENA link](https://www.ebi.ac.uk/ena/browser/view/PRJNA526405)

Study of pig microbiome in response to antibiotic. The big Aus one.

Maybe some relationship to Ja31/ prefix in sample_name?

In [19]:
(by_acc
     .join(metadata_df, left_on='match_name', right_on='acc', how='inner')
     .filter(pl.col('bioproject') == 'PRJNA526405')
     .sort('n_core')
     .select('n_core', 'sample_name')
     .filter(pl.col('sample_name').str.contains('Ja31/'))
     .filter(pl.col('n_core') < 10)
)

shape: (8, 2)
┌────────┬─────────────┐
│ n_core ┆ sample_name │
│ ---    ┆ ---         │
│ u32    ┆ str         │
╞════════╪═════════════╡
│ 7      ┆ Ja31/14276  │
│ 7      ┆ Ja31/29951  │
│ 7      ┆ Ja31/14276  │
│ 7      ┆ Ja31/29951  │
│ 7      ┆ Ja31/29951  │
│ 8      ┆ Ja31/14276  │
│ 9      ┆ Ja31/29792  │
│ 9      ┆ Ja31/29792  │
└────────┴─────────────┘

## Explore PRJEB31650 study (diff sample processing)

[ENA link](https://www.ebi.ac.uk/ena/browser/view/PRJEB31650)

Based on 4 samples processed differently (Pig feces 1 & 2 (P1 & P2) Sewage 1 & 2 (S1 & S2)), storage conditions (Time 0h, 16h, 64h Temperature (-80C, -20C, 5C, 22C)), sequencing platform (FTX=Freeze thawing, HX=Nextflex Hiseq, LTSX=Kappa Hiseq, NX1NS=Nextera Nextseq, NX2NS=Nextera Nextseq, NFNS=Nextflex Nextseq). Sample names containing HHKTMBBXX are resequenced samples. Sample names containing MC are spiked with a mock community. Sample names containing EC, ECPBS and pureMC, are negative DNA extraction controls, negative controls containing PBS and postive controls of the mock community used to spike with, respectively. The a, b and c are indicators of replicate number.

summary: all 9 are pureMC - positive controls of mock community used to spike. The other ...

pubs:

https://journals.asm.org/doi/10.1128/spectrum.00090-22

https://journals.asm.org/doi/10.1128/spectrum.01387-21

In [20]:
(by_acc
     .join(metadata_df, left_on='match_name', right_on='acc', how='inner')
     .filter(pl.col('bioproject') == 'PRJEB31650')
     .sort('n_core')
     .select('n_core', 'sample_name_sam')
     .filter(pl.col('n_core') < 10)
)

shape: (9, 2)
┌────────┬─────────────────────────────────┐
│ n_core ┆ sample_name_sam                 │
│ ---    ┆ ---                             │
│ u32    ┆ list[str]                       │
╞════════╪═════════════════════════════════╡
│ 1      ┆ ["DTU2018_MG_1516_LPSX_NX2NS_P… │
│ 1      ┆ ["DTU2018_MG_1468_LPSX_NX1NS_P… │
│ 1      ┆ ["DTU2018_MG_1515_LPSX_NX2NS_P… │
│ 1      ┆ ["DTU2018_MG_1469_LPSX_NX1NS_P… │
│ 4      ┆ ["DTU2016_MG_474_HX_P1pureMC_0… │
│ 4      ┆ ["HHKTMBBXXDTU2016_MG_474_HX_P… │
│ 5      ┆ ["DTU2018_MG_349_LPSX_KAHI_P1p… │
│ 5      ┆ ["HHKTMBBXX-replacementsDTU201… │
│ 5      ┆ ["DTU2018_MG_350_LPSX_KAHI_P1p… │
└────────┴─────────────────────────────────┘

In [21]:
(by_acc
     .join(metadata_df, left_on='match_name', right_on='acc', how='inner')
     .filter(pl.col('bioproject') == 'PRJEB31650')
     .sort('n_core')
     .select('n_core', 'sample_name_sam')
     .filter(pl.col('n_core') >= 10)
)

shape: (236, 2)
┌────────┬─────────────────────────────────┐
│ n_core ┆ sample_name_sam                 │
│ ---    ┆ ---                             │
│ u32    ┆ list[str]                       │
╞════════╪═════════════════════════════════╡
│ 14     ┆ ["DTU2018_MG_1517_LPSX_NX2NS_P… │
│ 16     ┆ ["HHKTMBBXX-replacementsDTU201… │
│ 16     ┆ ["DTU2018_MG_295_LTSX_P1_4m_80… │
│ 16     ┆ ["HHKTMBBXX-replacementsDTU201… │
│ 16     ┆ ["HHKTMBBXX-replacementsDTU201… │
│ …      ┆ …                               │
│ 17     ┆ ["HHKTMBBXX-replacementsDTU201… │
│ 17     ┆ ["HHKTMBBXX-replacementsDTU201… │
│ 17     ┆ ["DTU2016_MG_723_FTX_P1_64h_3F… │
│ 17     ┆ ["DTU2018_MG_304_LTSX_P1_8m_80… │
│ 17     ┆ ["DTU2016_MG_559_HX_P2_16h_22C… │
└────────┴─────────────────────────────────┘

In [22]:
(by_acc
     .join(metadata_df, left_on='match_name', right_on='acc', how='inner')
     .filter(pl.col('bioproject') == 'PRJEB31650')['organism'].value_counts())

shape: (1, 2)
┌────────────────────┬───────┐
│ organism           ┆ count │
│ ---                ┆ ---   │
│ str                ┆ u32   │
╞════════════════════╪═══════╡
│ pig gut metagenome ┆ 245   │
└────────────────────┴───────┘

In [23]:
(by_acc
     .join(metadata_df, left_on='match_name', right_on='acc', how='inner')
     .filter(pl.col('bioproject') == 'PRJEB31650')
     .sort('n_core')
     .select('n_core', 'sample_name_sam')
     .filter(pl.col('sample_name_sam').list.get(0).str.contains('pureMC'))
)

shape: (9, 2)
┌────────┬─────────────────────────────────┐
│ n_core ┆ sample_name_sam                 │
│ ---    ┆ ---                             │
│ u32    ┆ list[str]                       │
╞════════╪═════════════════════════════════╡
│ 1      ┆ ["DTU2018_MG_1516_LPSX_NX2NS_P… │
│ 1      ┆ ["DTU2018_MG_1468_LPSX_NX1NS_P… │
│ 1      ┆ ["DTU2018_MG_1515_LPSX_NX2NS_P… │
│ 1      ┆ ["DTU2018_MG_1469_LPSX_NX1NS_P… │
│ 4      ┆ ["DTU2016_MG_474_HX_P1pureMC_0… │
│ 4      ┆ ["HHKTMBBXXDTU2016_MG_474_HX_P… │
│ 5      ┆ ["DTU2018_MG_349_LPSX_KAHI_P1p… │
│ 5      ┆ ["HHKTMBBXX-replacementsDTU201… │
│ 5      ┆ ["DTU2018_MG_350_LPSX_KAHI_P1p… │
└────────┴─────────────────────────────────┘

In [24]:
metadata_df.filter(pl.col('bioproject') == 'PRJEB31650')['organism'].value_counts()

shape: (2, 2)
┌───────────────────────┬───────┐
│ organism              ┆ count │
│ ---                   ┆ ---   │
│ str                   ┆ u32   │
╞═══════════════════════╪═══════╡
│ pig gut metagenome    ┆ 287   │
│ wastewater metagenome ┆ 280   │
└───────────────────────┴───────┘

In [25]:
metadata_df.filter(pl.col('bioproject') == 'PRJEB31650')['sample_name_sam']

shape: (567,)
Series: 'sample_name_sam' [list[str]]
[
	["DTU2018_MG_307_LTSX_P1MC_8m_80C_b"]
	["DTU2016_MG_583_HX_P2_64h_22C_b"]
	["DTU2016_MG_478_HX_P1_16h_80C_a"]
	["HHKTMBBXX-replacementsDTU2016_MG_728_FTX_P1_88h_4FTC_20C_a"]
	["DTU2016_MG_633_HX_S1_64h_20C_c"]
	…
	["DTU2016_MG_626_HX_S1_64h_80C_b"]
	["DTU2016_MG_653_HX_S2_0h_c"]
	["DTU2016_MG_559_HX_P2_16h_22C_c"]
	["DTU2016_MG_737_FTX_S1_40h_2FTC_20C_a"]
	["HHKTMBBXXDTU2016_MG_619_HX_S1_16h_22C_b"]
]

## Explore PRJNA373834 study (Cdiff/formula)

"intestinal microbiome in feces from sows, five days after farrowing, their piglets during suckling and two weeks after weaning, 5-day old artificially reared and formula-fed siblings, and FP infected with Clostridium difficile"

summary: all of the formula fed piglets < 10 core. also two of the suckling piglets.

In [26]:
biosample_info = """\
SAMN06315441	Weaned Piglet 3
SAMN06315439	Weaned Piglet 1
SAMN06315460	Sow 4
SAMN06315449	Suckling Piglet 3
SAMN06315450	Suckling Piglet 4
SAMN06315453	Formula fed 3
SAMN06315440	Weaned Piglet 2
SAMN06315455	Formula fed cdiff 2
SAMN06315454	Formula fed cdiff 1
SAMN06315443	Weaned Piglet 5
SAMN06315452	Formula fed 2
SAMN06315446	Weaned Piglet 8
SAMN06315447	Suckling Piglet 1
SAMN06315445	Weaned Piglet 7
SAMN06315456	Formula fed cdiff 3
SAMN06315451	Formula fed 1
SAMN06315458	Sow 2
SAMN06315459	Sow 3
SAMN06315448	Suckling Piglet 2
SAMN06315444	Weaned Piglet 6
SAMN06315442	Weaned Piglet 4
SAMN06315457	Sow 1
"""

xx = []
for line in biosample_info.splitlines():
    biosample, descr = line.strip().split('	')
    is_formula=0
    if 'formula' in descr.lower():
        is_formula=1
    is_cdiff=0
    if 'cdiff' in descr.lower():
        is_cdiff= 1
    xx.append(dict(biosample=biosample, descr=descr, is_formula=is_formula, is_cdiff=is_cdiff))

biosample_df = pl.DataFrame(xx)
with pl.Config(tbl_rows=-1):
    print(biosample_df)

shape: (22, 4)
┌──────────────┬─────────────────────┬────────────┬──────────┐
│ biosample    ┆ descr               ┆ is_formula ┆ is_cdiff │
│ ---          ┆ ---                 ┆ ---        ┆ ---      │
│ str          ┆ str                 ┆ i64        ┆ i64      │
╞══════════════╪═════════════════════╪════════════╪══════════╡
│ SAMN06315441 ┆ Weaned Piglet 3     ┆ 0          ┆ 0        │
│ SAMN06315439 ┆ Weaned Piglet 1     ┆ 0          ┆ 0        │
│ SAMN06315460 ┆ Sow 4               ┆ 0          ┆ 0        │
│ SAMN06315449 ┆ Suckling Piglet 3   ┆ 0          ┆ 0        │
│ SAMN06315450 ┆ Suckling Piglet 4   ┆ 0          ┆ 0        │
│ SAMN06315453 ┆ Formula fed 3       ┆ 1          ┆ 0        │
│ SAMN06315440 ┆ Weaned Piglet 2     ┆ 0          ┆ 0        │
│ SAMN06315455 ┆ Formula fed cdiff 2 ┆ 1          ┆ 1        │
│ SAMN06315454 ┆ Formula fed cdiff 1 ┆ 1          ┆ 1        │
│ SAMN06315443 ┆ Weaned Piglet 5     ┆ 0          ┆ 0        │
│ SAMN06315452 ┆ Formula fed 2       ┆ 1          ┆ 0        │
│ SAMN06315446 ┆ Weaned Piglet 8     ┆ 0          ┆ 0        │
│ SAMN06315447 ┆ Suckling Piglet 1   ┆ 0          ┆ 0        │
│ SAMN06315445 ┆ Weaned Piglet 7     ┆ 0          ┆ 0        │
│ SAMN06315456 ┆ Formula fed cdiff 3 ┆ 1          ┆ 1        │
│ SAMN06315451 ┆ Formula fed 1       ┆ 1          ┆ 0        │
│ SAMN06315458 ┆ Sow 2               ┆ 0          ┆ 0        │
│ SAMN06315459 ┆ Sow 3               ┆ 0          ┆ 0        │
│ SAMN06315448 ┆ Suckling Piglet 2   ┆ 0          ┆ 0        │
│ SAMN06315444 ┆ Weaned Piglet 6     ┆ 0          ┆ 0        │
│ SAMN06315442 ┆ Weaned Piglet 4     ┆ 0          ┆ 0        │
│ SAMN06315457 ┆ Sow 1               ┆ 0          ┆ 0        │
└──────────────┴─────────────────────┴────────────┴──────────┘

In [27]:
with pl.Config(tbl_rows=-1):
    print(by_acc
     .join(metadata_df, left_on='match_name', right_on='acc', how='inner')
     .filter(pl.col('bioproject') == 'PRJNA373834')
     .join(biosample_df, on='biosample', how='inner')
     .select(['n_core', 'biosample', 'descr', 'is_cdiff', 'is_formula'])
     .sort('is_cdiff', 'is_formula')
    )

shape: (21, 5)
┌────────┬──────────────┬─────────────────────┬──────────┬────────────┐
│ n_core ┆ biosample    ┆ descr               ┆ is_cdiff ┆ is_formula │
│ ---    ┆ ---          ┆ ---                 ┆ ---      ┆ ---        │
│ u32    ┆ str          ┆ str                 ┆ i64      ┆ i64        │
╞════════╪══════════════╪═════════════════════╪══════════╪════════════╡
│ 17     ┆ SAMN06315459 ┆ Sow 3               ┆ 0        ┆ 0          │
│ 17     ┆ SAMN06315439 ┆ Weaned Piglet 1     ┆ 0        ┆ 0          │
│ 17     ┆ SAMN06315460 ┆ Sow 4               ┆ 0        ┆ 0          │
│ 8      ┆ SAMN06315449 ┆ Suckling Piglet 3   ┆ 0        ┆ 0          │
│ 16     ┆ SAMN06315450 ┆ Suckling Piglet 4   ┆ 0        ┆ 0          │
│ 17     ┆ SAMN06315441 ┆ Weaned Piglet 3     ┆ 0        ┆ 0          │
│ 17     ┆ SAMN06315440 ┆ Weaned Piglet 2     ┆ 0        ┆ 0          │
│ 17     ┆ SAMN06315457 ┆ Sow 1               ┆ 0        ┆ 0          │
│ 17     ┆ SAMN06315442 ┆ Weaned Piglet 4     ┆ 0        ┆ 0          │
│ 17     ┆ SAMN06315443 ┆ Weaned Piglet 5     ┆ 0        ┆ 0          │
│ 17     ┆ SAMN06315444 ┆ Weaned Piglet 6     ┆ 0        ┆ 0          │
│ 16     ┆ SAMN06315446 ┆ Weaned Piglet 8     ┆ 0        ┆ 0          │
│ 17     ┆ SAMN06315445 ┆ Weaned Piglet 7     ┆ 0        ┆ 0          │
│ 9      ┆ SAMN06315448 ┆ Suckling Piglet 2   ┆ 0        ┆ 0          │
│ 17     ┆ SAMN06315458 ┆ Sow 2               ┆ 0        ┆ 0          │
│ 6      ┆ SAMN06315453 ┆ Formula fed 3       ┆ 0        ┆ 1          │
│ 4      ┆ SAMN06315451 ┆ Formula fed 1       ┆ 0        ┆ 1          │
│ 5      ┆ SAMN06315452 ┆ Formula fed 2       ┆ 0        ┆ 1          │
│ 5      ┆ SAMN06315455 ┆ Formula fed cdiff 2 ┆ 1        ┆ 1          │
│ 5      ┆ SAMN06315456 ┆ Formula fed cdiff 3 ┆ 1        ┆ 1          │
│ 6      ┆ SAMN06315454 ┆ Formula fed cdiff 1 ┆ 1        ┆ 1          │
└────────┴──────────────┴─────────────────────┴──────────┴────────────┘

In [28]:
(low_core_acc2.filter(pl.col('bioproject') == 'PRJNA373834')
 .join(biosample_df, on='biosample', how='inner')
 .select(['n_core', 'biosample', 'descr', 'is_cdiff', 'is_formula'])
)

shape: (8, 5)
┌────────┬──────────────┬─────────────────────┬──────────┬────────────┐
│ n_core ┆ biosample    ┆ descr               ┆ is_cdiff ┆ is_formula │
│ ---    ┆ ---          ┆ ---                 ┆ ---      ┆ ---        │
│ u32    ┆ str          ┆ str                 ┆ i64      ┆ i64        │
╞════════╪══════════════╪═════════════════════╪══════════╪════════════╡
│ 8      ┆ SAMN06315449 ┆ Suckling Piglet 3   ┆ 0        ┆ 0          │
│ 6      ┆ SAMN06315453 ┆ Formula fed 3       ┆ 0        ┆ 1          │
│ 5      ┆ SAMN06315455 ┆ Formula fed cdiff 2 ┆ 1        ┆ 1          │
│ 6      ┆ SAMN06315454 ┆ Formula fed cdiff 1 ┆ 1        ┆ 1          │
│ 5      ┆ SAMN06315452 ┆ Formula fed 2       ┆ 0        ┆ 1          │
│ 5      ┆ SAMN06315456 ┆ Formula fed cdiff 3 ┆ 1        ┆ 1          │
│ 4      ┆ SAMN06315451 ┆ Formula fed 1       ┆ 0        ┆ 1          │
│ 9      ┆ SAMN06315448 ┆ Suckling Piglet 2   ┆ 0        ┆ 0          │
└────────┴──────────────┴─────────────────────┴──────────┴────────────┘

In [29]:
low_core_acc2.filter(pl.col('bioproject') == 'PRJNA373834')

shape: (8, 68)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ acc        ┆ n_core ┆ sample_nam ┆ sample_na ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_s │
│ ---        ┆ ---    ┆ e          ┆ me_sam    ┆   ┆ ---       ┆ create_da ┆ version   ┆ earch     │
│ str        ┆ u32    ┆ ---        ┆ ---       ┆   ┆ str       ┆ te        ┆ ---       ┆ ---       │
│            ┆        ┆ str        ┆ list[str] ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│            ┆        ┆            ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR5240735 ┆ 4      ┆ 2016_CRC_F ┆ []        ┆ … ┆ 192769841 ┆ "2017-02- ┆ null      ┆ "2016_CRC │
│            ┆        ┆ P1         ┆           ┆   ┆ 1         ┆ 09T10:39: ┆           ┆ _FP1"     │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR5240729 ┆ 5      ┆ 2016_CRC_F ┆ []        ┆ … ┆ 177513600 ┆ "2017-02- ┆ null      ┆ "2016_CRC │
│            ┆        ┆ P-CD3      ┆           ┆   ┆ 9         ┆ 09T10:37: ┆           ┆ _FP-CD3"  │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR5240734 ┆ 5      ┆ 2016_CRC_F ┆ []        ┆ … ┆ 187238754 ┆ "2017-02- ┆ null      ┆ "2016_CRC │
│            ┆        ┆ P2         ┆           ┆   ┆ 1         ┆ 09T10:45: ┆           ┆ _FP2"     │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR5240730 ┆ 5      ┆ 2016_CRC_F ┆ []        ┆ … ┆ 218213908 ┆ "2017-02- ┆ null      ┆ "2016_CRC │
│            ┆        ┆ P-CD2      ┆           ┆   ┆ 0         ┆ 09T10:40: ┆           ┆ _FP-CD2"  │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR5240731 ┆ 6      ┆ 2016_CRC_F ┆ []        ┆ … ┆ 206420554 ┆ "2017-02- ┆ null      ┆ "2016_CRC │
│            ┆        ┆ P-CD1      ┆           ┆   ┆ 1         ┆ 09T10:40: ┆           ┆ _FP-CD1"  │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR5240732 ┆ 6      ┆ 2016_CRC_F ┆ []        ┆ … ┆ 140259883 ┆ "2017-02- ┆ null      ┆ "2016_CRC │
│            ┆        ┆ P3         ┆           ┆   ┆ 9         ┆ 09T10:40: ┆           ┆ _FP3"     │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR5240737 ┆ 8      ┆ 2016_CRC_S ┆ []        ┆ … ┆ 213953989 ┆ "2017-02- ┆ null      ┆ "2016_CRC │
│            ┆        ┆ P3         ┆           ┆   ┆ 6         ┆ 09T10:39: ┆           ┆ _SP3"     │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR5240741 ┆ 9      ┆ 2016_CRC_S ┆ []        ┆ … ┆ 181714007 ┆ "2017-02- ┆ null      ┆ "2016_CRC │
│            ┆        ┆ P2         ┆           ┆   ┆ 3         ┆ 09T10:58: ┆           ┆ _SP2"     │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Explore PRJNA668104 (necrotizing enterocolitis study)

[ENA link](https://www.ebi.ac.uk/ena/browser/view/PRJNA668104)

publication: https://www.nature.com/articles/s41522-022-00310-2

github: https://github.com/yanhui09/FMT-donor/tree/master

metadata link: https://github.com/yanhui09/FMT-donor/blob/master/data/Metadata.tsv

In [30]:
low_core_acc2.filter(pl.col('bioproject') == 'PRJNA668104')

shape: (19, 68)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ acc        ┆ n_core ┆ sample_nam ┆ sample_na ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_s │
│ ---        ┆ ---    ┆ e          ┆ me_sam    ┆   ┆ ---       ┆ create_da ┆ version   ┆ earch     │
│ str        ┆ u32    ┆ ---        ┆ ---       ┆   ┆ str       ┆ te        ┆ ---       ┆ ---       │
│            ┆        ┆ str        ┆ list[str] ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│            ┆        ┆            ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR1279579 ┆ 1      ┆ pig_colon_ ┆ []        ┆ … ┆ 389259080 ┆ "2020-10- ┆ null      ┆ "16396817 │
│ 0          ┆        ┆ 405        ┆           ┆   ┆ 7         ┆ 08T12:38: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1279578 ┆ 1      ┆ pig_colon_ ┆ []        ┆ … ┆ 273201724 ┆ "2020-10- ┆ null      ┆ "16396804 │
│ 5          ┆        ┆ 403        ┆           ┆   ┆ 0         ┆ 08T12:38: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1279578 ┆ 2      ┆ pig_colon_ ┆ []        ┆ … ┆ 290040765 ┆ "2020-10- ┆ null      ┆ "16396824 │
│ 2          ┆        ┆ 424        ┆           ┆   ┆ 6         ┆ 08T12:24: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1279577 ┆ 2      ┆ pig_colon_ ┆ []        ┆ … ┆ 207750152 ┆ "2020-10- ┆ null      ┆ "16396805 │
│ 4          ┆        ┆ 406        ┆           ┆   ┆ 7         ┆ 08T12:22: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1279574 ┆ 2      ┆ pig_colon_ ┆ []        ┆ … ┆ 238694236 ┆ "2020-10- ┆ null      ┆ "16396841 │
│ 1          ┆        ┆ 428        ┆           ┆   ┆ 1         ┆ 08T12:26: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ …          ┆ …      ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ SRR1279577 ┆ 3      ┆ pig_colon_ ┆ []        ┆ … ┆ 233263181 ┆ "2020-10- ┆ null      ┆ "16396835 │
│ 0          ┆        ┆ 420        ┆           ┆   ┆ 6         ┆ 08T12:24: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1279577 ┆ 3      ┆ pig_colon_ ┆ []        ┆ … ┆ 241958452 ┆ "2020-10- ┆ null      ┆ "16396832 │
│ 3          ┆        ┆ 413        ┆           ┆   ┆ 4         ┆ 08T12:31: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1279574 ┆ 3      ┆ pig_colon_ ┆ []        ┆ … ┆ 265195756 ┆ "2020-10- ┆ null      ┆ "16396836 │
│ 6          ┆        ┆ 422        ┆           ┆   ┆ 5         ┆ 08T12:33: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1279577 ┆ 4      ┆ pig_colon_ ┆ []        ┆ … ┆ 231654331 ┆ "2020-10- ┆ null      ┆ "16396830 │
│ 6          ┆        ┆ 407        ┆           ┆   ┆ 1         ┆ 08T12:24: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1279577 ┆ 4      ┆ pig_colon_ ┆ []        ┆ … ┆ 239482448 ┆ "2020-10- ┆ null      ┆ "16396834 │
│ 1          ┆        ┆ 418        ┆           ┆   ┆ 0         ┆ 08T12:43: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Explore PRJNA807368 (berberine study)

[ENA link](https://www.ebi.ac.uk/ena/browser/view/PRJNA807368)

paper: https://www.frontiersin.org/journals/microbiology/articles/10.3389/fmicb.2022.862882/full

Summary of the below: of the 12 samples in the study, 4/6 of the Berberine suppl samples had < 10 core microbes, and none of the non-supplemented. All 6 berberine suppl samples had 10 core microbes or less, and only one control.

In [31]:
low_core_acc2.filter(pl.col('bioproject') == 'PRJNA807368')

shape: (4, 68)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ acc        ┆ n_core ┆ sample_nam ┆ sample_na ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_s │
│ ---        ┆ ---    ┆ e          ┆ me_sam    ┆   ┆ ---       ┆ create_da ┆ version   ┆ earch     │
│ str        ┆ u32    ┆ ---        ┆ ---       ┆   ┆ str       ┆ te        ┆ ---       ┆ ---       │
│            ┆        ┆ str        ┆ list[str] ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│            ┆        ┆            ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR1804890 ┆ 5      ┆ Berberine1 ┆ []        ┆ … ┆ 347442114 ┆ "2022-02- ┆ null      ┆ "25980738 │
│ 4          ┆        ┆            ┆           ┆   ┆ 5         ┆ 18T08:23: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1804890 ┆ 8      ┆ Berberine2 ┆ []        ┆ … ┆ 353623422 ┆ "2022-02- ┆ null      ┆ "25980739 │
│ 3          ┆        ┆            ┆           ┆   ┆ 0         ┆ 18T08:13: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1804890 ┆ 9      ┆ Berberine4 ┆ []        ┆ … ┆ 352673980 ┆ "2022-02- ┆ null      ┆ "25980741 │
│ 1          ┆        ┆            ┆           ┆   ┆ 2         ┆ 18T08:27: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1804890 ┆ 9      ┆ Berberine3 ┆ []        ┆ … ┆ 344807609 ┆ "2022-02- ┆ null      ┆ "25980740 │
│ 2          ┆        ┆            ┆           ┆   ┆ 5         ┆ 18T08:14: ┆           ┆ "         │
│            ┆        ┆            ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [32]:
with(pl.Config(tbl_rows=-10)):
    print(metadata_df.filter(pl.col('bioproject') == 'PRJNA807368')['sample_name'].sort())

shape: (12,)
Series: 'sample_name' [str]
[
	"Berberine1"
	"Berberine2"
	"Berberine3"
	"Berberine4"
	"Berberine5"
	"Berberine6"
	"Control1"
	"Control2"
	"Control3"
	"Control4"
	"Control5"
	"Control6"
]

In [33]:
low_core_acc

shape: (54, 2)
┌─────────────┬────────┐
│ acc         ┆ n_core │
│ ---         ┆ ---    │
│ str         ┆ u32    │
╞═════════════╪════════╡
│ SRR12795790 ┆ 1      │
│ SRR12795785 ┆ 1      │
│ ERR3212036  ┆ 1      │
│ ERR3212024  ┆ 1      │
│ ERR3212025  ┆ 1      │
│ …           ┆ …      │
│ SRR18048901 ┆ 9      │
│ SRR5240741  ┆ 9      │
│ SRR11183533 ┆ 9      │
│ SRR11125388 ┆ 9      │
│ SRR18048902 ┆ 9      │
└─────────────┴────────┘

In [34]:
with pl.Config(tbl_rows=-1):
    print(by_acc
     .join(metadata_df, left_on='match_name', right_on='acc', how='inner')
     .filter(pl.col('bioproject') == 'PRJNA807368')
     .select(['n_core', 'sample_name'])
     .sort('n_core')
    )

shape: (12, 2)
┌────────┬─────────────┐
│ n_core ┆ sample_name │
│ ---    ┆ ---         │
│ u32    ┆ str         │
╞════════╪═════════════╡
│ 5      ┆ Berberine1  │
│ 8      ┆ Berberine2  │
│ 9      ┆ Berberine4  │
│ 9      ┆ Berberine3  │
│ 10     ┆ Control3    │
│ 10     ┆ Berberine5  │
│ 10     ┆ Berberine6  │
│ 11     ┆ Control2    │
│ 13     ┆ Control5    │
│ 14     ┆ Control1    │
│ 14     ┆ Control4    │
│ 17     ┆ Control6    │
└────────┴─────────────┘