# Explore the metagenome accessions missing some or all of the core microbes

In [1]:
import polars as pl
from io import StringIO

In [2]:
CORE_NAMES = [ x.strip() for x in open('../inputs.branchwater/names.list') ]

## Load in the metadata

In [3]:
metadata_df = (
    pl.scan_parquet("/group/ctbrowngrp5/sra-metagenomes/20241128-metadata.parquet")
    .filter(pl.col("acc") != "NP")
    .filter(pl.col("assay_type") == "WGS")
    .collect()
)
metadata_df.head(1)

shape: (1, 67)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_na ┆ sample_na ┆ acc       ┆ assay_typ ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_ │
│ me        ┆ me_sam    ┆ ---       ┆ e         ┆   ┆ ---       ┆ create_da ┆ version   ┆ search   │
│ ---       ┆ ---       ┆ str       ┆ ---       ┆   ┆ str       ┆ te        ┆ ---       ┆ ---      │
│ str       ┆ list[str] ┆           ┆ str       ┆   ┆           ┆ ---       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 27        ┆ []        ┆ SRR285238 ┆ WGS       ┆ … ┆ 232696690 ┆ "2024-04- ┆ null      ┆ "1095378 │
│           ┆           ┆ 69        ┆           ┆   ┆           ┆ 02T09:18: ┆           ┆ "        │
│           ┆           ┆           ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Load the manysearch results and filter at our default threshold of 20

In [4]:
df = (
    pl.scan_parquet('../outputs.cds3/pq/mag+gtdb.cds3.x.3216.manysearch.parquet')
    .filter(pl.col('intersect_hashes') >= 20)
    .with_columns(
        species_name=pl.col('query_name').str.split(' ').list.slice(1, 2).list.join( " "),
        acc=pl.col('match_name'),
    )
).collect()

In [5]:
df.head(1)

shape: (1, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ n_weighte ┆ total_wei ┆ species_n ┆ acc      │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ d_found   ┆ ghted_has ┆ ame       ┆ ---      │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ hes       ┆ ---       ┆ str      │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ i64       ┆ ---       ┆ str       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ i64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ GCA_96360 ┆ 98787da90 ┆ SRR111833 ┆ 0.18467   ┆ … ┆ 4656      ┆ 1066419   ┆ s__Methan ┆ SRR11183 │
│ 6895 s__M ┆ 33ca08f4a ┆ 30        ┆           ┆   ┆           ┆           ┆ ocatella  ┆ 330      │
│ ethanocat ┆ 8e0e553cd ┆           ┆           ┆   ┆           ┆           ┆ smithii   ┆          │
│ ell…      ┆ 3be…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
# Do some nice reporting out of samples belong to a particular bioproject

class ReportOnBioProject:
    def __init__(self, *, manysearch_df, metadata_df, species_set, CUTOFF=9):
        all_acc = set(manysearch_df['acc'])
        assert len(all_acc) == 3216
        manysearch_df = manysearch_df.filter(pl.col('species_name').is_in(species_set))

        self.species_set = species_set
        self.manysearch_df = manysearch_df
        self.metadata_df = metadata_df

        by_acc = manysearch_df.group_by('acc').agg(
            n_core=pl.len(),
        )

        # how many in each bioproject are below cutoff?
        self.low_count_df = (
            by_acc
            .filter(pl.col('n_core') <= CUTOFF)
            .join(metadata_df, on='acc', how='inner')
            .group_by('bioproject').agg(n_low=pl.len())
        )
        # how many were searched in the 3216?
        self.manysearch_count_df = (
            metadata_df.filter(pl.col('acc').is_in(all_acc))
            .group_by('bioproject').agg(n_3216=pl.len())
        )
        # how many were in the SRA to begin with?
        self.sra_count_df = (
            metadata_df.group_by('bioproject').agg(n_sra=pl.len())
        )

    def report(self, *bioprojects, sort='n_low'):
        xx_df = (
            self.low_count_df
            .join(self.manysearch_count_df, on='bioproject', how='inner')
            .join(self.sra_count_df, on='bioproject', how='inner')
        )
        
        print(xx_df.filter(pl.col('bioproject').is_in(set(list(bioprojects)))).sort(sort))

reporter = ReportOnBioProject(manysearch_df=df, metadata_df=metadata_df, species_set=CORE_NAMES)
reporter.report('PRJNA668104')

shape: (1, 4)
┌─────────────┬───────┬────────┬───────┐
│ bioproject  ┆ n_low ┆ n_3216 ┆ n_sra │
│ ---         ┆ ---   ┆ ---    ┆ ---   │
│ str         ┆ u32   ┆ u32    ┆ u32   │
╞═════════════╪═══════╪════════╪═══════╡
│ PRJNA668104 ┆ 17    ┆ 21     ┆ 40    │
└─────────────┴───────┴────────┴───────┘

## Summarize by species to get core

In [7]:
n_acc = df['match_name'].n_unique()
by_species = df.group_by('query_name').agg(
    freq=pl.len() / n_acc
)

In [8]:
with pl.Config(tbl_rows=-1):
    print(by_species.sort('freq', descending=True).filter(pl.col('freq') >= 0.95))

shape: (17, 2)
┌─────────────────────────────────┬──────────┐
│ query_name                      ┆ freq     │
│ ---                             ┆ ---      │
│ str                             ┆ f64      │
╞═════════════════════════════════╪══════════╡
│ GCF_001256715 s__Escherichia c… ┆ 0.992537 │
│ GCA_945834365 s__Sodaliphilus … ┆ 0.990983 │
│ GCF_028308525 s__Lactobacillus… ┆ 0.990361 │
│ GCA_946007015 s__UBA2868 sp004… ┆ 0.979167 │
│ GCA_927798655 s__Cryptobactero… ┆ 0.978545 │
│ GCA_034171835 s__Mogibacterium… ┆ 0.977301 │
│ GCA_945872445 s__JAFBIX01 sp02… ┆ 0.974502 │
│ GCA_946408405 s__Fimisoma sp00… ┆ 0.973259 │
│ GCA_945501735 s__Prevotella sp… ┆ 0.968595 │
│ GCA_945876695 s__Floccifex por… ┆ 0.968284 │
│ GCA_004561115 s__Cryptobactero… ┆ 0.968284 │
│ GCA_945877245 s__Bariatricus s… ┆ 0.966418 │
│ GCA_022781365 s__Colivicinus s… ┆ 0.958333 │
│ GCA_945932635 s__Cryptobactero… ┆ 0.956468 │
│ GCA_945938975 s__Ornithospiroc… ┆ 0.955224 │
│ GCA_934726065 s__Cryptobactero… ┆ 0.952425 │
│ GCA_028727695 s__Prevotella sp… ┆ 0.95056  │
└─────────────────────────────────┴──────────┘

In [9]:
CORE_NAMES = set(by_species.sort('freq', descending=True).filter(pl.col('freq') >= 0.95)['query_name'])
assert len(CORE_NAMES) == 17
print(CORE_NAMES)

{'GCA_022781365 s__Colivicinus sp002299675 singlehash', 'GCA_946007015 s__UBA2868 sp004552595 singlehash', 'GCA_934726065 s__Cryptobacteroides sp000432655 singlehash', 'GCA_945872445 s__JAFBIX01 sp021531895 singlehash', 'GCA_034171835 s__Mogibacterium_A kristiansenii singlehash', 'GCA_927798655 s__Cryptobacteroides sp900546925 singlehash', 'GCA_946408405 s__Fimisoma sp002320005 singlehash', 'GCF_028308525 s__Lactobacillus amylovorus singlehash', 'GCA_004561115 s__Cryptobacteroides sp034089285 singlehash', 'GCA_945877245 s__Bariatricus sp004560705 singlehash', 'GCA_945938975 s__Ornithospirochaeta sp022785155 singlehash', 'GCA_028727695 s__Prevotella sp000434975 singlehash', 'GCA_945876695 s__Floccifex porci singlehash', 'GCA_945932635 s__Cryptobacteroides sp000434935 singlehash', 'GCA_945501735 s__Prevotella sp002251295 singlehash', 'GCF_001256715 s__Escherichia coli singlehash', 'GCA_945834365 s__Sodaliphilus sp004557565 singlehash'}

## Ask questions about core species by metagenome

In [10]:
by_acc = (
    df
    .filter(pl.col('query_name').is_in(CORE_NAMES))
    .join(metadata_df, left_on='match_name', right_on='acc')
    .group_by('match_name').agg(
        bioproject=pl.col('bioproject').unique().get(0),
        n_core=pl.len(),
    )
).sort('n_core')
by_acc.head(1)

shape: (1, 3)
┌────────────┬────────────┬────────┐
│ match_name ┆ bioproject ┆ n_core │
│ ---        ┆ ---        ┆ ---    │
│ str        ┆ str        ┆ u32    │
╞════════════╪════════════╪════════╡
│ ERR3212024 ┆ PRJEB31650 ┆ 1      │
└────────────┴────────────┴────────┘

In [11]:
assert by_acc['match_name'].n_unique() == 3216 # we found at least _one_ matches in all 3216 metagenomes

In [12]:
by_acc

shape: (3_216, 3)
┌─────────────┬─────────────┬────────┐
│ match_name  ┆ bioproject  ┆ n_core │
│ ---         ┆ ---         ┆ ---    │
│ str         ┆ str         ┆ u32    │
╞═════════════╪═════════════╪════════╡
│ ERR3212024  ┆ PRJEB31650  ┆ 1      │
│ SRR12795785 ┆ PRJNA668104 ┆ 1      │
│ ERR3212036  ┆ PRJEB31650  ┆ 1      │
│ ERR3212035  ┆ PRJEB31650  ┆ 1      │
│ SRR12795790 ┆ PRJNA668104 ┆ 1      │
│ …           ┆ …           ┆ …      │
│ SRR16235699 ┆ PRJNA769425 ┆ 17     │
│ SRR8960102  ┆ PRJNA526405 ┆ 17     │
│ ERR1135309  ┆ PRJEB11755  ┆ 17     │
│ SRR7182031  ┆ PRJNA471402 ┆ 17     │
│ SRR8960458  ┆ PRJNA526405 ┆ 17     │
└─────────────┴─────────────┴────────┘

## Join in the metadata

In [13]:
by_acc2 = by_acc.join(metadata_df, left_on='match_name', right_on='acc', how='inner', coalesce=True)
by_acc2.head(1)

shape: (1, 69)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ match_name ┆ bioproject ┆ n_core ┆ sample_na ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_s │
│ ---        ┆ ---        ┆ ---    ┆ me        ┆   ┆ ---       ┆ create_da ┆ version   ┆ earch     │
│ str        ┆ str        ┆ u32    ┆ ---       ┆   ┆ str       ┆ te        ┆ ---       ┆ ---       │
│            ┆            ┆        ┆ str       ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│            ┆            ┆        ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR1112548 ┆ PRJNA52640 ┆ 17     ┆ Fe24/1420 ┆ … ┆ 416591685 ┆ "2020-02- ┆ null      ┆ "11098298 │
│ 6          ┆ 5          ┆        ┆ 8         ┆   ┆           ┆ 20T21:25: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Do we see any strong patterns in which species is most often missing? No.

In [14]:
by_acc_16 = by_acc.filter(pl.col('n_core') == 16)
with pl.Config(tbl_rows=-1):
    print(df
 .filter(pl.col('query_name').is_in(CORE_NAMES))
 ['query_name'].value_counts().sort('count')
)
print(df['match_name'].n_unique())

shape: (17, 2)
┌─────────────────────────────────┬───────┐
│ query_name                      ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ GCA_028727695 s__Prevotella sp… ┆ 3057  │
│ GCA_934726065 s__Cryptobactero… ┆ 3063  │
│ GCA_945938975 s__Ornithospiroc… ┆ 3072  │
│ GCA_945932635 s__Cryptobactero… ┆ 3076  │
│ GCA_022781365 s__Colivicinus s… ┆ 3082  │
│ GCA_945877245 s__Bariatricus s… ┆ 3108  │
│ GCA_004561115 s__Cryptobactero… ┆ 3114  │
│ GCA_945876695 s__Floccifex por… ┆ 3114  │
│ GCA_945501735 s__Prevotella sp… ┆ 3115  │
│ GCA_946408405 s__Fimisoma sp00… ┆ 3130  │
│ GCA_945872445 s__JAFBIX01 sp02… ┆ 3134  │
│ GCA_034171835 s__Mogibacterium… ┆ 3143  │
│ GCA_927798655 s__Cryptobactero… ┆ 3147  │
│ GCA_946007015 s__UBA2868 sp004… ┆ 3149  │
│ GCF_028308525 s__Lactobacillus… ┆ 3185  │
│ GCA_945834365 s__Sodaliphilus … ┆ 3187  │
│ GCF_001256715 s__Escherichia c… ┆ 3192  │
└─────────────────────────────────┴───────┘
3216

## What's our distribution of numbers of core microbes present in metagenomes?

tl;dr relatively few metagenomes have few core microbes

In [15]:
with pl.Config(tbl_rows=-1):
    print(by_acc['n_core'].value_counts())

print(len(by_acc.filter(pl.col('n_core') < 17)))

shape: (17, 2)
┌────────┬───────┐
│ n_core ┆ count │
│ ---    ┆ ---   │
│ u32    ┆ u32   │
╞════════╪═══════╡
│ 1      ┆ 6     │
│ 2      ┆ 12    │
│ 3      ┆ 3     │
│ 4      ┆ 5     │
│ 5      ┆ 8     │
│ 6      ┆ 3     │
│ 7      ┆ 7     │
│ 8      ┆ 5     │
│ 9      ┆ 5     │
│ 10     ┆ 9     │
│ 11     ┆ 10    │
│ 12     ┆ 15    │
│ 13     ┆ 32    │
│ 14     ┆ 38    │
│ 15     ┆ 109   │
│ 16     ┆ 279   │
│ 17     ┆ 2670  │
└────────┴───────┘
546

## Let's pick 10 as an arbitrary cutoff to investigate

We could also use 8 (per branchwater combinations) or go up to ~11 or 12?

In [16]:
low_core_acc = by_acc.filter(pl.col('n_core') < 10)
len(low_core_acc)
low_core_acc.head(1)

shape: (1, 3)
┌────────────┬────────────┬────────┐
│ match_name ┆ bioproject ┆ n_core │
│ ---        ┆ ---        ┆ ---    │
│ str        ┆ str        ┆ u32    │
╞════════════╪════════════╪════════╡
│ ERR3212024 ┆ PRJEB31650 ┆ 1      │
└────────────┴────────────┴────────┘

In [17]:
low_core_acc = low_core_acc.rename({'match_name': 'acc'})

In [18]:
low_core_acc2 = low_core_acc.join(metadata_df, on='acc', how='left')
low_core_acc2

shape: (54, 69)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ acc        ┆ bioproject ┆ n_core ┆ sample_na ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_s │
│ ---        ┆ ---        ┆ ---    ┆ me        ┆   ┆ ---       ┆ create_da ┆ version   ┆ earch     │
│ str        ┆ str        ┆ u32    ┆ ---       ┆   ┆ str       ┆ te        ┆ ---       ┆ ---       │
│            ┆            ┆        ┆ str       ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│            ┆            ┆        ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ ERR3212024 ┆ PRJEB31650 ┆ 1      ┆ SAMEA5414 ┆ … ┆ 835005957 ┆ "2021-11- ┆ null      ┆ "11156626 │
│            ┆            ┆        ┆ 670       ┆   ┆           ┆ 04T09:07: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1279578 ┆ PRJNA66810 ┆ 1      ┆ pig_colon ┆ … ┆ 273201724 ┆ "2020-10- ┆ null      ┆ "16396804 │
│ 5          ┆ 4          ┆        ┆ _403      ┆   ┆ 0         ┆ 08T12:38: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ ERR3212036 ┆ PRJEB31650 ┆ 1      ┆ SAMEA5414 ┆ … ┆ 704684139 ┆ "2021-11- ┆ null      ┆ "11156638 │
│            ┆            ┆        ┆ 682       ┆   ┆           ┆ 04T10:00: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ ERR3212035 ┆ PRJEB31650 ┆ 1      ┆ SAMEA5414 ┆ … ┆ 777096014 ┆ "2021-11- ┆ null      ┆ "11156637 │
│            ┆            ┆        ┆ 681       ┆   ┆           ┆ 04T08:46: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1279579 ┆ PRJNA66810 ┆ 1      ┆ pig_colon ┆ … ┆ 389259080 ┆ "2020-10- ┆ null      ┆ "16396817 │
│ 0          ┆ 4          ┆        ┆ _405      ┆   ┆ 7         ┆ 08T12:38: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ …          ┆ …          ┆ …      ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ SRR1804890 ┆ PRJNA80736 ┆ 9      ┆ Berberine ┆ … ┆ 344807609 ┆ "2022-02- ┆ null      ┆ "25980740 │
│ 2          ┆ 8          ┆        ┆ 3         ┆   ┆ 5         ┆ 18T08:14: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR5240741 ┆ PRJNA37383 ┆ 9      ┆ 2016_CRC_ ┆ … ┆ 181714007 ┆ "2017-02- ┆ null      ┆ "2016_CRC │
│            ┆ 4          ┆        ┆ SP2       ┆   ┆ 3         ┆ 09T10:58: ┆           ┆ _SP2"     │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1804890 ┆ PRJNA80736 ┆ 9      ┆ Berberine ┆ … ┆ 352673980 ┆ "2022-02- ┆ null      ┆ "25980741 │
│ 1          ┆ 8          ┆        ┆ 4         ┆   ┆ 2         ┆ 18T08:27: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1112538 ┆ PRJNA52640 ┆ 9      ┆ Ja31/2979 ┆ … ┆ 306296301 ┆ "2020-02- ┆ null      ┆ "11097709 │
│ 8          ┆ 5          ┆        ┆ 2         ┆   ┆           ┆ 20T21:13: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1118353 ┆ PRJNA52640 ┆ 9      ┆ Ja31/2979 ┆ … ┆ 332399481 ┆ "2020-02- ┆ null      ┆ "11097709 │
│ 3          ┆ 5          ┆        ┆ 2         ┆   ┆           ┆ 26T03:24: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [19]:
# write out to a CSV for follow-on manual curation
blank_man_cur1 = low_core_acc2.select(
    ['acc', 'n_core', 'bioproject', 'organism']
).with_columns(
    broad_cat=pl.lit('pig'),  # all of these are _labelled_ as pig
    labelled_as_pig=pl.lit(1),
    is_actually_pig=pl.lit(None),
    is_pig_and_atypical=pl.lit(None),
    summary=pl.lit(None),
    description=pl.lit(None)
)
#blank_man_cur1.write_csv('../BLANK-curated-low-n_core.csv')

## Summarize by bioproject

In [44]:
reporter.report(*low_core_acc['bioproject'], sort='n_low')

shape: (9, 4)
┌─────────────┬───────┬────────┬───────┐
│ bioproject  ┆ n_low ┆ n_3216 ┆ n_sra │
│ ---         ┆ ---   ┆ ---    ┆ ---   │
│ str         ┆ u32   ┆ u32    ┆ u32   │
╞═════════════╪═══════╪════════╪═══════╡
│ PRJNA471402 ┆ 1     ┆ 36     ┆ 39    │
│ PRJNA629856 ┆ 1     ┆ 58     ┆ 179   │
│ PRJNA741980 ┆ 1     ┆ 14     ┆ 14    │
│ PRJNA408025 ┆ 3     ┆ 26     ┆ 47    │
│ PRJEB31650  ┆ 5     ┆ 245    ┆ 567   │
│ PRJNA807368 ┆ 7     ┆ 12     ┆ 12    │
│ PRJNA373834 ┆ 8     ┆ 21     ┆ 22    │
│ PRJNA526405 ┆ 14    ┆ 2103   ┆ 3598  │
│ PRJNA668104 ┆ 17    ┆ 21     ┆ 40    │
└─────────────┴───────┴────────┴───────┘

## 9 bioprojects are responsible for the 54 samples with 9 or fewer core species

In [25]:
descriptions = {}
descriptions['PRJNA668104'] = 'Fecal microbiota transplantation on necrotizing enterocolitis in preterm piglets'
descriptions['PRJNA526405'] = 'Study of pig microbiome in response to antibiotic'
descriptions['PRJNA373834'] = 'intestinal microbiome in feces from sows, five days after farrowing, their piglets during suckling and two weeks after weaning, 5-day old artificially reared and formula-fed siblings, and FP infected with Clostridium difficile.'
descriptions['PRJNA807368'] = 'This study aimed to investigate the microbial structure and function in the rectum of weaned piglets with berberine supplementation.'
descriptions['PRJEB31650'] = 'Based on 4 samples processed differently...'
descriptions['PRJNA408025'] = 'effects of LDA exposure'
descriptions['PRJNA741980'] = 'phage-encoded AMR'
descriptions['PRJNA629856'] = 'The effect of weaning age on the piglet gut microbiome was evaluated by collecting fecal swabs from piglets and sows.'
descriptions['PRJNA471402'] = 'antibiotic feed additive (oxytetracycline)'

## Explore PRJNA471402 - antibiotic feed additive (oxytetracycline)

no obvious paper

In [61]:
reporter.report('PRJNA471402')

shape: (1, 4)
┌─────────────┬───────┬────────┬───────┐
│ bioproject  ┆ n_low ┆ n_3216 ┆ n_sra │
│ ---         ┆ ---   ┆ ---    ┆ ---   │
│ str         ┆ u32   ┆ u32    ┆ u32   │
╞═════════════╪═══════╪════════╪═══════╡
│ PRJNA471402 ┆ 1     ┆ 36     ┆ 39    │
└─────────────┴───────┴────────┴───────┘

In [62]:
low_core_acc2.filter(pl.col('bioproject') == 'PRJNA471402')

shape: (1, 69)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ acc        ┆ bioproject ┆ n_core ┆ sample_na ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_s │
│ ---        ┆ ---        ┆ ---    ┆ me        ┆   ┆ ---       ┆ create_da ┆ version   ┆ earch     │
│ str        ┆ str        ┆ u32    ┆ ---       ┆   ┆ str       ┆ te        ┆ ---       ┆ ---       │
│            ┆            ┆        ┆ str       ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│            ┆            ┆        ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR7182060 ┆ PRJNA47140 ┆ 5      ┆ NGS_B.T6. ┆ … ┆ 695415979 ┆ "2018-05- ┆ null      ┆ "471402"  │
│            ┆ 2          ┆        ┆ d0.433673 ┆   ┆           ┆ 18T03:50: ┆           ┆           │
│            ┆            ┆        ┆ 28        ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Explore PRJNA408025 - effects of LDA exposure

note, 47 in SRA, only 26 in 3216.

nothing stands out. no obvious paper, either??

In [59]:
reporter.report('PRJNA408025')

shape: (1, 4)
┌─────────────┬───────┬────────┬───────┐
│ bioproject  ┆ n_low ┆ n_3216 ┆ n_sra │
│ ---         ┆ ---   ┆ ---    ┆ ---   │
│ str         ┆ u32   ┆ u32    ┆ u32   │
╞═════════════╪═══════╪════════╪═══════╡
│ PRJNA408025 ┆ 3     ┆ 26     ┆ 47    │
└─────────────┴───────┴────────┴───────┘

In [60]:
low_core_acc2.filter(pl.col('bioproject') == 'PRJNA408025')

shape: (3, 69)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ acc        ┆ bioproject ┆ n_core ┆ sample_na ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_s │
│ ---        ┆ ---        ┆ ---    ┆ me        ┆   ┆ ---       ┆ create_da ┆ version   ┆ earch     │
│ str        ┆ str        ┆ u32    ┆ ---       ┆   ┆ str       ┆ te        ┆ ---       ┆ ---       │
│            ┆            ┆        ┆ str       ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│            ┆            ┆        ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR1148976 ┆ PRJNA40802 ┆ 7      ┆ I-CON4    ┆ … ┆ 579870887 ┆ "2020-04- ┆ null      ┆ "14543241 │
│ 5          ┆ 5          ┆        ┆           ┆   ┆ 5         ┆ 07T17:52: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1148977 ┆ PRJNA40802 ┆ 8      ┆ I-CON10   ┆ … ┆ 539516914 ┆ "2020-04- ┆ null      ┆ "14543232 │
│ 5          ┆ 5          ┆        ┆           ┆   ┆ 1         ┆ 07T15:45: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1148975 ┆ PRJNA40802 ┆ 8      ┆ I-LDA9    ┆ … ┆ 571379595 ┆ "2020-04- ┆ null      ┆ "14543254 │
│ 1          ┆ 5          ┆        ┆           ┆   ┆ 8         ┆ 07T15:18: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Explore PRJNA741980 - phage-encoded AMR

https://europepmc.org/article/PMC/PMC9723715

nothing stands out - it's just pig 7, looks like?

In [49]:
reporter.report('PRJNA741980')

shape: (1, 4)
┌─────────────┬───────┬────────┬───────┐
│ bioproject  ┆ n_low ┆ n_3216 ┆ n_sra │
│ ---         ┆ ---   ┆ ---    ┆ ---   │
│ str         ┆ u32   ┆ u32    ┆ u32   │
╞═════════════╪═══════╪════════╪═══════╡
│ PRJNA741980 ┆ 1     ┆ 14     ┆ 14    │
└─────────────┴───────┴────────┴───────┘

In [51]:
low_core_acc2.filter(pl.col('bioproject') == 'PRJNA741980')

shape: (1, 69)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ acc        ┆ bioproject ┆ n_core ┆ sample_na ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_s │
│ ---        ┆ ---        ┆ ---    ┆ me        ┆   ┆ ---       ┆ create_da ┆ version   ┆ earch     │
│ str        ┆ str        ┆ u32    ┆ ---       ┆   ┆ str       ┆ te        ┆ ---       ┆ ---       │
│            ┆            ┆        ┆ str       ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│            ┆            ┆        ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR1505792 ┆ PRJNA74198 ┆ 6      ┆ P7_R1_R2  ┆ … ┆ 261032130 ┆ "2021-07- ┆ null      ┆ "20056604 │
│ 3          ┆ 0          ┆        ┆           ┆   ┆ 8         ┆ 07T05:27: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [57]:
with pl.Config(tbl_rows=-1):
    print(metadata_df.filter(pl.col('bioproject') == 'PRJNA741980')['sample_name'].sort())

shape: (14,)
Series: 'sample_name' [str]
[
	"P11_R1_R2"
	"P12_R1_R2"
	"P13_R1_R2"
	"P15_R1_R2"
	"P16_R1_R2"
	"P17_R1_R2"
	"P2_R1_R2"
	"P3_R1_R2"
	"P4_R1_R2"
	"P5_R1_R2"
	"P6_R1_R2"
	"P7_R1_R2"
	"P8_R1_R2"
	"P9_R1_R2"
]

## Explore PRJNA629856 - weaning age, 1 sample

https://pmc.ncbi.nlm.nih.gov/articles/PMC8609972/

thoughts:
* not clear how to decode sample names.
* lots that didn't make it into the 3216...

In [48]:
reporter.report('PRJNA629856')

shape: (1, 4)
┌─────────────┬───────┬────────┬───────┐
│ bioproject  ┆ n_low ┆ n_3216 ┆ n_sra │
│ ---         ┆ ---   ┆ ---    ┆ ---   │
│ str         ┆ u32   ┆ u32    ┆ u32   │
╞═════════════╪═══════╪════════╪═══════╡
│ PRJNA629856 ┆ 1     ┆ 58     ┆ 179   │
└─────────────┴───────┴────────┴───────┘

In [47]:
low_core_acc2.filter(pl.col('bioproject') == 'PRJNA629856')

shape: (1, 69)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ acc        ┆ bioproject ┆ n_core ┆ sample_na ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_s │
│ ---        ┆ ---        ┆ ---    ┆ me        ┆   ┆ ---       ┆ create_da ┆ version   ┆ earch     │
│ str        ┆ str        ┆ u32    ┆ ---       ┆   ┆ str       ┆ te        ┆ ---       ┆ ---       │
│            ┆            ┆        ┆ str       ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│            ┆            ┆        ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR1436922 ┆ PRJNA62985 ┆ 7      ┆ H1P910W28 ┆ … ┆ 273892754 ┆ "2021-04- ┆ null      ┆ "17899767 │
│ 6          ┆ 6          ┆        ┆ FD007     ┆   ┆ 4         ┆ 30T13:57: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Explore PRJNA526405 (big Australian study)

TODO: add papers, link to metadata

[ENA link](https://www.ebi.ac.uk/ena/browser/view/PRJNA526405)

Study of pig microbiome in response to antibiotic. The big Aus one.

Maybe some relationship to Ja31/ prefix in sample_name?

In [26]:
(by_acc
     .join(metadata_df, left_on='match_name', right_on='acc', how='inner')
     .filter(pl.col('bioproject') == 'PRJNA526405')
     .sort('n_core')
     .select('n_core', 'sample_name')
     .filter(pl.col('sample_name').str.contains('Ja31/'))
     .filter(pl.col('n_core') < 10)
)

shape: (8, 2)
┌────────┬─────────────┐
│ n_core ┆ sample_name │
│ ---    ┆ ---         │
│ u32    ┆ str         │
╞════════╪═════════════╡
│ 7      ┆ Ja31/14276  │
│ 7      ┆ Ja31/29951  │
│ 7      ┆ Ja31/14276  │
│ 7      ┆ Ja31/29951  │
│ 7      ┆ Ja31/29951  │
│ 8      ┆ Ja31/14276  │
│ 9      ┆ Ja31/29792  │
│ 9      ┆ Ja31/29792  │
└────────┴─────────────┘

## Explore PRJEB31650 study (diff sample processing)

[ENA link](https://www.ebi.ac.uk/ena/browser/view/PRJEB31650)

Based on 4 samples processed differently (Pig feces 1 & 2 (P1 & P2) Sewage 1 & 2 (S1 & S2)), storage conditions (Time 0h, 16h, 64h Temperature (-80C, -20C, 5C, 22C)), sequencing platform (FTX=Freeze thawing, HX=Nextflex Hiseq, LTSX=Kappa Hiseq, NX1NS=Nextera Nextseq, NX2NS=Nextera Nextseq, NFNS=Nextflex Nextseq). Sample names containing HHKTMBBXX are resequenced samples. Sample names containing MC are spiked with a mock community. Sample names containing EC, ECPBS and pureMC, are negative DNA extraction controls, negative controls containing PBS and postive controls of the mock community used to spike with, respectively. The a, b and c are indicators of replicate number.

summary: all 9 are pureMC - positive controls of mock community used to spike. 

Composition: "synthetic mock community composed of eight microorganisms that included two eukaryotes (Propionibacterium freudenreichii, Bacteroides fragilis, Staphylococcus aureus, Fusobacterium nucleatum, Escherichia coli, Salmonella enterica serovar Typhimurium, Cryptosporidium parvum, and Saccharomyces cerevisiae), respectively."

Note: we do see a great deal of E. coli! But we also see low intersection amounts of a few others, what's up with that??

TODO: examine overlaps with other expected organisms. Note that there are only a few intersect hashes but HIGH DEPTH.

pubs:

https://journals.asm.org/doi/10.1128/spectrum.00090-22

https://journals.asm.org/doi/10.1128/spectrum.01387-21

In [27]:
(by_acc
     .join(metadata_df, left_on='match_name', right_on='acc', how='inner')
     .filter(pl.col('bioproject') == 'PRJEB31650')
     .sort('n_core')
     .select('n_core', 'sample_name_sam')
     .filter(pl.col('n_core') < 10)
)

shape: (9, 2)
┌────────┬─────────────────────────────────┐
│ n_core ┆ sample_name_sam                 │
│ ---    ┆ ---                             │
│ u32    ┆ list[str]                       │
╞════════╪═════════════════════════════════╡
│ 1      ┆ ["DTU2018_MG_1516_LPSX_NX2NS_P… │
│ 1      ┆ ["DTU2018_MG_1468_LPSX_NX1NS_P… │
│ 1      ┆ ["DTU2018_MG_1515_LPSX_NX2NS_P… │
│ 1      ┆ ["DTU2018_MG_1469_LPSX_NX1NS_P… │
│ 4      ┆ ["DTU2016_MG_474_HX_P1pureMC_0… │
│ 4      ┆ ["HHKTMBBXXDTU2016_MG_474_HX_P… │
│ 5      ┆ ["DTU2018_MG_349_LPSX_KAHI_P1p… │
│ 5      ┆ ["HHKTMBBXX-replacementsDTU201… │
│ 5      ┆ ["DTU2018_MG_350_LPSX_KAHI_P1p… │
└────────┴─────────────────────────────────┘

In [28]:
# which species _were_ found in these?!
this_df = df.join(
    # get those in low_core, from the relevant bioproject
    (low_core_acc
     .join(metadata_df, on='acc', how='inner')
     .filter(pl.col('bioproject') == 'PRJEB31650')
    ),
    left_on='match_name', right_on='acc',
    how='semi'
).filter(pl.col('query_name').is_in(CORE_NAMES))

with pl.Config(tbl_rows=-1):
    print(this_df.sort('intersect_hashes'))

shape: (27, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ n_weighte ┆ total_wei ┆ species_n ┆ acc      │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ d_found   ┆ ghted_has ┆ ame       ┆ ---      │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ hes       ┆ ---       ┆ str      │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ i64       ┆ ---       ┆ str       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ i64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ GCA_02872 ┆ 5f3ec5317 ┆ ERR321174 ┆ 0.00288   ┆ … ┆ 23        ┆ 915385    ┆ s__Prevot ┆ ERR32117 │
│ 7695 s__P ┆ 3d835a3cb ┆ 7         ┆           ┆   ┆           ┆           ┆ ella sp00 ┆ 47       │
│ revotella ┆ 129557502 ┆           ┆           ┆   ┆           ┆           ┆ 0434975   ┆          │
│ sp…       ┆ 962…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_92779 ┆ bcb17cf3e ┆ ERR321199 ┆ 0.00365   ┆ … ┆ 26        ┆ 3075473   ┆ s__Crypto ┆ ERR32119 │
│ 8655 s__C ┆ 5825e4662 ┆ 0         ┆           ┆   ┆           ┆           ┆ bacteroid ┆ 90       │
│ ryptobact ┆ c88727827 ┆           ┆           ┆   ┆           ┆           ┆ es sp9005 ┆          │
│ ero…      ┆ 526…      ┆           ┆           ┆   ┆           ┆           ┆ 469…      ┆          │
│ GCA_92779 ┆ bcb17cf3e ┆ ERR321198 ┆ 0.004314  ┆ … ┆ 28        ┆ 4525088   ┆ s__Crypto ┆ ERR32119 │
│ 8655 s__C ┆ 5825e4662 ┆ 9         ┆           ┆   ┆           ┆           ┆ bacteroid ┆ 89       │
│ ryptobact ┆ c88727827 ┆           ┆           ┆   ┆           ┆           ┆ es sp9005 ┆          │
│ ero…      ┆ 526…      ┆           ┆           ┆   ┆           ┆           ┆ 469…      ┆          │
│ GCA_02872 ┆ 5f3ec5317 ┆ ERR321182 ┆ 0.003977  ┆ … ┆ 30        ┆ 977071    ┆ s__Prevot ┆ ERR32118 │
│ 7695 s__P ┆ 3d835a3cb ┆ 1         ┆           ┆   ┆           ┆           ┆ ella sp00 ┆ 21       │
│ revotella ┆ 129557502 ┆           ┆           ┆   ┆           ┆           ┆ 0434975   ┆          │
│ sp…       ┆ 962…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_94550 ┆ e0fb5daef ┆ ERR321182 ┆ 0.005231  ┆ … ┆ 33        ┆ 977071    ┆ s__Prevot ┆ ERR32118 │
│ 1735 s__P ┆ 6be045ea4 ┆ 1         ┆           ┆   ┆           ┆           ┆ ella sp00 ┆ 21       │
│ revotella ┆ 71399dbdf ┆           ┆           ┆   ┆           ┆           ┆ 2251295   ┆          │
│ sp…       ┆ fbf…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_94550 ┆ e0fb5daef ┆ ERR321174 ┆ 0.005549  ┆ … ┆ 36        ┆ 915385    ┆ s__Prevot ┆ ERR32117 │
│ 1735 s__P ┆ 6be045ea4 ┆ 7         ┆           ┆   ┆           ┆           ┆ ella sp00 ┆ 47       │
│ revotella ┆ 71399dbdf ┆           ┆           ┆   ┆           ┆           ┆ 2251295   ┆          │
│ sp…       ┆ fbf…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_92779 ┆ bcb17cf3e ┆ ERR321182 ┆ 0.007135  ┆ … ┆ 43        ┆ 4404056   ┆ s__Crypto ┆ ERR32118 │
│ 8655 s__C ┆ 5825e4662 ┆ 2         ┆           ┆   ┆           ┆           ┆ bacteroid ┆ 22       │
│ ryptobact ┆ c88727827 ┆           ┆           ┆   ┆           ┆           ┆ es sp9005 ┆          │
│ ero…      ┆ 526…      ┆           ┆           ┆   ┆           ┆           ┆ 469…      ┆          │
│ GCA_94583 ┆ 5fa208478 ┆ ERR321198 ┆ 0.004436  ┆ … ┆ 64        ┆ 4525088   ┆ s__Sodali ┆ ERR32119 │
│ 4365 s__S ┆ 801183d23 ┆ 9         ┆           ┆   ┆           ┆           ┆ philus    ┆ 89       │
│ odaliphil ┆ 24c715109 ┆           ┆           ┆   ┆           ┆           ┆ sp0045575 ┆          │
│ us …      ┆ d37…      ┆           ┆           ┆   ┆           ┆           ┆ 65        ┆          │
│ GCA_94583 ┆ 5fa208478 ┆ ERR321199 ┆ 0.004603  ┆ … ┆ 64        ┆ 3075473   ┆ s__Sodali ┆ ERR32119 │
│ 4365 s__S ┆ 801183d23 ┆ 0         ┆           ┆   ┆           ┆           ┆ philus    ┆ 90       │
│ odaliphil ┆ 24c715109 ┆           ┆           ┆   ┆           ┆           ┆ sp0045575 ┆          │
│ us …      ┆ d37…      ┆           ┆           ┆   ┆           ┆           ┆ 65        ┆          │
│ GCA_94550 ┆ e0fb5daef ┆ ERR321199 ┆ 0.00967   ┆ … ┆ 73        ┆ 3075473   ┆ s__Prevot ┆ ERR32119 │
│ 1735 s__P ┆ 6be045ea4 ┆ 0         ┆           ┆   ┆           ┆           ┆ ella sp00 ┆ 90       │
│ revotella ┆ 71399dbdf ┆           ┆           ┆   ┆           ┆           ┆ 2251295   ┆          │
│ sp…       ┆ fbf…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_02872 ┆ 5f3ec5317 ┆ ERR321182 ┆ 0.008502  ┆ … ┆ 71        ┆ 4404056   ┆ s__Prevot ┆ ERR32118 │
│ 7695 s__P ┆ 3d835a3cb ┆ 2         ┆           ┆   ┆           ┆           ┆ ella sp00 ┆ 22       │
│ revotella ┆ 129557502 ┆           ┆           ┆   ┆           ┆           ┆ 0434975   ┆          │
│ sp…       ┆ 962…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_02872 ┆ 5f3ec5317 ┆ ERR321199 ┆ 0.00864   ┆ … ┆ 71        ┆ 3075473   ┆ s__Prevot ┆ ERR32119 │
│ 7695 s__P ┆ 3d835a3cb ┆ 0         ┆           ┆   ┆           ┆           ┆ ella sp00 ┆ 90       │
│ revotella ┆ 129557502 ┆           ┆           ┆   ┆           ┆           ┆ 0434975   ┆          │
│ sp…       ┆ 962…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_94550 ┆ e0fb5daef ┆ ERR321198 ┆ 0.010304  ┆ … ┆ 75        ┆ 4525088   ┆ s__Prevot ┆ ERR32119 │
│ 1735 s__P ┆ 6be045ea4 ┆ 9         ┆           ┆   ┆           ┆           ┆ ella sp00 ┆ 89       │
│ revotella ┆ 71399dbdf ┆           ┆           ┆   ┆           ┆           ┆ 2251295   ┆          │
│ sp…       ┆ fbf…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_02872 ┆ 5f3ec5317 ┆ ERR321198 ┆ 0.009188  ┆ … ┆ 80        ┆ 4525088   ┆ s__Prevot ┆ ERR32119 │
│ 7695 s__P ┆ 3d835a3cb ┆ 9         ┆           ┆   ┆           ┆           ┆ ella sp00 ┆ 89       │
│ revotella ┆ 129557502 ┆           ┆           ┆   ┆           ┆           ┆ 0434975   ┆          │
│ sp…       ┆ 962…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_94583 ┆ 5fa208478 ┆ ERR321174 ┆ 0.005775  ┆ … ┆ 72        ┆ 915385    ┆ s__Sodali ┆ ERR32117 │
│ 4365 s__S ┆ 801183d23 ┆ 7         ┆           ┆   ┆           ┆           ┆ philus    ┆ 47       │
│ odaliphil ┆ 24c715109 ┆           ┆           ┆   ┆           ┆           ┆ sp0045575 ┆          │
│ us …      ┆ d37…      ┆           ┆           ┆   ┆           ┆           ┆ 65        ┆          │
│ GCA_94583 ┆ 5fa208478 ┆ ERR321182 ┆ 0.006026  ┆ … ┆ 77        ┆ 977071    ┆ s__Sodali ┆ ERR32118 │
│ 4365 s__S ┆ 801183d23 ┆ 1         ┆           ┆   ┆           ┆           ┆ philus    ┆ 21       │
│ odaliphil ┆ 24c715109 ┆           ┆           ┆   ┆           ┆           ┆ sp0045575 ┆          │
│ us …      ┆ d37…      ┆           ┆           ┆   ┆           ┆           ┆ 65        ┆          │
│ GCA_94550 ┆ e0fb5daef ┆ ERR321182 ┆ 0.012524  ┆ … ┆ 85        ┆ 4404056   ┆ s__Prevot ┆ ERR32118 │
│ 1735 s__P ┆ 6be045ea4 ┆ 2         ┆           ┆   ┆           ┆           ┆ ella sp00 ┆ 22       │
│ revotella ┆ 71399dbdf ┆           ┆           ┆   ┆           ┆           ┆ 2251295   ┆          │
│ sp…       ┆ fbf…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCA_94583 ┆ 5fa208478 ┆ ERR321182 ┆ 0.009541  ┆ … ┆ 119       ┆ 4404056   ┆ s__Sodali ┆ ERR32118 │
│ 4365 s__S ┆ 801183d23 ┆ 2         ┆           ┆   ┆           ┆           ┆ philus    ┆ 22       │
│ odaliphil ┆ 24c715109 ┆           ┆           ┆   ┆           ┆           ┆ sp0045575 ┆          │
│ us …      ┆ d37…      ┆           ┆           ┆   ┆           ┆           ┆ 65        ┆          │
│ GCF_00125 ┆ 2e7f136ca ┆ ERR321174 ┆ 0.008973  ┆ … ┆ 11892     ┆ 915385    ┆ s__Escher ┆ ERR32117 │
│ 6715 s__E ┆ e1634a43c ┆ 7         ┆           ┆   ┆           ┆           ┆ ichia     ┆ 47       │
│ scherichi ┆ 52b78cb97 ┆           ┆           ┆   ┆           ┆           ┆ coli      ┆          │
│ a c…      ┆ 0e0…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCF_00125 ┆ 2e7f136ca ┆ ERR321203 ┆ 0.00983   ┆ … ┆ 18455     ┆ 1343464   ┆ s__Escher ┆ ERR32120 │
│ 6715 s__E ┆ e1634a43c ┆ 6         ┆           ┆   ┆           ┆           ┆ ichia     ┆ 36       │
│ scherichi ┆ 52b78cb97 ┆           ┆           ┆   ┆           ┆           ┆ coli      ┆          │
│ a c…      ┆ 0e0…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCF_00125 ┆ 2e7f136ca ┆ ERR321203 ┆ 0.011171  ┆ … ┆ 20591     ┆ 1490940   ┆ s__Escher ┆ ERR32120 │
│ 6715 s__E ┆ e1634a43c ┆ 5         ┆           ┆   ┆           ┆           ┆ ichia     ┆ 35       │
│ scherichi ┆ 52b78cb97 ┆           ┆           ┆   ┆           ┆           ┆ coli      ┆          │
│ a c…      ┆ 0e0…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCF_00125 ┆ 2e7f136ca ┆ ERR321202 ┆ 0.012096  ┆ … ┆ 23112     ┆ 1580518   ┆ s__Escher ┆ ERR32120 │
│ 6715 s__E ┆ e1634a43c ┆ 4         ┆           ┆   ┆           ┆           ┆ ichia     ┆ 24       │
│ scherichi ┆ 52b78cb97 ┆           ┆           ┆   ┆           ┆           ┆ coli      ┆          │
│ a c…      ┆ 0e0…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCF_00125 ┆ 2e7f136ca ┆ ERR321182 ┆ 0.013234  ┆ … ┆ 12181     ┆ 977071    ┆ s__Escher ┆ ERR32118 │
│ 6715 s__E ┆ e1634a43c ┆ 1         ┆           ┆   ┆           ┆           ┆ ichia     ┆ 21       │
│ scherichi ┆ 52b78cb97 ┆           ┆           ┆   ┆           ┆           ┆ coli      ┆          │
│ a c…      ┆ 0e0…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCF_00125 ┆ 2e7f136ca ┆ ERR321202 ┆ 0.014312  ┆ … ┆ 30128     ┆ 2003005   ┆ s__Escher ┆ ERR32120 │
│ 6715 s__E ┆ e1634a43c ┆ 5         ┆           ┆   ┆           ┆           ┆ ichia     ┆ 25       │
│ scherichi ┆ 52b78cb97 ┆           ┆           ┆   ┆           ┆           ┆ coli      ┆          │
│ a c…      ┆ 0e0…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCF_00125 ┆ 2e7f136ca ┆ ERR321199 ┆ 0.015763  ┆ … ┆ 40232     ┆ 3075473   ┆ s__Escher ┆ ERR32119 │
│ 6715 s__E ┆ e1634a43c ┆ 0         ┆           ┆   ┆           ┆           ┆ ichia     ┆ 90       │
│ scherichi ┆ 52b78cb97 ┆           ┆           ┆   ┆           ┆           ┆ coli      ┆          │
│ a c…      ┆ 0e0…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCF_00125 ┆ 2e7f136ca ┆ ERR321198 ┆ 0.023955  ┆ … ┆ 58370     ┆ 4525088   ┆ s__Escher ┆ ERR32119 │
│ 6715 s__E ┆ e1634a43c ┆ 9         ┆           ┆   ┆           ┆           ┆ ichia     ┆ 89       │
│ scherichi ┆ 52b78cb97 ┆           ┆           ┆   ┆           ┆           ┆ coli      ┆          │
│ a c…      ┆ 0e0…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GCF_00125 ┆ 2e7f136ca ┆ ERR321182 ┆ 0.030339  ┆ … ┆ 56169     ┆ 4404056   ┆ s__Escher ┆ ERR32118 │
│ 6715 s__E ┆ e1634a43c ┆ 2         ┆           ┆   ┆           ┆           ┆ ichia     ┆ 22       │
│ scherichi ┆ 52b78cb97 ┆           ┆           ┆   ┆           ┆           ┆ coli      ┆          │
│ a c…      ┆ 0e0…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Explore PRJNA373834 study (Cdiff/formula)

"intestinal microbiome in feces from sows, five days after farrowing, their piglets during suckling and two weeks after weaning, 5-day old artificially reared and formula-fed siblings, and FP infected with Clostridium difficile"

no publication?

summary: all of the formula fed piglets < 10 core. also two of the suckling piglets.

In [29]:
biosample_info = """\
SAMN06315441	Weaned Piglet 3
SAMN06315439	Weaned Piglet 1
SAMN06315460	Sow 4
SAMN06315449	Suckling Piglet 3
SAMN06315450	Suckling Piglet 4
SAMN06315453	Formula fed 3
SAMN06315440	Weaned Piglet 2
SAMN06315455	Formula fed cdiff 2
SAMN06315454	Formula fed cdiff 1
SAMN06315443	Weaned Piglet 5
SAMN06315452	Formula fed 2
SAMN06315446	Weaned Piglet 8
SAMN06315447	Suckling Piglet 1
SAMN06315445	Weaned Piglet 7
SAMN06315456	Formula fed cdiff 3
SAMN06315451	Formula fed 1
SAMN06315458	Sow 2
SAMN06315459	Sow 3
SAMN06315448	Suckling Piglet 2
SAMN06315444	Weaned Piglet 6
SAMN06315442	Weaned Piglet 4
SAMN06315457	Sow 1
"""

xx = []
for line in biosample_info.splitlines():
    biosample, descr = line.strip().split('	')
    is_formula=0
    if 'formula' in descr.lower():
        is_formula=1
    is_cdiff=0
    if 'cdiff' in descr.lower():
        is_cdiff= 1
    xx.append(dict(biosample=biosample, descr=descr, is_formula=is_formula, is_cdiff=is_cdiff))

biosample_df = pl.DataFrame(xx)
with pl.Config(tbl_rows=-1):
    print(biosample_df)

shape: (22, 4)
┌──────────────┬─────────────────────┬────────────┬──────────┐
│ biosample    ┆ descr               ┆ is_formula ┆ is_cdiff │
│ ---          ┆ ---                 ┆ ---        ┆ ---      │
│ str          ┆ str                 ┆ i64        ┆ i64      │
╞══════════════╪═════════════════════╪════════════╪══════════╡
│ SAMN06315441 ┆ Weaned Piglet 3     ┆ 0          ┆ 0        │
│ SAMN06315439 ┆ Weaned Piglet 1     ┆ 0          ┆ 0        │
│ SAMN06315460 ┆ Sow 4               ┆ 0          ┆ 0        │
│ SAMN06315449 ┆ Suckling Piglet 3   ┆ 0          ┆ 0        │
│ SAMN06315450 ┆ Suckling Piglet 4   ┆ 0          ┆ 0        │
│ SAMN06315453 ┆ Formula fed 3       ┆ 1          ┆ 0        │
│ SAMN06315440 ┆ Weaned Piglet 2     ┆ 0          ┆ 0        │
│ SAMN06315455 ┆ Formula fed cdiff 2 ┆ 1          ┆ 1        │
│ SAMN06315454 ┆ Formula fed cdiff 1 ┆ 1          ┆ 1        │
│ SAMN06315443 ┆ Weaned Piglet 5     ┆ 0          ┆ 0        │
│ SAMN06315452 ┆ Formula fed 2       ┆ 1          ┆ 0        │
│ SAMN06315446 ┆ Weaned Piglet 8     ┆ 0          ┆ 0        │
│ SAMN06315447 ┆ Suckling Piglet 1   ┆ 0          ┆ 0        │
│ SAMN06315445 ┆ Weaned Piglet 7     ┆ 0          ┆ 0        │
│ SAMN06315456 ┆ Formula fed cdiff 3 ┆ 1          ┆ 1        │
│ SAMN06315451 ┆ Formula fed 1       ┆ 1          ┆ 0        │
│ SAMN06315458 ┆ Sow 2               ┆ 0          ┆ 0        │
│ SAMN06315459 ┆ Sow 3               ┆ 0          ┆ 0        │
│ SAMN06315448 ┆ Suckling Piglet 2   ┆ 0          ┆ 0        │
│ SAMN06315444 ┆ Weaned Piglet 6     ┆ 0          ┆ 0        │
│ SAMN06315442 ┆ Weaned Piglet 4     ┆ 0          ┆ 0        │
│ SAMN06315457 ┆ Sow 1               ┆ 0          ┆ 0        │
└──────────────┴─────────────────────┴────────────┴──────────┘

In [30]:
with pl.Config(tbl_rows=-1):
    print(by_acc
     .join(metadata_df, left_on='match_name', right_on='acc', how='inner')
     .filter(pl.col('bioproject') == 'PRJNA373834')
     .join(biosample_df, on='biosample', how='inner')
     .select(['n_core', 'biosample', 'match_name', 'descr', 'is_cdiff', 'is_formula'])
     .sort('is_cdiff', 'is_formula')
    )

shape: (21, 6)
┌────────┬──────────────┬────────────┬─────────────────────┬──────────┬────────────┐
│ n_core ┆ biosample    ┆ match_name ┆ descr               ┆ is_cdiff ┆ is_formula │
│ ---    ┆ ---          ┆ ---        ┆ ---                 ┆ ---      ┆ ---        │
│ u32    ┆ str          ┆ str        ┆ str                 ┆ i64      ┆ i64        │
╞════════╪══════════════╪════════════╪═════════════════════╪══════════╪════════════╡
│ 17     ┆ SAMN06315459 ┆ SRR5240726 ┆ Sow 3               ┆ 0        ┆ 0          │
│ 17     ┆ SAMN06315439 ┆ SRR5240751 ┆ Weaned Piglet 1     ┆ 0        ┆ 0          │
│ 17     ┆ SAMN06315460 ┆ SRR5240725 ┆ Sow 4               ┆ 0        ┆ 0          │
│ 8      ┆ SAMN06315449 ┆ SRR5240737 ┆ Suckling Piglet 3   ┆ 0        ┆ 0          │
│ 16     ┆ SAMN06315450 ┆ SRR5240736 ┆ Suckling Piglet 4   ┆ 0        ┆ 0          │
│ 17     ┆ SAMN06315441 ┆ SRR5240749 ┆ Weaned Piglet 3     ┆ 0        ┆ 0          │
│ 17     ┆ SAMN06315440 ┆ SRR5240750 ┆ Weaned Piglet 2     ┆ 0        ┆ 0          │
│ 17     ┆ SAMN06315457 ┆ SRR5240728 ┆ Sow 1               ┆ 0        ┆ 0          │
│ 17     ┆ SAMN06315442 ┆ SRR5240748 ┆ Weaned Piglet 4     ┆ 0        ┆ 0          │
│ 17     ┆ SAMN06315443 ┆ SRR5240747 ┆ Weaned Piglet 5     ┆ 0        ┆ 0          │
│ 17     ┆ SAMN06315444 ┆ SRR5240745 ┆ Weaned Piglet 6     ┆ 0        ┆ 0          │
│ 16     ┆ SAMN06315446 ┆ SRR5240743 ┆ Weaned Piglet 8     ┆ 0        ┆ 0          │
│ 17     ┆ SAMN06315445 ┆ SRR5240744 ┆ Weaned Piglet 7     ┆ 0        ┆ 0          │
│ 9      ┆ SAMN06315448 ┆ SRR5240741 ┆ Suckling Piglet 2   ┆ 0        ┆ 0          │
│ 17     ┆ SAMN06315458 ┆ SRR5240727 ┆ Sow 2               ┆ 0        ┆ 0          │
│ 6      ┆ SAMN06315453 ┆ SRR5240732 ┆ Formula fed 3       ┆ 0        ┆ 1          │
│ 4      ┆ SAMN06315451 ┆ SRR5240735 ┆ Formula fed 1       ┆ 0        ┆ 1          │
│ 5      ┆ SAMN06315452 ┆ SRR5240734 ┆ Formula fed 2       ┆ 0        ┆ 1          │
│ 5      ┆ SAMN06315455 ┆ SRR5240730 ┆ Formula fed cdiff 2 ┆ 1        ┆ 1          │
│ 5      ┆ SAMN06315456 ┆ SRR5240729 ┆ Formula fed cdiff 3 ┆ 1        ┆ 1          │
│ 6      ┆ SAMN06315454 ┆ SRR5240731 ┆ Formula fed cdiff 1 ┆ 1        ┆ 1          │
└────────┴──────────────┴────────────┴─────────────────────┴──────────┴────────────┘

In [31]:
(low_core_acc2.filter(pl.col('bioproject') == 'PRJNA373834')
 .join(biosample_df, on='biosample', how='inner')
 .select(['n_core', 'biosample', 'descr', 'is_cdiff', 'is_formula'])
)

shape: (8, 5)
┌────────┬──────────────┬─────────────────────┬──────────┬────────────┐
│ n_core ┆ biosample    ┆ descr               ┆ is_cdiff ┆ is_formula │
│ ---    ┆ ---          ┆ ---                 ┆ ---      ┆ ---        │
│ u32    ┆ str          ┆ str                 ┆ i64      ┆ i64        │
╞════════╪══════════════╪═════════════════════╪══════════╪════════════╡
│ 8      ┆ SAMN06315449 ┆ Suckling Piglet 3   ┆ 0        ┆ 0          │
│ 6      ┆ SAMN06315453 ┆ Formula fed 3       ┆ 0        ┆ 1          │
│ 5      ┆ SAMN06315455 ┆ Formula fed cdiff 2 ┆ 1        ┆ 1          │
│ 6      ┆ SAMN06315454 ┆ Formula fed cdiff 1 ┆ 1        ┆ 1          │
│ 5      ┆ SAMN06315452 ┆ Formula fed 2       ┆ 0        ┆ 1          │
│ 5      ┆ SAMN06315456 ┆ Formula fed cdiff 3 ┆ 1        ┆ 1          │
│ 4      ┆ SAMN06315451 ┆ Formula fed 1       ┆ 0        ┆ 1          │
│ 9      ┆ SAMN06315448 ┆ Suckling Piglet 2   ┆ 0        ┆ 0          │
└────────┴──────────────┴─────────────────────┴──────────┴────────────┘

In [32]:
low_core_acc2.filter(pl.col('bioproject') == 'PRJNA373834')

shape: (8, 69)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ acc        ┆ bioproject ┆ n_core ┆ sample_na ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_s │
│ ---        ┆ ---        ┆ ---    ┆ me        ┆   ┆ ---       ┆ create_da ┆ version   ┆ earch     │
│ str        ┆ str        ┆ u32    ┆ ---       ┆   ┆ str       ┆ te        ┆ ---       ┆ ---       │
│            ┆            ┆        ┆ str       ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│            ┆            ┆        ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR5240735 ┆ PRJNA37383 ┆ 4      ┆ 2016_CRC_ ┆ … ┆ 192769841 ┆ "2017-02- ┆ null      ┆ "2016_CRC │
│            ┆ 4          ┆        ┆ FP1       ┆   ┆ 1         ┆ 09T10:39: ┆           ┆ _FP1"     │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR5240734 ┆ PRJNA37383 ┆ 5      ┆ 2016_CRC_ ┆ … ┆ 187238754 ┆ "2017-02- ┆ null      ┆ "2016_CRC │
│            ┆ 4          ┆        ┆ FP2       ┆   ┆ 1         ┆ 09T10:45: ┆           ┆ _FP2"     │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR5240729 ┆ PRJNA37383 ┆ 5      ┆ 2016_CRC_ ┆ … ┆ 177513600 ┆ "2017-02- ┆ null      ┆ "2016_CRC │
│            ┆ 4          ┆        ┆ FP-CD3    ┆   ┆ 9         ┆ 09T10:37: ┆           ┆ _FP-CD3"  │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR5240730 ┆ PRJNA37383 ┆ 5      ┆ 2016_CRC_ ┆ … ┆ 218213908 ┆ "2017-02- ┆ null      ┆ "2016_CRC │
│            ┆ 4          ┆        ┆ FP-CD2    ┆   ┆ 0         ┆ 09T10:40: ┆           ┆ _FP-CD2"  │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR5240732 ┆ PRJNA37383 ┆ 6      ┆ 2016_CRC_ ┆ … ┆ 140259883 ┆ "2017-02- ┆ null      ┆ "2016_CRC │
│            ┆ 4          ┆        ┆ FP3       ┆   ┆ 9         ┆ 09T10:40: ┆           ┆ _FP3"     │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR5240731 ┆ PRJNA37383 ┆ 6      ┆ 2016_CRC_ ┆ … ┆ 206420554 ┆ "2017-02- ┆ null      ┆ "2016_CRC │
│            ┆ 4          ┆        ┆ FP-CD1    ┆   ┆ 1         ┆ 09T10:40: ┆           ┆ _FP-CD1"  │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR5240737 ┆ PRJNA37383 ┆ 8      ┆ 2016_CRC_ ┆ … ┆ 213953989 ┆ "2017-02- ┆ null      ┆ "2016_CRC │
│            ┆ 4          ┆        ┆ SP3       ┆   ┆ 6         ┆ 09T10:39: ┆           ┆ _SP3"     │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR5240741 ┆ PRJNA37383 ┆ 9      ┆ 2016_CRC_ ┆ … ┆ 181714007 ┆ "2017-02- ┆ null      ┆ "2016_CRC │
│            ┆ 4          ┆        ┆ SP2       ┆   ┆ 3         ┆ 09T10:58: ┆           ┆ _SP2"     │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Explore PRJNA668104 (necrotizing enterocolitis study)

[ENA link](https://www.ebi.ac.uk/ena/browser/view/PRJNA668104)

publication: https://www.nature.com/articles/s41522-022-00310-2

github: https://github.com/yanhui09/FMT-donor/tree/master

metadata link: https://github.com/yanhui09/FMT-donor/blob/master/data/Metadata.tsv

Weird: it looks like we didn't include all 40 in the 3216 metagenomes being searched? only 19?
e.g. SRR12795742 and SRR12795718 are not in the 3216 list. Why not?? MAYBE HOST CONTAM.

In [33]:
biosample_text = StringIO('''accession	description
SAMN16396816	FMT1_pig_1
SAMN16396823	FMT1_pig_8
SAMN16396815	DONOR2
SAMN16396805	CON_pig_4
SAMN16396829	FMT2_pig_1
SAMN16396834	FMT2_pig_6
SAMN16396802	CON_pig_1
SAMN16396814	DONOR1
SAMN16396820	FMT1_pig_5
SAMN16396837	FMT2_pig_9
SAMN16396808	CON_pig_7
SAMN16396839	FMT2_pig_11
SAMN16396840	FMT2_pig_12
SAMN16396813	CON_pig_12
SAMN16396835	FMT2_pig_7
SAMN16396826	FMT1_pig_11
SAMN16396819	FMT1_pig_4
SAMN16396818	FMT1_pig_3
SAMN16396828	FMT1_pig_13
SAMN16396807	CON_pig_6
SAMN16396822	FMT1_pig_7
SAMN16396832	FMT2_pig_4
SAMN16396806	CON_pig_5
SAMN16396824	FMT1_pig_9
SAMN16396817	FMT1_pig_2
SAMN16396831	FMT2_pig_3
SAMN16396836	FMT2_pig_8
SAMN16396811	CON_pig_10
SAMN16396821	FMT1_pig_6
SAMN16396809	CON_pig_8
SAMN16396810	CON_pig_9
SAMN16396827	FMT1_pig_12
SAMN16396830	FMT2_pig_2
SAMN16396803	CON_pig_2
SAMN16396838	FMT2_pig_10
SAMN16396804	CON_pig_3
SAMN16396812	CON_pig_11
SAMN16396825	FMT1_pig_10
SAMN16396841	FMT2_pig_13
SAMN16396833	FMT2_pig_5
''')

biosample_df = pl.read_csv(biosample_text, separator='\t').rename({ 'accession': 'biosample' })
biosample_df

shape: (40, 2)
┌──────────────┬─────────────┐
│ biosample    ┆ description │
│ ---          ┆ ---         │
│ str          ┆ str         │
╞══════════════╪═════════════╡
│ SAMN16396816 ┆ FMT1_pig_1  │
│ SAMN16396823 ┆ FMT1_pig_8  │
│ SAMN16396815 ┆ DONOR2      │
│ SAMN16396805 ┆ CON_pig_4   │
│ SAMN16396829 ┆ FMT2_pig_1  │
│ …            ┆ …           │
│ SAMN16396804 ┆ CON_pig_3   │
│ SAMN16396812 ┆ CON_pig_11  │
│ SAMN16396825 ┆ FMT1_pig_10 │
│ SAMN16396841 ┆ FMT2_pig_13 │
│ SAMN16396833 ┆ FMT2_pig_5  │
└──────────────┴─────────────┘

In [34]:
with pl.Config(tbl_rows=-1):
    print(low_core_acc2
 .filter(pl.col('bioproject') == 'PRJNA668104')
 .join(biosample_df, on='biosample', how='inner')
 .select(['acc', 'n_core','description'])
 .sort('description')
 )

shape: (19, 3)
┌─────────────┬────────┬─────────────┐
│ acc         ┆ n_core ┆ description │
│ ---         ┆ ---    ┆ ---         │
│ str         ┆ u32    ┆ str         │
╞═════════════╪════════╪═════════════╡
│ SRR12795785 ┆ 1      ┆ CON_pig_3   │
│ SRR12795774 ┆ 2      ┆ CON_pig_4   │
│ SRR12795740 ┆ 2      ┆ CON_pig_5   │
│ SRR12795729 ┆ 2      ┆ CON_pig_6   │
│ SRR12795780 ┆ 2      ┆ FMT1_pig_11 │
│ SRR12795790 ┆ 1      ┆ FMT1_pig_2  │
│ SRR12795789 ┆ 2      ┆ FMT1_pig_3  │
│ SRR12795784 ┆ 2      ┆ FMT1_pig_7  │
│ SRR12795783 ┆ 2      ┆ FMT1_pig_8  │
│ SRR12795782 ┆ 2      ┆ FMT1_pig_9  │
│ SRR12795744 ┆ 2      ┆ FMT2_pig_10 │
│ SRR12795741 ┆ 2      ┆ FMT2_pig_13 │
│ SRR12795776 ┆ 4      ┆ FMT2_pig_2  │
│ SRR12795775 ┆ 2      ┆ FMT2_pig_3  │
│ SRR12795773 ┆ 3      ┆ FMT2_pig_4  │
│ SRR12795771 ┆ 4      ┆ FMT2_pig_6  │
│ SRR12795770 ┆ 3      ┆ FMT2_pig_7  │
│ SRR12795746 ┆ 3      ┆ FMT2_pig_8  │
│ SRR12795745 ┆ 2      ┆ FMT2_pig_9  │
└─────────────┴────────┴─────────────┘

In [35]:
with pl.Config(tbl_rows=-1):
    print(biosample_df.sort('description'))

shape: (40, 2)
┌──────────────┬─────────────┐
│ biosample    ┆ description │
│ ---          ┆ ---         │
│ str          ┆ str         │
╞══════════════╪═════════════╡
│ SAMN16396802 ┆ CON_pig_1   │
│ SAMN16396811 ┆ CON_pig_10  │
│ SAMN16396812 ┆ CON_pig_11  │
│ SAMN16396813 ┆ CON_pig_12  │
│ SAMN16396803 ┆ CON_pig_2   │
│ SAMN16396804 ┆ CON_pig_3   │
│ SAMN16396805 ┆ CON_pig_4   │
│ SAMN16396806 ┆ CON_pig_5   │
│ SAMN16396807 ┆ CON_pig_6   │
│ SAMN16396808 ┆ CON_pig_7   │
│ SAMN16396809 ┆ CON_pig_8   │
│ SAMN16396810 ┆ CON_pig_9   │
│ SAMN16396814 ┆ DONOR1      │
│ SAMN16396815 ┆ DONOR2      │
│ SAMN16396816 ┆ FMT1_pig_1  │
│ SAMN16396825 ┆ FMT1_pig_10 │
│ SAMN16396826 ┆ FMT1_pig_11 │
│ SAMN16396827 ┆ FMT1_pig_12 │
│ SAMN16396828 ┆ FMT1_pig_13 │
│ SAMN16396817 ┆ FMT1_pig_2  │
│ SAMN16396818 ┆ FMT1_pig_3  │
│ SAMN16396819 ┆ FMT1_pig_4  │
│ SAMN16396820 ┆ FMT1_pig_5  │
│ SAMN16396821 ┆ FMT1_pig_6  │
│ SAMN16396822 ┆ FMT1_pig_7  │
│ SAMN16396823 ┆ FMT1_pig_8  │
│ SAMN16396824 ┆ FMT1_pig_9  │
│ SAMN16396829 ┆ FMT2_pig_1  │
│ SAMN16396838 ┆ FMT2_pig_10 │
│ SAMN16396839 ┆ FMT2_pig_11 │
│ SAMN16396840 ┆ FMT2_pig_12 │
│ SAMN16396841 ┆ FMT2_pig_13 │
│ SAMN16396830 ┆ FMT2_pig_2  │
│ SAMN16396831 ┆ FMT2_pig_3  │
│ SAMN16396832 ┆ FMT2_pig_4  │
│ SAMN16396833 ┆ FMT2_pig_5  │
│ SAMN16396834 ┆ FMT2_pig_6  │
│ SAMN16396835 ┆ FMT2_pig_7  │
│ SAMN16396836 ┆ FMT2_pig_8  │
│ SAMN16396837 ┆ FMT2_pig_9  │
└──────────────┴─────────────┘

In [36]:
# from https://github.com/yanhui09/FMT-donor/blob/master/data/Metadata.tsv
github_meta_text = StringIO("""""	"CustomerID"	"FMT_ID"	"Litter"	"Sex"	"Group_old"	"GroupID"	"Group"	"NEC"	"NEC_max"	"NEC_severity"
"17119-05-01-243200068"	"0"	"400"	"1"	"m"	"CON4"	"CON4_1"	"CON"	0	3	2.33333333333333
"17119-05-02-243200066"	"1"	"401"	"1"	"m"	"CON4"	"CON4_2"	"CON"	1	6	6
"17119-05-03-243200095"	"2"	"402"	"1"	"m"	"NEW4"	"NEW4_1"	"FMT1"	1	5	3.33333333333333
"17119-05-04-243200101"	"3"	"403"	"1"	"f"	"CON4"	"CON4_3"	"CON"	0	3	1.66666666666667
"17119-05-05-243200087"	"4"	"404"	"1"	"f"	"OLD4"	"OLD4_1"	"FMT2"	0	1	1
"17119-05-06-243200069"	"5"	"405"	"1"	"f"	"NEW4"	"NEW4_2"	"FMT1"	0	1	1
"17119-05-07-243200099"	"6"	"406"	"1"	"f"	"CON4"	"CON4_4"	"CON"	0	2	1.66666666666667
"17119-05-08-243200071"	"7"	"407"	"1"	"m"	"OLD4"	"OLD4_2"	"FMT2"	0	2	1.33333333333333
"17119-05-09-243200070"	"8"	"408"	"1"	"f"	"NEW4"	"NEW4_3"	"FMT1"	0	1	1
"17119-05-10-243200096"	"9"	"409"	"1"	"f"	"CON4"	"CON4_5"	"CON"	0	2	1.33333333333333
"17119-05-11-243200091"	"10"	"410"	"1"	"f"	"OLD4"	"OLD4_3"	"FMT2"	0	2	1.66666666666667
"17119-05-12-243200081"	"11"	"411"	"1"	"f"	"NEW4"	"NEW4_4"	"FMT1"	0	2	1.33333333333333
"17119-05-13-243200076"	"12"	"412"	"1"	"m"	"CON4"	"CON4_6"	"CON"	1	5	4
"17119-05-14-243200089"	"13"	"413"	"1"	"f"	"OLD4"	"OLD4_4"	"FMT2"	0	1	1
"17119-05-15-243200093"	"14"	"414"	"1"	"m"	"NEW4"	"NEW4_5"	"FMT1"	0	1	1
"17119-05-16-243200072"	"15"	"415"	"1"	"m"	"CON4"	"CON4_7"	"CON"	1	6	4.33333333333333
"17119-05-17-243200086"	"16"	"416"	"1"	"m"	"OLD4"	"OLD4_5"	"FMT2"	0	1	1
"17119-05-18-243200100"	"17"	"417"	"1"	"m"	"NEW4"	"NEW4_6"	"FMT1"	1	5	3.33333333333333
"17119-05-19-243200062"	"18"	"418"	"1"	"m"	"OLD4"	"OLD4_6"	"FMT2"	0	2	1.66666666666667
"17119-05-20-243200063"	"19"	"419"	"1"	"m"	"NEW4"	"NEW4_7"	"FMT1"	1	5	2.33333333333333
"17119-05-21-243200075"	"20"	"420"	"1"	"m"	"OLD4"	"OLD4_7"	"FMT2"	0	2	1.33333333333333
"17119-05-22-243200094"	"21"	"421"	"1"	"m"	"NEW4"	"NEW4_8"	"FMT1"	0	3	1.66666666666667
"17119-05-23-243200073"	"22"	"422"	"2"	"f"	"OLD4"	"OLD4_8"	"FMT2"	0	2	1.33333333333333
"17119-05-24-243200088"	"23"	"423"	"2"	"f"	"CON4"	"CON4_8"	"CON"	1	5	2.33333333333333
"17119-05-25-243200085"	"24"	"424"	"2"	"f"	"NEW4"	"NEW4_9"	"FMT1"	0	1	1
"17119-05-26-243200098"	"25"	"425"	"2"	"f"	"OLD4"	"OLD4_9"	"FMT2"	0	3	1.66666666666667
"17119-05-27-243200083"	"26"	"426"	"2"	"f"	"CON4"	"CON4_9"	"CON"	0	1	1
"17119-05-28-243200078"	"27"	"427"	"2"	"f"	"NEW4"	"NEW4_10"	"FMT1"	0	1	1
"17119D-05-29-243200065"	"28"	"428"	"2"	"f"	"OLD4"	"OLD4_13"	"FMT2"	0	1	1
"17119-05-30-243200082"	"29"	"429"	"2"	"f"	"CON4"	"CON4_10"	"CON"	0	1	1
"17119-05-31-243200080"	"30"	"430"	"2"	"f"	"NEW4"	"NEW4_11"	"FMT1"	0	2	1.33333333333333
"17119-05-32-243200092"	"31"	"431"	"2"	"f"	"OLD4"	"OLD4_10"	"FMT2"	0	1	1
"17119-05-33-243200064"	"32"	"432"	"2"	"f"	"CON4"	"CON4_11"	"CON"	1	6	4
"17119-05-34-243200097"	"33"	"433"	"2"	"f"	"NEW4"	"NEW4_12"	"FMT1"	0	3	1.66666666666667
"17119-05-35-243200067"	"34"	"434"	"2"	"m"	"OLD4"	"OLD4_11"	"FMT2"	0	2	1.33333333333333
"17119-05-36-243200079"	"36"	"436"	"2"	"m"	"NEW4"	"NEW4_13"	"FMT1"	0	2	1.33333333333333
"17119-05-37-243200074"	"37"	"437"	"2"	"m"	"OLD4"	"OLD4_12"	"FMT2"	0	1	1
"17119-05-38-243200077"	"38"	"438"	"2"	"m"	"CON4"	"CON4_12"	"CON"	0	1	1
"17119-05-40-243200090"	"new"	"new"	"DONOR1"	"new"	"NEW Donor"	"NEW_Donor"	"DONOR1"	0	0	0
"17119-05-39-243200084"	"old"	"old"	"DONOR2"	"old"	"OLD Donor"	"OLD_Donor"	"DONOR2"	0	0	0
""")
github_meta_df = pl.read_csv(github_meta_text, separator='\t').rename({'': 'timestamp'})
github_meta_df

shape: (40, 11)
┌───────────────────────┬────────────┬────────┬────────┬───┬────────┬─────┬─────────┬──────────────┐
│ timestamp             ┆ CustomerID ┆ FMT_ID ┆ Litter ┆ … ┆ Group  ┆ NEC ┆ NEC_max ┆ NEC_severity │
│ ---                   ┆ ---        ┆ ---    ┆ ---    ┆   ┆ ---    ┆ --- ┆ ---     ┆ ---          │
│ str                   ┆ str        ┆ str    ┆ str    ┆   ┆ str    ┆ i64 ┆ i64     ┆ f64          │
╞═══════════════════════╪════════════╪════════╪════════╪═══╪════════╪═════╪═════════╪══════════════╡
│ 17119-05-01-243200068 ┆ 0          ┆ 400    ┆ 1      ┆ … ┆ CON    ┆ 0   ┆ 3       ┆ 2.333333     │
│ 17119-05-02-243200066 ┆ 1          ┆ 401    ┆ 1      ┆ … ┆ CON    ┆ 1   ┆ 6       ┆ 6.0          │
│ 17119-05-03-243200095 ┆ 2          ┆ 402    ┆ 1      ┆ … ┆ FMT1   ┆ 1   ┆ 5       ┆ 3.333333     │
│ 17119-05-04-243200101 ┆ 3          ┆ 403    ┆ 1      ┆ … ┆ CON    ┆ 0   ┆ 3       ┆ 1.666667     │
│ 17119-05-05-243200087 ┆ 4          ┆ 404    ┆ 1      ┆ … ┆ FMT2   ┆ 0   ┆ 1       ┆ 1.0          │
│ …                     ┆ …          ┆ …      ┆ …      ┆ … ┆ …      ┆ …   ┆ …       ┆ …            │
│ 17119-05-36-243200079 ┆ 36         ┆ 436    ┆ 2      ┆ … ┆ FMT1   ┆ 0   ┆ 2       ┆ 1.333333     │
│ 17119-05-37-243200074 ┆ 37         ┆ 437    ┆ 2      ┆ … ┆ FMT2   ┆ 0   ┆ 1       ┆ 1.0          │
│ 17119-05-38-243200077 ┆ 38         ┆ 438    ┆ 2      ┆ … ┆ CON    ┆ 0   ┆ 1       ┆ 1.0          │
│ 17119-05-40-243200090 ┆ new        ┆ new    ┆ DONOR1 ┆ … ┆ DONOR1 ┆ 0   ┆ 0       ┆ 0.0          │
│ 17119-05-39-243200084 ┆ old        ┆ old    ┆ DONOR2 ┆ … ┆ DONOR2 ┆ 0   ┆ 0       ┆ 0.0          │
└───────────────────────┴────────────┴────────┴────────┴───┴────────┴─────┴─────────┴──────────────┘

In [37]:
xx_df = (low_core_acc2
 .filter(pl.col('bioproject') == 'PRJNA668104')
 .join(biosample_df, on='biosample', how='inner')
 .with_columns(
     descr2=pl.col('description').str.split('_').list.get(0),
 )
 .select(['acc', 'bioproject', 'n_core', 'sample_name', 'biosample', 'description', 'descr2'])
 )

In [38]:
by_acc2

shape: (3_216, 69)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ match_name ┆ bioproject ┆ n_core ┆ sample_na ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_s │
│ ---        ┆ ---        ┆ ---    ┆ me        ┆   ┆ ---       ┆ create_da ┆ version   ┆ earch     │
│ str        ┆ str        ┆ u32    ┆ ---       ┆   ┆ str       ┆ te        ┆ ---       ┆ ---       │
│            ┆            ┆        ┆ str       ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│            ┆            ┆        ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR1112548 ┆ PRJNA52640 ┆ 17     ┆ Fe24/1420 ┆ … ┆ 416591685 ┆ "2020-02- ┆ null      ┆ "11098298 │
│ 6          ┆ 5          ┆        ┆ 8         ┆   ┆           ┆ 20T21:25: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ ERR1135387 ┆ PRJEB11755 ┆ 17     ┆ SAMEA3663 ┆ … ┆ 460732824 ┆ "2016-01- ┆ null      ┆ "308698"  │
│            ┆            ┆        ┆ 214       ┆   ┆ 6         ┆ 13T01:23: ┆           ┆           │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1112608 ┆ PRJNA52640 ┆ 17     ┆ Fe24/1420 ┆ … ┆ 424454702 ┆ "2020-02- ┆ null      ┆ "11098298 │
│ 0          ┆ 5          ┆        ┆ 8         ┆   ┆           ┆ 20T22:03: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1112475 ┆ PRJNA52640 ┆ 16     ┆ Fe21/2979 ┆ … ┆ 394096836 ┆ "2020-02- ┆ null      ┆ "11098250 │
│ 5          ┆ 5          ┆        ┆ 6         ┆   ┆           ┆ 20T20:34: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1279983 ┆ PRJNA64693 ┆ 17     ┆ PI_5      ┆ … ┆ 236836219 ┆ "2020-10- ┆ null      ┆ "16402095 │
│ 3          ┆ 4          ┆        ┆           ┆   ┆ 8         ┆ 09T06:17: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ …          ┆ …          ┆ …      ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ SRR1112491 ┆ PRJNA52640 ┆ 17     ┆ Fe7/14183 ┆ … ┆ 333202038 ┆ "2020-02- ┆ null      ┆ "11097950 │
│ 2          ┆ 5          ┆        ┆           ┆   ┆           ┆ 20T20:45: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR8960143 ┆ PRJNA52640 ┆ 17     ┆ Ma8/14306 ┆ … ┆ 173025457 ┆ "2019-04- ┆ null      ┆ "11098459 │
│            ┆ 5          ┆        ┆           ┆   ┆ 3         ┆ 26T03:09: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1112547 ┆ PRJNA52640 ┆ 17     ┆ Fe28/2970 ┆ … ┆ 385233982 ┆ "2020-02- ┆ null      ┆ "11098310 │
│ 2          ┆ 5          ┆        ┆ 5         ┆   ┆           ┆ 20T21:17: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1118380 ┆ PRJNA52640 ┆ 17     ┆ Ma9/14208 ┆ … ┆ 457484814 ┆ "2020-02- ┆ null      ┆ "11098478 │
│ 1          ┆ 5          ┆        ┆           ┆   ┆           ┆ 26T03:30: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1118525 ┆ PRJNA52640 ┆ 17     ┆ Ma7/14186 ┆ … ┆ 587822447 ┆ "2020-02- ┆ null      ┆ "11098444 │
│ 4          ┆ 5          ┆        ┆           ┆   ┆ 8         ┆ 27T08:54: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [39]:
# not all samples are included!? k anyway.
metadata_df.filter(pl.col('bioproject') == 'PRJNA668104').select(['acc']).sort('acc')

with open('PRJNA668104.acc.list', 'wt') as fp:
    for acc in metadata_df.filter(pl.col('bioproject') == 'PRJNA668104')['acc']:
        print(f'/group/ctbrowngrp5/wort/wort-sra/sigs/{acc}.sig', file=fp)

In [40]:
xx_df = (by_acc2
 .filter(pl.col('bioproject') == 'PRJNA668104')
 .join(biosample_df, on='biosample', how='inner')
 .with_columns(
     descr2=pl.col('description').str.split('_').list.get(0),
     sample_name2=pl.col('sample_name').str.split('_').list.get(-1),
 )
 .with_columns(# replace 'donor1' with 'new'
     sample_name2=pl.when(pl.col('sample_name2')=='donor1').then(pl.lit('new')).otherwise(pl.col('sample_name2'))
 )
 .with_columns(# replace 'donor2' with 'old'
     sample_name2=pl.when(pl.col('sample_name2')=='donor2').then(pl.lit('old')).otherwise(pl.col('sample_name2'))
 )
 .join(github_meta_df, left_on='sample_name2', right_on='FMT_ID')
# .select(['match_name', 'bioproject', 'n_core', 'sample_name', 'sample_name2', 'biosample', 'description', 'descr2'])
 .sort('descr2')
 )
with pl.Config(tbl_rows=-1):
    print(xx_df)

shape: (21, 82)
┌─────────────┬─────────────┬────────┬───────────────┬───┬────────┬─────┬─────────┬──────────────┐
│ match_name  ┆ bioproject  ┆ n_core ┆ sample_name   ┆ … ┆ Group  ┆ NEC ┆ NEC_max ┆ NEC_severity │
│ ---         ┆ ---         ┆ ---    ┆ ---           ┆   ┆ ---    ┆ --- ┆ ---     ┆ ---          │
│ str         ┆ str         ┆ u32    ┆ str           ┆   ┆ str    ┆ i64 ┆ i64     ┆ f64          │
╞═════════════╪═════════════╪════════╪═══════════════╪═══╪════════╪═════╪═════════╪══════════════╡
│ SRR12795785 ┆ PRJNA668104 ┆ 1      ┆ pig_colon_403 ┆ … ┆ CON    ┆ 0   ┆ 3       ┆ 1.666667     │
│ SRR12795774 ┆ PRJNA668104 ┆ 2      ┆ pig_colon_406 ┆ … ┆ CON    ┆ 0   ┆ 2       ┆ 1.666667     │
│ SRR12795740 ┆ PRJNA668104 ┆ 2      ┆ pig_colon_409 ┆ … ┆ CON    ┆ 0   ┆ 2       ┆ 1.333333     │
│ SRR12795729 ┆ PRJNA668104 ┆ 2      ┆ pig_colon_412 ┆ … ┆ CON    ┆ 1   ┆ 5       ┆ 4.0          │
│ SRR12795793 ┆ PRJNA668104 ┆ 17     ┆ donor1        ┆ … ┆ DONOR1 ┆ 0   ┆ 0       ┆ 0.0          │
│ SRR12795792 ┆ PRJNA668104 ┆ 16     ┆ donor2        ┆ … ┆ DONOR2 ┆ 0   ┆ 0       ┆ 0.0          │
│ SRR12795790 ┆ PRJNA668104 ┆ 1      ┆ pig_colon_405 ┆ … ┆ FMT1   ┆ 0   ┆ 1       ┆ 1.0          │
│ SRR12795789 ┆ PRJNA668104 ┆ 2      ┆ pig_colon_408 ┆ … ┆ FMT1   ┆ 0   ┆ 1       ┆ 1.0          │
│ SRR12795784 ┆ PRJNA668104 ┆ 2      ┆ pig_colon_419 ┆ … ┆ FMT1   ┆ 1   ┆ 5       ┆ 2.333333     │
│ SRR12795783 ┆ PRJNA668104 ┆ 2      ┆ pig_colon_421 ┆ … ┆ FMT1   ┆ 0   ┆ 3       ┆ 1.666667     │
│ SRR12795782 ┆ PRJNA668104 ┆ 2      ┆ pig_colon_424 ┆ … ┆ FMT1   ┆ 0   ┆ 1       ┆ 1.0          │
│ SRR12795780 ┆ PRJNA668104 ┆ 2      ┆ pig_colon_430 ┆ … ┆ FMT1   ┆ 0   ┆ 2       ┆ 1.333333     │
│ SRR12795776 ┆ PRJNA668104 ┆ 4      ┆ pig_colon_407 ┆ … ┆ FMT2   ┆ 0   ┆ 2       ┆ 1.333333     │
│ SRR12795775 ┆ PRJNA668104 ┆ 2      ┆ pig_colon_410 ┆ … ┆ FMT2   ┆ 0   ┆ 2       ┆ 1.666667     │
│ SRR12795773 ┆ PRJNA668104 ┆ 3      ┆ pig_colon_413 ┆ … ┆ FMT2   ┆ 0   ┆ 1       ┆ 1.0          │
│ SRR12795771 ┆ PRJNA668104 ┆ 4      ┆ pig_colon_418 ┆ … ┆ FMT2   ┆ 0   ┆ 2       ┆ 1.666667     │
│ SRR12795770 ┆ PRJNA668104 ┆ 3      ┆ pig_colon_420 ┆ … ┆ FMT2   ┆ 0   ┆ 2       ┆ 1.333333     │
│ SRR12795746 ┆ PRJNA668104 ┆ 3      ┆ pig_colon_422 ┆ … ┆ FMT2   ┆ 0   ┆ 2       ┆ 1.333333     │
│ SRR12795745 ┆ PRJNA668104 ┆ 2      ┆ pig_colon_425 ┆ … ┆ FMT2   ┆ 0   ┆ 3       ┆ 1.666667     │
│ SRR12795741 ┆ PRJNA668104 ┆ 2      ┆ pig_colon_428 ┆ … ┆ FMT2   ┆ 0   ┆ 1       ┆ 1.0          │
│ SRR12795744 ┆ PRJNA668104 ┆ 2      ┆ pig_colon_431 ┆ … ┆ FMT2   ┆ 0   ┆ 1       ┆ 1.0          │
└─────────────┴─────────────┴────────┴───────────────┴───┴────────┴─────┴─────────┴──────────────┘

## Explore PRJNA807368 (berberine study)

[ENA link](https://www.ebi.ac.uk/ena/browser/view/PRJNA807368)

paper: https://www.frontiersin.org/journals/microbiology/articles/10.3389/fmicb.2022.862882/full

Summary of the below: of the 12 samples in the study, 4/6 of the Berberine suppl samples had < 10 core microbes, and none of the non-supplemented. All 6 berberine suppl samples had 10 core microbes or less, and only one control.

In [41]:
low_core_acc2.filter(pl.col('bioproject') == 'PRJNA807368')

shape: (4, 69)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ acc        ┆ bioproject ┆ n_core ┆ sample_na ┆ … ┆ bytes     ┆ run_file_ ┆ run_file_ ┆ primary_s │
│ ---        ┆ ---        ┆ ---    ┆ me        ┆   ┆ ---       ┆ create_da ┆ version   ┆ earch     │
│ str        ┆ str        ┆ u32    ┆ ---       ┆   ┆ str       ┆ te        ┆ ---       ┆ ---       │
│            ┆            ┆        ┆ str       ┆   ┆           ┆ ---       ┆ str       ┆ str       │
│            ┆            ┆        ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR1804890 ┆ PRJNA80736 ┆ 5      ┆ Berberine ┆ … ┆ 347442114 ┆ "2022-02- ┆ null      ┆ "25980738 │
│ 4          ┆ 8          ┆        ┆ 1         ┆   ┆ 5         ┆ 18T08:23: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1804890 ┆ PRJNA80736 ┆ 8      ┆ Berberine ┆ … ┆ 353623422 ┆ "2022-02- ┆ null      ┆ "25980739 │
│ 3          ┆ 8          ┆        ┆ 2         ┆   ┆ 0         ┆ 18T08:13: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1804890 ┆ PRJNA80736 ┆ 9      ┆ Berberine ┆ … ┆ 344807609 ┆ "2022-02- ┆ null      ┆ "25980740 │
│ 2          ┆ 8          ┆        ┆ 3         ┆   ┆ 5         ┆ 18T08:14: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
│ SRR1804890 ┆ PRJNA80736 ┆ 9      ┆ Berberine ┆ … ┆ 352673980 ┆ "2022-02- ┆ null      ┆ "25980741 │
│ 1          ┆ 8          ┆        ┆ 4         ┆   ┆ 2         ┆ 18T08:27: ┆           ┆ "         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 00.000Z"  ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [42]:
with(pl.Config(tbl_rows=-10)):
    print(metadata_df.filter(pl.col('bioproject') == 'PRJNA807368')['sample_name'].sort())

shape: (12,)
Series: 'sample_name' [str]
[
	"Berberine1"
	"Berberine2"
	"Berberine3"
	"Berberine4"
	"Berberine5"
	"Berberine6"
	"Control1"
	"Control2"
	"Control3"
	"Control4"
	"Control5"
	"Control6"
]

In [43]:
with pl.Config(tbl_rows=-1):
    print(by_acc
     .join(metadata_df, left_on='match_name', right_on='acc', how='inner')
     .filter(pl.col('bioproject') == 'PRJNA807368')
     .select(['n_core', 'match_name', 'sample_name'])
     .sort('n_core')
    )

shape: (12, 3)
┌────────┬─────────────┬─────────────┐
│ n_core ┆ match_name  ┆ sample_name │
│ ---    ┆ ---         ┆ ---         │
│ u32    ┆ str         ┆ str         │
╞════════╪═════════════╪═════════════╡
│ 5      ┆ SRR18048904 ┆ Berberine1  │
│ 8      ┆ SRR18048903 ┆ Berberine2  │
│ 9      ┆ SRR18048901 ┆ Berberine4  │
│ 9      ┆ SRR18048902 ┆ Berberine3  │
│ 10     ┆ SRR18048908 ┆ Control3    │
│ 10     ┆ SRR18048910 ┆ Berberine5  │
│ 10     ┆ SRR18048909 ┆ Berberine6  │
│ 11     ┆ SRR18048911 ┆ Control2    │
│ 13     ┆ SRR18048906 ┆ Control5    │
│ 14     ┆ SRR18048912 ┆ Control1    │
│ 14     ┆ SRR18048907 ┆ Control4    │
│ 17     ┆ SRR18048905 ┆ Control6    │
└────────┴─────────────┴─────────────┘