# Nanopore analysis (from the PRJEB88111 dataset)

data from [Metagenomics provides broad detection of pathogens, antimicrobial resistance, and virulence genes in pig diarrhoea and complement conventional methods](https://link.springer.com/article/10.1186/s42523-026-00577-2), Ivanova et al., 2026.

SRA entry: https://www.ncbi.nlm.nih.gov/sra/?term=PRJEB88111

In [1]:
import polars as pl
import matplotlib.pyplot as plt

## Read in run & sample metadata

In [2]:
expinfo_df = (
    pl.read_csv('../inputs.PRJEB88111.nanopore/experiment_info.PRJEB88111.csv')
    .filter(pl.col("Organism Name") == 'Sus scrofa')
)
expinfo_df.head(1)

shape: (1, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Experimen ┆ Experimen ┆ Organism  ┆ Instrumen ┆ … ┆ Library   ┆ Library   ┆ Library   ┆ Library  │
│ t         ┆ t Title   ┆ Name      ┆ t         ┆   ┆ Name      ┆ Strategy  ┆ Source    ┆ Selectio │
│ Accession ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ n        │
│ ---       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│ str       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ERX153304 ┆ Raw       ┆ Sus       ┆ PromethIO ┆ … ┆           ┆ WGS       ┆ METAGENOM ┆ RANDOM   │
│ 93        ┆ reads:    ┆ scrofa    ┆ N         ┆   ┆           ┆           ┆ IC        ┆          │
│           ┆ DTU_2024_ ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 1036881_1 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0…        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
# per https://link.springer.com/article/10.1186/s42523-026-00577-2, the LVK datasets are the diarrhea datasets.
xx = []
for row in expinfo_df.iter_rows(named=True):
    exp_acc = row["Experiment Accession"]

    is_lvk = 0
    title = row["Experiment Title"]
    if "LVK" in title:
        is_lvk = 1

    xx.append(dict(is_diarrhea=is_lvk, Experiment=exp_acc))

xx_df = pl.DataFrame(xx)
xx_df

shape: (59, 2)
┌─────────────┬─────────────┐
│ is_diarrhea ┆ Experiment  │
│ ---         ┆ ---         │
│ i64         ┆ str         │
╞═════════════╪═════════════╡
│ 1           ┆ ERX15330493 │
│ 1           ┆ ERX15330568 │
│ 1           ┆ ERX15332128 │
│ 1           ┆ ERX15333324 │
│ 1           ┆ ERX15330180 │
│ …           ┆ …           │
│ 1           ┆ ERX15305647 │
│ 1           ┆ ERX15305652 │
│ 1           ┆ ERX15305662 │
│ 1           ┆ ERX15305633 │
│ 1           ┆ ERX15305648 │
└─────────────┴─────────────┘

In [4]:
runinfo_df = (
    pl.read_csv('../inputs.PRJEB88111.nanopore/SraRunInfo.PRJEB88111.csv')
    .filter(pl.col("ScientificName") == 'Sus scrofa')
)
runinfo_df.head(1)

shape: (1, 47)
┌────────────┬────────────┬────────────┬─────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ Run        ┆ ReleaseDat ┆ LoadDate   ┆ spots   ┆ … ┆ dbgap_stu ┆ Consent ┆ RunHash   ┆ ReadHash  │
│ ---        ┆ e          ┆ ---        ┆ ---     ┆   ┆ dy_access ┆ ---     ┆ ---       ┆ ---       │
│ str        ┆ ---        ┆ str        ┆ i64     ┆   ┆ ion       ┆ str     ┆ str       ┆ str       │
│            ┆ str        ┆            ┆         ┆   ┆ ---       ┆         ┆           ┆           │
│            ┆            ┆            ┆         ┆   ┆ str       ┆         ┆           ┆           │
╞════════════╪════════════╪════════════╪═════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ ERR1593667 ┆ 2025-11-21 ┆ 2025-11-25 ┆ 5640279 ┆ … ┆ null      ┆ public  ┆ 58DD49D01 ┆ EF1972883 │
│ 6          ┆ 21:12:07   ┆ 01:08:24   ┆         ┆   ┆           ┆         ┆ 233D0BB22 ┆ 7C856F4CD │
│            ┆            ┆            ┆         ┆   ┆           ┆         ┆ 6B8858217 ┆ 0B157146C │
│            ┆            ┆            ┆         ┆   ┆           ┆         ┆ 137…      ┆ 8E2…      │
└────────────┴────────────┴────────────┴─────────┴───┴───────────┴─────────┴───────────┴───────────┘

In [5]:
join_df = (
    runinfo_df
    .join(xx_df, on="Experiment", how="inner")
    .select(["Run", "Model", "is_diarrhea", "bases"])
)
join_df['Model'].value_counts()

shape: (2, 2)
┌────────────┬───────┐
│ Model      ┆ count │
│ ---        ┆ ---   │
│ str        ┆ u32   │
╞════════════╪═══════╡
│ GridION    ┆ 27    │
│ PromethION ┆ 32    │
└────────────┴───────┘

In [6]:
# select just the PromethION since they are deeper
prjeb_df = join_df.filter(pl.col('Model') == 'PromethION')
prjeb_df.head(1)

shape: (1, 4)
┌─────────────┬────────────┬─────────────┬─────────────┐
│ Run         ┆ Model      ┆ is_diarrhea ┆ bases       │
│ ---         ┆ ---        ┆ ---         ┆ ---         │
│ str         ┆ str        ┆ i64         ┆ i64         │
╞═════════════╪════════════╪═════════════╪═════════════╡
│ ERR15934865 ┆ PromethION ┆ 1           ┆ 35068056814 │
└─────────────┴────────────┴─────────────┴─────────────┘

## Read in summary of mapping of nanopore to reference genomes

In [7]:
depth_df = (
    pl.read_csv('../outputs.PRJEB88111.nanopore/bams/*.x.all-core.depth.csv')
)
depth_df.head(1)

shape: (1, 7)
┌─────────────┬────────────┬───────┬──────┬──────────┬───────────┬───────────┐
│ metag       ┆ gene       ┆ len   ┆ hits ┆ breadth  ┆ depth_all ┆ depth_cov │
│ ---         ┆ ---        ┆ ---   ┆ ---  ┆ ---      ┆ ---       ┆ ---       │
│ str         ┆ str        ┆ i64   ┆ i64  ┆ f64      ┆ f64       ┆ f64       │
╞═════════════╪════════════╪═══════╪══════╪══════════╪═══════════╪═══════════╡
│ ERR15909852 ┆ FR882202.1 ┆ 72839 ┆ 5938 ┆ 0.081522 ┆ 0.088785  ┆ 1.089087  │
└─────────────┴────────────┴───────┴──────┴──────────┴───────────┴───────────┘

## Read in table connecting contigs to species

In [8]:
contigs_species_df = pl.read_csv('../outputs.PRJEB88111.nanopore/contigs_to_species.csv')
contigs_species_df.head(1)

shape: (1, 3)
┌────────────────┬─────────────────────────────────┬─────────────────┐
│ contig         ┆ species                         ┆ acc             │
│ ---            ┆ ---                             ┆ ---             │
│ str            ┆ str                             ┆ str             │
╞════════════════╪═════════════════════════════════╪═════════════════╡
│ UREV01000001.1 ┆ s__Cryptobacteroides sp9005469… ┆ GCA_900546925.1 │
└────────────────┴─────────────────────────────────┴─────────────────┘

## Combine depth and contigs to species!!

In [9]:
combo_df = (
    depth_df
    .join(contigs_species_df, left_on='gene', right_on='contig', how='inner')
    .with_columns(
        weighted_depth=(pl.col('len') * pl.col('depth_all')),
        weighted_breadth=(pl.col('len') * pl.col('breadth')),
    )
)
combo_df.head(1)

shape: (1, 11)
┌─────────────┬────────────┬───────┬──────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ metag       ┆ gene       ┆ len   ┆ hits ┆ … ┆ species     ┆ acc        ┆ weighted_d ┆ weighted_b │
│ ---         ┆ ---        ┆ ---   ┆ ---  ┆   ┆ ---         ┆ ---        ┆ epth       ┆ readth     │
│ str         ┆ str        ┆ i64   ┆ i64  ┆   ┆ str         ┆ str        ┆ ---        ┆ ---        │
│             ┆            ┆       ┆      ┆   ┆             ┆            ┆ f64        ┆ f64        │
╞═════════════╪════════════╪═══════╪══════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ ERR15909852 ┆ FR882202.1 ┆ 72839 ┆ 5938 ┆ … ┆ s__Cryptoba ┆ GCA_000434 ┆ 6467.0     ┆ 5938.0     │
│             ┆            ┆       ┆      ┆   ┆ cteroides   ┆ 935.1      ┆            ┆            │
│             ┆            ┆       ┆      ┆   ┆ sp0004349…  ┆            ┆            ┆            │
└─────────────┴────────────┴───────┴──────┴───┴─────────────┴────────────┴────────────┴────────────┘

## Summarize by metag/species

In [10]:
sum_df = combo_df.group_by(['metag', 'species']).agg(
    depth_all=pl.col('weighted_depth').sum() / pl.col('len').sum(),
    breadth=pl.col('weighted_breadth').sum() / pl.col('len').sum(),
).join(prjeb_df, left_on='metag', right_on='Run', how='inner')
sum_df.sort('breadth')

shape: (512, 7)
┌─────────────┬──────────────────┬─────────────┬──────────┬────────────┬─────────────┬─────────────┐
│ metag       ┆ species          ┆ depth_all   ┆ breadth  ┆ Model      ┆ is_diarrhea ┆ bases       │
│ ---         ┆ ---              ┆ ---         ┆ ---      ┆ ---        ┆ ---         ┆ ---         │
│ str         ┆ str              ┆ f64         ┆ f64      ┆ str        ┆ i64         ┆ i64         │
╞═════════════╪══════════════════╪═════════════╪══════════╪════════════╪═════════════╪═════════════╡
│ ERR15934505 ┆ s__Ornithospiroc ┆ 0.204572    ┆ 0.056841 ┆ PromethION ┆ 1           ┆ 7393986829  │
│             ┆ haeta sp022785…  ┆             ┆          ┆            ┆             ┆             │
│ ERR15934505 ┆ s__UBA2868       ┆ 2.94368     ┆ 0.192117 ┆ PromethION ┆ 1           ┆ 7393986829  │
│             ┆ sp004552595      ┆             ┆          ┆            ┆             ┆             │
│ ERR15934505 ┆ s__Cryptobactero ┆ 0.503539    ┆ 0.300202 ┆ PromethION ┆ 1           ┆ 7393986829  │
│             ┆ ides sp9005469…  ┆             ┆          ┆            ┆             ┆             │
│ ERR15939764 ┆ s__UBA2868       ┆ 1.812845    ┆ 0.328263 ┆ PromethION ┆ 1           ┆ 6640569258  │
│             ┆ sp004552595      ┆             ┆          ┆            ┆             ┆             │
│ ERR15934783 ┆ s__UBA2868       ┆ 18.441043   ┆ 0.330411 ┆ PromethION ┆ 0           ┆ 16653212647 │
│             ┆ sp004552595      ┆             ┆          ┆            ┆             ┆             │
│ …           ┆ …                ┆ …           ┆ …        ┆ …          ┆ …           ┆ …           │
│ ERR15935028 ┆ s__JAFBIX01      ┆ 137.764068  ┆ 0.992922 ┆ PromethION ┆ 1           ┆ 20643064873 │
│             ┆ sp021531895      ┆             ┆          ┆            ┆             ┆             │
│ ERR15934940 ┆ s__Bariatricus   ┆ 108.242687  ┆ 0.99321  ┆ PromethION ┆ 1           ┆ 31254201876 │
│             ┆ sp004560705      ┆             ┆          ┆            ┆             ┆             │
│ ERR15934725 ┆ s__Bariatricus   ┆ 102.132863  ┆ 0.993625 ┆ PromethION ┆ 1           ┆ 23038537820 │
│             ┆ sp004560705      ┆             ┆          ┆            ┆             ┆             │
│ ERR15934877 ┆ s__Lactobacillus ┆ 5257.163197 ┆ 0.994524 ┆ PromethION ┆ 1           ┆ 32257989526 │
│             ┆ amylovorus       ┆             ┆          ┆            ┆             ┆             │
│ ERR15938761 ┆ s__JAFBIX01      ┆ 245.597313  ┆ 0.995247 ┆ PromethION ┆ 1           ┆ 23065958954 │
│             ┆ sp021531895      ┆             ┆          ┆            ┆             ┆             │
└─────────────┴──────────────────┴─────────────┴──────────┴────────────┴─────────────┴─────────────┘

In [14]:
by_species = sum_df.group_by('species').agg(
    min_breadth=pl.col('breadth').min().round(3),
    med_breadth=pl.col('breadth').median().round(3),
    max_breadth=pl.col('breadth').max().round(3),
    min_depth=pl.col('depth_all').min().round(2),
    med_depth=pl.col('depth_all').median().round(1),
    max_depth=pl.col('depth_all').max().round(1),
)

In [45]:
by_species.sort('min_depth').style

GT(_tbl_data=shape: (16, 7)
┌────────────────────┬─────────────┬─────────────┬─────────────┬───────────┬───────────┬───────────┐
│ species            ┆ min_breadth ┆ med_breadth ┆ max_breadth ┆ min_depth ┆ med_depth ┆ max_depth │
│ ---                ┆ ---         ┆ ---         ┆ ---         ┆ ---       ┆ ---       ┆ ---       │
│ str                ┆ f64         ┆ f64         ┆ f64         ┆ f64       ┆ f64       ┆ f64       │
╞════════════════════╪═════════════╪═════════════╪═════════════╪═══════════╪═══════════╪═══════════╡
│ s__Ornithospirocha ┆ 0.057       ┆ 0.891       ┆ 0.978       ┆ 0.2       ┆ 5.0       ┆ 14.1      │
│ eta sp022785…      ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Cryptobacteroid ┆ 0.3         ┆ 0.977       ┆ 0.986       ┆ 0.5       ┆ 10.5      ┆ 67.9      │
│ es sp9005469…      ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Cryptobacteroid ┆ 0.35        ┆ 0.83        ┆ 0.887       ┆ 0.56      ┆ 6.1       ┆ 30.9      │
│ es sp0004349…      ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Cryptobacteroid ┆ 0.39        ┆ 0.894       ┆ 0.935       ┆ 0.64      ┆ 6.5       ┆ 18.3      │
│ es sp0004326…      ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Cryptobacteroid ┆ 0.527       ┆ 0.981       ┆ 0.991       ┆ 1.13      ┆ 16.1      ┆ 61.5      │
│ es sp0340892…      ┆             ┆             ┆             ┆           ┆           ┆           │
│ …                  ┆ …           ┆ …           ┆ …           ┆ …         ┆ …         ┆ …         │
│ s__Floccifex porci ┆ 0.41        ┆ 0.937       ┆ 0.97        ┆ 4.77      ┆ 27.1      ┆ 67.1      │
│ s__Prevotella      ┆ 0.504       ┆ 0.899       ┆ 0.951       ┆ 4.87      ┆ 40.6      ┆ 613.9     │
│ sp000434975        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Bariatricus     ┆ 0.917       ┆ 0.98        ┆ 0.994       ┆ 9.02      ┆ 48.6      ┆ 193.9     │
│ sp004560705        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__JAFBIX01        ┆ 0.708       ┆ 0.955       ┆ 0.995       ┆ 11.53     ┆ 70.1      ┆ 256.1     │
│ sp021531895        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Lactobacillus   ┆ 0.921       ┆ 0.979       ┆ 0.995       ┆ 38.31     ┆ 1379.2    ┆ 5257.2    │
│ amylovorus         ┆             ┆             ┆             ┆           ┆           ┆           │

In [51]:
sum_df['breadth'].describe()

shape: (9, 2)
┌────────────┬──────────┐
│ statistic  ┆ value    │
│ ---        ┆ ---      │
│ str        ┆ f64      │
╞════════════╪══════════╡
│ count      ┆ 512.0    │
│ null_count ┆ 0.0      │
│ mean       ┆ 0.883145 │
│ std        ┆ 0.153136 │
│ min        ┆ 0.056841 │
│ 25%        ┆ 0.861999 │
│ 50%        ┆ 0.943947 │
│ 75%        ┆ 0.975082 │
│ max        ┆ 0.995247 │
└────────────┴──────────┘

In [52]:
len(sum_df)

512

In [56]:
len(sum_df.filter(pl.col('breadth') >= .5)) / 512

0.94921875

In [57]:
sum_df['depth_all'].describe()

shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ value       │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 512.0       │
│ null_count ┆ 0.0         │
│ mean       ┆ 130.345946  │
│ std        ┆ 478.414332  │
│ min        ┆ 0.204572    │
│ 25%        ┆ 8.784293    │
│ 50%        ┆ 20.429855   │
│ 75%        ┆ 48.453538   │
│ max        ┆ 5257.163197 │
└────────────┴─────────────┘

In [58]:
len(sum_df.filter(pl.col('depth_all') >= 1)) / 512

0.990234375

In [50]:
(sum_df.sort('breadth')
 .select(['metag', 'species', 'depth_all', 'breadth'])
 .style.fmt_number(columns=["depth_all", "breadth"], decimals=2)
)

GT(_tbl_data=shape: (512, 4)
┌─────────────┬─────────────────────────────────┬─────────────┬──────────┐
│ metag       ┆ species                         ┆ depth_all   ┆ breadth  │
│ ---         ┆ ---                             ┆ ---         ┆ ---      │
│ str         ┆ str                             ┆ f64         ┆ f64      │
╞═════════════╪═════════════════════════════════╪═════════════╪══════════╡
│ ERR15934505 ┆ s__Ornithospirochaeta sp022785… ┆ 0.204572    ┆ 0.056841 │
│ ERR15934505 ┆ s__UBA2868 sp004552595          ┆ 2.94368     ┆ 0.192117 │
│ ERR15934505 ┆ s__Cryptobacteroides sp9005469… ┆ 0.503539    ┆ 0.300202 │
│ ERR15939764 ┆ s__UBA2868 sp004552595          ┆ 1.812845    ┆ 0.328263 │
│ ERR15934783 ┆ s__UBA2868 sp004552595          ┆ 18.441043   ┆ 0.330411 │
│ …           ┆ …                               ┆ …           ┆ …        │
│ ERR15935028 ┆ s__JAFBIX01 sp021531895         ┆ 137.764068  ┆ 0.992922 │
│ ERR15934940 ┆ s__Bariatricus sp004560705      ┆ 108.242687  ┆ 0.99321  │
│ ERR15934725 ┆ s__Bariatricus sp004560705      ┆ 102.132863  ┆ 0.993625 │
│ ERR15934877 ┆ s__Lactobacillus amylovorus     ┆ 5257.163197 ┆ 0.994524 │
│ ERR15938761 ┆ s__JAFBIX01 sp021531895         ┆ 245.597313  ┆ 0.995247 │
└─────────────┴─────────────────────────────────┴─────────────┴──────────┘, _body=<great_tables._gt_data.Body object at 0x751b47c71c40>, _boxhead=Boxhead([ColInfo(var='metag', type=<ColInfoTypeEnum.default: 1>, column_label='metag', column_align='left', column_width=None), ColInfo(var='species', type=<ColInfoTypeEnum.default: 1>, column_label='species', column_align='left', column_width=None), ColInfo(var='depth_all', type=<ColInfoTypeEnum.default: 1>, column_label='depth_all', column_align='right', column_width=None), ColInfo(var='breadth', type=<ColInfoTypeEnum.default: 1>, column_label='breadth', column_align='right', column_width=None)]), _stub=<great_tables._gt_data.Stub object at 0x751b3c937ce0>, _spanners=Spanners([]), _heading=Heading(title=None, subtitle=None, preheader=None), _stubhead=None, _summary_rows=<great_tables._gt_data.SummaryRows object at 0x751b47c73350>, _summary_rows_grand=<great_tables._gt_data.SummaryRows object at 0x751b47c73860>, _source_notes=[], _footnotes=[], _styles=[], _locale=<great_tables._gt_data.Locale object at 0x751b47c73410>, _formats=[<great_tables._gt_data.FormatInfo object at 0x751b47c73f80>], _substitutions=[], _col_merge=[], _transforms=[], _options=Options(table_id=OptionsInfo(scss=False, category='table', type='value', value=None), table_caption=OptionsInfo(scss=False, category='table', type='value', value=None), table_width=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_layout=OptionsInfo(scss=True, category='table', type='value', value='fixed'), table_margin_left=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_margin_right=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_background_color=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_additional_css=OptionsInfo(scss=False, category='table', type='values', value=[]), table_font_names=OptionsInfo(scss=False, category='table', type='values', value=['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Helvetica Neue', 'Fira Sans', 'Droid Sans', 'Arial', 'sans-serif']), table_font_size=OptionsInfo(scss=True, category='table', type='px', value='16px'), table_font_weight=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_style=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_color=OptionsInfo(scss=True, category='table', type='value', value='#333333'), table_font_color_light=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_border_top_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_top_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_top_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_top_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_right_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_right_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_right_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), table_border_bottom_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_bottom_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_bottom_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_bottom_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_left_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_left_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_left_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), heading_background_color=OptionsInfo(scss=True, category='heading', type='value', value=None), heading_align=OptionsInfo(scss=True, category='heading', type='value', value='center'), heading_title_font_size=OptionsInfo(scss=True, category='heading', type='px', value='125%'), heading_title_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_subtitle_font_size=OptionsInfo(scss=True, category='heading', type='px', value='85%'), heading_subtitle_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_padding=OptionsInfo(scss=True, category='heading', type='px', value='4px'), heading_padding_horizontal=OptionsInfo(scss=True, category='heading', type='px', value='5px'), heading_border_bottom_style=OptionsInfo(scss=True, category='heading', type='value', value='solid'), heading_border_bottom_width=OptionsInfo(scss=True, category='heading', type='px', value='2px'), heading_border_bottom_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), heading_border_lr_style=OptionsInfo(scss=True, category='heading', type='value', value='none'), heading_border_lr_width=OptionsInfo(scss=True, category='heading', type='px', value='1px'), heading_border_lr_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), column_labels_background_color=OptionsInfo(scss=True, category='column_labels', type='value', value=None), column_labels_font_size=OptionsInfo(scss=True, category='column_labels', type='px', value='100%'), column_labels_font_weight=OptionsInfo(scss=True, category='column_labels', type='value', value='normal'), column_labels_text_transform=OptionsInfo(scss=True, category='column_labels', type='value', value='inherit'), column_labels_padding=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_padding_horizontal=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), column_labels_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), column_labels_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), column_labels_border_top_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_top_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_top_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_bottom_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_bottom_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_bottom_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_lr_style=OptionsInfo(scss=True, category='column_labels', type='value', value='none'), column_labels_border_lr_width=OptionsInfo(scss=True, category='column_labels', type='px', value='1px'), column_labels_border_lr_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_hidden=OptionsInfo(scss=False, category='column_labels', type='boolean', value=False), row_group_background_color=OptionsInfo(scss=True, category='row_group', type='value', value=None), row_group_font_size=OptionsInfo(scss=True, category='row_group', type='px', value='100%'), row_group_font_weight=OptionsInfo(scss=True, category='row_group', type='value', value='initial'), row_group_text_transform=OptionsInfo(scss=True, category='row_group', type='value', value='inherit'), row_group_padding=OptionsInfo(scss=True, category='row_group', type='px', value='8px'), row_group_padding_horizontal=OptionsInfo(scss=True, category='row_group', type='px', value='5px'), row_group_border_top_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_top_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_top_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_right_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_right_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_right_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_bottom_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_bottom_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_bottom_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_left_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_left_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_left_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_as_column=OptionsInfo(scss=False, category='row_group', type='boolean', value=False), table_body_hlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_hlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_hlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), table_body_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_top_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_top_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_top_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_bottom_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_bottom_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_bottom_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), data_row_padding=OptionsInfo(scss=True, category='data_row', type='px', value='8px'), data_row_padding_horizontal=OptionsInfo(scss=True, category='data_row', type='px', value='5px'), stub_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), stub_indent_length=OptionsInfo(scss=True, category='stub', type='px', value='5px'), stub_row_group_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_row_group_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_row_group_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_row_group_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_row_group_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_row_group_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_row_group_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), summary_row_padding=OptionsInfo(scss=True, category='summary_row', type='px', value='8px'), summary_row_padding_horizontal=OptionsInfo(scss=True, category='summary_row', type='px', value='5px'), summary_row_background_color=OptionsInfo(scss=True, category='summary_row', type='value', value=None), summary_row_text_transform=OptionsInfo(scss=True, category='summary_row', type='value', value='inherit'), summary_row_border_style=OptionsInfo(scss=True, category='summary_row', type='value', value='solid'), summary_row_border_width=OptionsInfo(scss=True, category='summary_row', type='px', value='2px'), summary_row_border_color=OptionsInfo(scss=True, category='summary_row', type='value', value='#D3D3D3'), grand_summary_row_padding=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='8px'), grand_summary_row_padding_horizontal=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='5px'), grand_summary_row_background_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value=None), grand_summary_row_text_transform=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='inherit'), grand_summary_row_border_style=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='double'), grand_summary_row_border_width=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='6px'), grand_summary_row_border_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='#D3D3D3'), footnotes_marks=OptionsInfo(scss=False, category='footnotes', type='values', value='numbers'), source_notes_padding=OptionsInfo(scss=True, category='source_notes', type='px', value='4px'), source_notes_padding_horizontal=OptionsInfo(scss=True, category='source_notes', type='px', value='5px'), source_notes_background_color=OptionsInfo(scss=True, category='source_notes', type='value', value=None), source_notes_font_size=OptionsInfo(scss=True, category='source_notes', type='px', value='90%'), source_notes_border_bottom_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_bottom_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_bottom_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_border_lr_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_lr_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_lr_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_multiline=OptionsInfo(scss=False, category='source_notes', type='boolean', value=True), source_notes_sep=OptionsInfo(scss=False, category='source_notes', type='value', value=' '), row_striping_background_color=OptionsInfo(scss=True, category='row', type='value', value='#F4F4F4'), row_striping_include_stub=OptionsInfo(scss=False, category='row', type='boolean', value=False), row_striping_include_table_body=OptionsInfo(scss=False, category='row', type='boolean', value=False), container_width=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_height=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_padding_x=OptionsInfo(scss=False, category='container', type='px', value='0px'), container_padding_y=OptionsInfo(scss=False, category='container', type='px', value='10px'), container_overflow_x=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), container_overflow_y=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), quarto_disable_processing=OptionsInfo(scss=False, category='quarto', type='logical', value=False), quarto_use_bootstrap=OptionsInfo(scss=False, category='quarto', type='logical', value=False), ihtml_active=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_pagination=OptionsInfo(scss=False, category='ihtml', type='boolean', value=True), ihtml_use_pagination_info=OptionsInfo(scss=False, category='ihtml', type='boolean', value=True), ihtml_use_sorting=OptionsInfo(scss=False, category='ihtml', type='boolean', value=True), ihtml_use_search=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_filters=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_resizers=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_highlight=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_compact_mode=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_use_text_wrapping=OptionsInfo(scss=False, category='ihtml', type='boolean', value=True), ihtml_use_page_size_select=OptionsInfo(scss=False, category='ihtml', type='boolean', value=False), ihtml_page_size_default=OptionsInfo(scss=False, category='ihtml', type='value', value=10), ihtml_page_size_values=OptionsInfo(scss=False, category='ihtml', type='values', value=[10, 25, 50, 100]), ihtml_pagination_type=OptionsInfo(scss=False, category='ihtml', type='value', value='numbers'), ihtml_height=OptionsInfo(scss=False, category='ihtml', type='value', value='auto'), ihtml_selection_mode=OptionsInfo(scss=False, category='ihtml', type='value', value=None)), _google_font_imports=GoogleFontImports(imports=frozenset()), _has_built=False)

In [44]:
by_species_healthy = (
    sum_df
    .filter(pl.col('is_diarrhea') == 0)
    .group_by('species').agg(
        min_breadth=pl.col('breadth').min().round(3),
        med_breadth=pl.col('breadth').median().round(3),
        max_breadth=pl.col('breadth').max().round(3),
        min_depth=pl.col('depth_all').min().round(2),
        med_depth=pl.col('depth_all').median().round(1),
        max_depth=pl.col('depth_all').max().round(1),
    )
)
by_species_healthy.sort('min_depth').style

GT(_tbl_data=shape: (16, 7)
┌────────────────────┬─────────────┬─────────────┬─────────────┬───────────┬───────────┬───────────┐
│ species            ┆ min_breadth ┆ med_breadth ┆ max_breadth ┆ min_depth ┆ med_depth ┆ max_depth │
│ ---                ┆ ---         ┆ ---         ┆ ---         ┆ ---       ┆ ---       ┆ ---       │
│ str                ┆ f64         ┆ f64         ┆ f64         ┆ f64       ┆ f64       ┆ f64       │
╞════════════════════╪═════════════╪═════════════╪═════════════╪═══════════╪═══════════╪═══════════╡
│ s__Ornithospirocha ┆ 0.645       ┆ 0.938       ┆ 0.977       ┆ 4.66      ┆ 7.4       ┆ 14.1      │
│ eta sp022785…      ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Colivicinus     ┆ 0.964       ┆ 0.969       ┆ 0.983       ┆ 8.62      ┆ 13.9      ┆ 47.2      │
│ sp002299675        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Cryptobacteroid ┆ 0.906       ┆ 0.924       ┆ 0.927       ┆ 10.74     ┆ 17.4      ┆ 18.3      │
│ es sp0004326…      ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Fimisoma        ┆ 0.731       ┆ 0.927       ┆ 0.953       ┆ 11.3      ┆ 31.9      ┆ 51.6      │
│ sp002320005        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Floccifex porci ┆ 0.45        ┆ 0.59        ┆ 0.923       ┆ 11.98     ┆ 20.2      ┆ 40.5      │
│ …                  ┆ …           ┆ …           ┆ …           ┆ …         ┆ …         ┆ …         │
│ s__Bariatricus     ┆ 0.941       ┆ 0.971       ┆ 0.991       ┆ 39.68     ┆ 78.9      ┆ 193.9     │
│ sp004560705        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__JAFBIX01        ┆ 0.714       ┆ 0.785       ┆ 0.971       ┆ 50.8      ┆ 93.7      ┆ 226.7     │
│ sp021531895        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Prevotella      ┆ 0.665       ┆ 0.977       ┆ 0.98        ┆ 113.94    ┆ 161.0     ┆ 330.3     │
│ sp002251295        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Sodaliphilus    ┆ 0.974       ┆ 0.976       ┆ 0.978       ┆ 126.45    ┆ 204.0     ┆ 311.4     │
│ sp004557565        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Prevotella      ┆ 0.939       ┆ 0.948       ┆ 0.951       ┆ 317.87    ┆ 438.1     ┆ 613.9     │
│ sp000434975        ┆             ┆             ┆             ┆           ┆           ┆           │

In [19]:
by_species_diarrhea = (
    sum_df
    .filter(pl.col('is_diarrhea') == 1)
    .group_by('species').agg(
        min_breadth=pl.col('breadth').min().round(3),
        med_breadth=pl.col('breadth').median().round(3),
        max_breadth=pl.col('breadth').max().round(3),
        min_depth=pl.col('depth_all').min().round(2),
        med_depth=pl.col('depth_all').median().round(1),
        max_depth=pl.col('depth_all').max().round(1),
    )
)
by_species_diarrhea.sort('min_depth').style

GT(_tbl_data=shape: (16, 7)
┌────────────────────┬─────────────┬─────────────┬─────────────┬───────────┬───────────┬───────────┐
│ species            ┆ min_breadth ┆ med_breadth ┆ max_breadth ┆ min_depth ┆ med_depth ┆ max_depth │
│ ---                ┆ ---         ┆ ---         ┆ ---         ┆ ---       ┆ ---       ┆ ---       │
│ str                ┆ f64         ┆ f64         ┆ f64         ┆ f64       ┆ f64       ┆ f64       │
╞════════════════════╪═════════════╪═════════════╪═════════════╪═══════════╪═══════════╪═══════════╡
│ s__Ornithospirocha ┆ 0.057       ┆ 0.864       ┆ 0.978       ┆ 0.2       ┆ 3.8       ┆ 10.4      │
│ eta sp022785…      ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Cryptobacteroid ┆ 0.3         ┆ 0.97        ┆ 0.985       ┆ 0.5       ┆ 9.4       ┆ 19.6      │
│ es sp9005469…      ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Cryptobacteroid ┆ 0.35        ┆ 0.819       ┆ 0.886       ┆ 0.56      ┆ 5.3       ┆ 12.6      │
│ es sp0004349…      ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Cryptobacteroid ┆ 0.39        ┆ 0.889       ┆ 0.935       ┆ 0.64      ┆ 5.9       ┆ 16.6      │
│ es sp0004326…      ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Cryptobacteroid ┆ 0.527       ┆ 0.973       ┆ 0.991       ┆ 1.13      ┆ 13.1      ┆ 35.9      │
│ es sp0340892…      ┆             ┆             ┆             ┆           ┆           ┆           │
│ …                  ┆ …           ┆ …           ┆ …           ┆ …         ┆ …         ┆ …         │
│ s__Floccifex porci ┆ 0.41        ┆ 0.944       ┆ 0.97        ┆ 4.77      ┆ 28.2      ┆ 67.1      │
│ s__Prevotella      ┆ 0.504       ┆ 0.886       ┆ 0.934       ┆ 4.87      ┆ 32.0      ┆ 79.8      │
│ sp000434975        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Bariatricus     ┆ 0.917       ┆ 0.983       ┆ 0.994       ┆ 9.02      ┆ 45.4      ┆ 157.1     │
│ sp004560705        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__JAFBIX01        ┆ 0.708       ┆ 0.963       ┆ 0.995       ┆ 11.53     ┆ 58.4      ┆ 256.1     │
│ sp021531895        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Lactobacillus   ┆ 0.929       ┆ 0.979       ┆ 0.995       ┆ 117.92    ┆ 1510.9    ┆ 5257.2    │
│ amylovorus         ┆             ┆             ┆             ┆           ┆           ┆           │

In [20]:
combo_df.head(1)

shape: (1, 11)
┌─────────────┬────────────┬───────┬──────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ metag       ┆ gene       ┆ len   ┆ hits ┆ … ┆ species     ┆ acc        ┆ weighted_d ┆ weighted_b │
│ ---         ┆ ---        ┆ ---   ┆ ---  ┆   ┆ ---         ┆ ---        ┆ epth       ┆ readth     │
│ str         ┆ str        ┆ i64   ┆ i64  ┆   ┆ str         ┆ str        ┆ ---        ┆ ---        │
│             ┆            ┆       ┆      ┆   ┆             ┆            ┆ f64        ┆ f64        │
╞═════════════╪════════════╪═══════╪══════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ ERR15909852 ┆ FR882202.1 ┆ 72839 ┆ 5938 ┆ … ┆ s__Cryptoba ┆ GCA_000434 ┆ 6467.0     ┆ 5938.0     │
│             ┆            ┆       ┆      ┆   ┆ cteroides   ┆ 935.1      ┆            ┆            │
│             ┆            ┆       ┆      ┆   ┆ sp0004349…  ┆            ┆            ┆            │
└─────────────┴────────────┴───────┴──────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [26]:
combo_df

shape: (167_616, 11)
┌─────────────┬────────────┬───────┬───────┬───┬────────────┬────────────┬────────────┬────────────┐
│ metag       ┆ gene       ┆ len   ┆ hits  ┆ … ┆ species    ┆ acc        ┆ weighted_d ┆ weighted_b │
│ ---         ┆ ---        ┆ ---   ┆ ---   ┆   ┆ ---        ┆ ---        ┆ epth       ┆ readth     │
│ str         ┆ str        ┆ i64   ┆ i64   ┆   ┆ str        ┆ str        ┆ ---        ┆ ---        │
│             ┆            ┆       ┆       ┆   ┆            ┆            ┆ f64        ┆ f64        │
╞═════════════╪════════════╪═══════╪═══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ ERR15909852 ┆ FR882202.1 ┆ 72839 ┆ 5938  ┆ … ┆ s__Cryptob ┆ GCA_000434 ┆ 6467.0     ┆ 5938.0     │
│             ┆            ┆       ┆       ┆   ┆ acteroides ┆ 935.1      ┆            ┆            │
│             ┆            ┆       ┆       ┆   ┆ sp0004349… ┆            ┆            ┆            │
│ ERR15909852 ┆ SFNX010001 ┆ 4530  ┆ 0     ┆ … ┆ s__UBA2868 ┆ GCA_004552 ┆ 0.0        ┆ 0.0        │
│             ┆ 31.1       ┆       ┆       ┆   ┆ sp00455259 ┆ 595.1      ┆            ┆            │
│             ┆            ┆       ┆       ┆   ┆ 5          ┆            ┆            ┆            │
│ ERR15909852 ┆ NZ_JAFBIX0 ┆ 46446 ┆ 8035  ┆ … ┆ s__JAFBIX0 ┆ GCF_021531 ┆ 19334.0    ┆ 8035.0     │
│             ┆ 10000025.1 ┆       ┆       ┆   ┆ 1 sp021531 ┆ 895.1      ┆            ┆            │
│             ┆            ┆       ┆       ┆   ┆ 895        ┆            ┆            ┆            │
│ ERR15909852 ┆ JALFRH0100 ┆ 9875  ┆ 105   ┆ … ┆ s__Ornitho ┆ GCA_022785 ┆ 315.0      ┆ 105.0      │
│             ┆ 00010.1    ┆       ┆       ┆   ┆ spirochaet ┆ 155.1      ┆            ┆            │
│             ┆            ┆       ┆       ┆   ┆ a          ┆            ┆            ┆            │
│             ┆            ┆       ┆       ┆   ┆ sp022785…  ┆            ┆            ┆            │
│ ERR15909852 ┆ JALFNN0100 ┆ 63285 ┆ 24763 ┆ … ┆ s__Bariatr ┆ GCA_022774 ┆ 35763.0    ┆ 24763.0    │
│             ┆ 00087.1    ┆       ┆       ┆   ┆ icus sp004 ┆ 325.1      ┆            ┆            │
│             ┆            ┆       ┆       ┆   ┆ 560705     ┆            ┆            ┆            │
│ …           ┆ …          ┆ …     ┆ …     ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ ERR15942255 ┆ SFNX010001 ┆ 3218  ┆ 0     ┆ … ┆ s__UBA2868 ┆ GCA_004552 ┆ 0.0        ┆ 0.0        │
│             ┆ 82.1       ┆       ┆       ┆   ┆ sp00455259 ┆ 595.1      ┆            ┆            │
│             ┆            ┆       ┆       ┆   ┆ 5          ┆            ┆            ┆            │
│ ERR15942255 ┆ JALFNN0100 ┆ 4012  ┆ 0     ┆ … ┆ s__Bariatr ┆ GCA_022774 ┆ 0.0        ┆ 0.0        │
│             ┆ 00085.1    ┆       ┆       ┆   ┆ icus sp004 ┆ 325.1      ┆            ┆            │
│             ┆            ┆       ┆       ┆   ┆ 560705     ┆            ┆            ┆            │
│ ERR15942255 ┆ SFNX010001 ┆ 3818  ┆ 0     ┆ … ┆ s__UBA2868 ┆ GCA_004552 ┆ 0.0        ┆ 0.0        │
│             ┆ 39.1       ┆       ┆       ┆   ┆ sp00455259 ┆ 595.1      ┆            ┆            │
│             ┆            ┆       ┆       ┆   ┆ 5          ┆            ┆            ┆            │
│ ERR15942255 ┆ SFNX010000 ┆ 21689 ┆ 0     ┆ … ┆ s__UBA2868 ┆ GCA_004552 ┆ 0.0        ┆ 0.0        │
│             ┆ 24.1       ┆       ┆       ┆   ┆ sp00455259 ┆ 595.1      ┆            ┆            │
│             ┆            ┆       ┆       ┆   ┆ 5          ┆            ┆            ┆            │
│ ERR15942255 ┆ JALFNN0100 ┆ 18212 ┆ 0     ┆ … ┆ s__Bariatr ┆ GCA_022774 ┆ 0.0        ┆ 0.0        │
│             ┆ 00079.1    ┆       ┆       ┆   ┆ icus sp004 ┆ 325.1      ┆            ┆            │
│             ┆            ┆       ┆       ┆   ┆ 560705     ┆            ┆            ┆            │
└─────────────┴────────────┴───────┴───────┴───┴────────────┴────────────┴────────────┴────────────┘

In [35]:
xx = []

for species in combo_df['species'].unique():
    xx_df = combo_df.filter(pl.col('species') == species)
    xx_df = xx_df.join(prjeb_df, left_on='metag', right_on='Run', how='inner')
    healthy_df = xx_df.filter(pl.col('is_diarrhea') == 0)
    diarrhea_df = xx_df.filter(pl.col('is_diarrhea') == 1)

    healthy_mean = healthy_df['depth_all'].mean()
    healthy_std = healthy_df['depth_all'].std()

    diarrhea_mean = diarrhea_df['depth_all'].mean()
    diarrhea_std = diarrhea_df['depth_all'].std()

    print(f"{healthy_mean:.1f} +/- {healthy_std:.1f} vs {diarrhea_mean:.1f} +/- {diarrhea_std:.1f} - {species}")

46.2 +/- 17.2 vs 9.3 +/- 5.3 - s__Cryptobacteroides sp900546925
286.5 +/- 1066.0 vs 152.3 +/- 525.8 - s__JAFBIX01 sp021531895
613.5 +/- 2403.5 vs 79.3 +/- 297.2 - s__Prevotella sp002251295
16.6 +/- 11.4 vs 5.9 +/- 4.4 - s__Cryptobacteroides sp000432655
233.9 +/- 354.2 vs 69.3 +/- 208.7 - s__Sodaliphilus sp004557565
47.9 +/- 20.4 vs 14.3 +/- 10.6 - s__Cryptobacteroides sp034089285
45.8 +/- 184.2 vs 57.5 +/- 215.1 - s__Floccifex porci
21.6 +/- 22.0 vs 17.1 +/- 21.3 - s__Colivicinus sp002299675
34.3 +/- 81.7 vs 24.3 +/- 64.2 - s__Fimisoma sp002320005
1122.2 +/- 1322.4 vs 1605.2 +/- 1260.2 - s__Lactobacillus amylovorus
7.4 +/- 14.8 vs 4.1 +/- 5.7 - s__Ornithospirochaeta sp022785155
83.5 +/- 362.3 vs 84.8 +/- 393.2 - s__Mogibacterium_A kristiansenii
46.7 +/- 146.4 vs 19.4 +/- 114.5 - s__UBA2868 sp004552595
405.5 +/- 824.1 vs 35.2 +/- 105.4 - s__Prevotella sp000434975
20.8 +/- 24.8 vs 5.8 +/- 8.6 - s__Cryptobacteroides sp000434935
90.2 +/- 116.5 vs 53.1 +/- 63.4 - s__Bariatricus sp004560705