# Nanopore analysis (from the PRJEB88111 dataset)

In [1]:
import polars as pl
import matplotlib.pyplot as plt

## Read in summary of mapping of nanopore to reference genomes

In [2]:
depth_df = (
    pl.read_csv('../outputs.PRJEB88111.nanopore/bams/*.x.all-core.depth.csv')
)
depth_df.head(1)

shape: (1, 7)
┌─────────────┬────────────┬───────┬──────┬──────────┬───────────┬───────────┐
│ metag       ┆ gene       ┆ len   ┆ hits ┆ breadth  ┆ depth_all ┆ depth_cov │
│ ---         ┆ ---        ┆ ---   ┆ ---  ┆ ---      ┆ ---       ┆ ---       │
│ str         ┆ str        ┆ i64   ┆ i64  ┆ f64      ┆ f64       ┆ f64       │
╞═════════════╪════════════╪═══════╪══════╪══════════╪═══════════╪═══════════╡
│ ERR15909852 ┆ FR882202.1 ┆ 72839 ┆ 5938 ┆ 0.081522 ┆ 0.088785  ┆ 1.089087  │
└─────────────┴────────────┴───────┴──────┴──────────┴───────────┴───────────┘

## Read in table connecting contigs to species

In [3]:
contigs_species_df = pl.read_csv('../outputs.PRJEB88111.nanopore/contigs_to_species.csv')
contigs_species_df.head(1)

shape: (1, 3)
┌────────────────┬─────────────────────────────────┬─────────────────┐
│ contig         ┆ species                         ┆ acc             │
│ ---            ┆ ---                             ┆ ---             │
│ str            ┆ str                             ┆ str             │
╞════════════════╪═════════════════════════════════╪═════════════════╡
│ UREV01000001.1 ┆ s__Cryptobacteroides sp9005469… ┆ GCA_900546925.1 │
└────────────────┴─────────────────────────────────┴─────────────────┘

## Combine!

In [4]:
join_df = (
    depth_df
    .join(contigs_species_df, left_on='gene', right_on='contig', how='inner')
    .with_columns(
        weighted_depth=(pl.col('len') * pl.col('depth_all')),
        weighted_breadth=(pl.col('len') * pl.col('breadth')),
    )
)
join_df.head(1)

shape: (1, 11)
┌─────────────┬────────────┬───────┬──────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ metag       ┆ gene       ┆ len   ┆ hits ┆ … ┆ species     ┆ acc        ┆ weighted_d ┆ weighted_b │
│ ---         ┆ ---        ┆ ---   ┆ ---  ┆   ┆ ---         ┆ ---        ┆ epth       ┆ readth     │
│ str         ┆ str        ┆ i64   ┆ i64  ┆   ┆ str         ┆ str        ┆ ---        ┆ ---        │
│             ┆            ┆       ┆      ┆   ┆             ┆            ┆ f64        ┆ f64        │
╞═════════════╪════════════╪═══════╪══════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ ERR15909852 ┆ FR882202.1 ┆ 72839 ┆ 5938 ┆ … ┆ s__Cryptoba ┆ GCA_000434 ┆ 6467.0     ┆ 5938.0     │
│             ┆            ┆       ┆      ┆   ┆ cteroides   ┆ 935.1      ┆            ┆            │
│             ┆            ┆       ┆      ┆   ┆ sp0004349…  ┆            ┆            ┆            │
└─────────────┴────────────┴───────┴──────┴───┴─────────────┴────────────┴────────────┴────────────┘

## Summarize by metag/species

In [5]:
sum_df = join_df.group_by(['metag', 'species']).agg(
    depth_all=pl.col('weighted_depth').sum() / pl.col('len').sum(),
    breadth=pl.col('weighted_breadth').sum() / pl.col('len').sum(),
)
sum_df.sort('breadth')

shape: (1_728, 4)
┌─────────────┬─────────────────────────────────┬─────────────┬──────────┐
│ metag       ┆ species                         ┆ depth_all   ┆ breadth  │
│ ---         ┆ ---                             ┆ ---         ┆ ---      │
│ str         ┆ str                             ┆ f64         ┆ f64      │
╞═════════════╪═════════════════════════════════╪═════════════╪══════════╡
│ ERR15942132 ┆ s__Cryptobacteroides sp9005469… ┆ 0.0         ┆ 0.0      │
│ ERR15941754 ┆ s__Cryptobacteroides sp9005469… ┆ 0.0         ┆ 0.0      │
│ ERR15942135 ┆ s__Cryptobacteroides sp0004326… ┆ 0.0         ┆ 0.0      │
│ ERR15942245 ┆ s__Cryptobacteroides sp9005469… ┆ 0.0         ┆ 0.0      │
│ ERR15942238 ┆ s__Cryptobacteroides sp0004326… ┆ 0.0         ┆ 0.0      │
│ …           ┆ …                               ┆ …           ┆ …        │
│ ERR15935028 ┆ s__JAFBIX01 sp021531895         ┆ 137.764068  ┆ 0.992922 │
│ ERR15934940 ┆ s__Bariatricus sp004560705      ┆ 108.242687  ┆ 0.99321  │
│ ERR15934725 ┆ s__Bariatricus sp004560705      ┆ 102.132863  ┆ 0.993625 │
│ ERR15934877 ┆ s__Lactobacillus amylovorus     ┆ 5257.163197 ┆ 0.994524 │
│ ERR15938761 ┆ s__JAFBIX01 sp021531895         ┆ 245.597313  ┆ 0.995247 │
└─────────────┴─────────────────────────────────┴─────────────┴──────────┘

## Read in the manifest information for the sketches

In [6]:
mf_df = (
    pl.read_csv('../outputs.PRJEB88111.nanopore/PRJEB88111.mf.csv', skip_lines=1)
    .select(["name", "n_hashes"])
)

## Add it in to the summary...

In [7]:
sum2_df = sum_df.join(mf_df, left_on='metag', right_on='name', how='inner')
sum2_df

shape: (5_184, 5)
┌─────────────┬─────────────────────────────────┬───────────┬──────────┬──────────┐
│ metag       ┆ species                         ┆ depth_all ┆ breadth  ┆ n_hashes │
│ ---         ┆ ---                             ┆ ---       ┆ ---      ┆ ---      │
│ str         ┆ str                             ┆ f64       ┆ f64      ┆ i64      │
╞═════════════╪═════════════════════════════════╪═══════════╪══════════╪══════════╡
│ ERR15909856 ┆ s__Prevotella sp002251295       ┆ 0.138455  ┆ 0.094686 ┆ 96666    │
│ ERR15909856 ┆ s__Prevotella sp002251295       ┆ 0.138455  ┆ 0.094686 ┆ 101637   │
│ ERR15909856 ┆ s__Prevotella sp002251295       ┆ 0.138455  ┆ 0.094686 ┆ 109515   │
│ ERR15942235 ┆ s__Prevotella sp002251295       ┆ 0.114299  ┆ 0.001396 ┆ 115408   │
│ ERR15942235 ┆ s__Prevotella sp002251295       ┆ 0.114299  ┆ 0.001396 ┆ 156558   │
│ …           ┆ …                               ┆ …         ┆ …        ┆ …        │
│ ERR15942141 ┆ s__Mogibacterium_A kristiansen… ┆ 0.814743  ┆ 0.003886 ┆ 139839   │
│ ERR15942141 ┆ s__Mogibacterium_A kristiansen… ┆ 0.814743  ┆ 0.003886 ┆ 206060   │
│ ERR15942221 ┆ s__Cryptobacteroides sp0340892… ┆ 0.014325  ┆ 0.000858 ┆ 71962    │
│ ERR15942221 ┆ s__Cryptobacteroides sp0340892… ┆ 0.014325  ┆ 0.000858 ┆ 96385    │
│ ERR15942221 ┆ s__Cryptobacteroides sp0340892… ┆ 0.014325  ┆ 0.000858 ┆ 141258   │
└─────────────┴─────────────────────────────────┴───────────┴──────────┴──────────┘

## ...and now filter for the bigger sketches only, representing the deeper sequenced nanopore runs.

See analysis at bottom for motivation!

In [8]:
filt_df = sum2_df.filter(pl.col('n_hashes') > 4e6)
filt_df

shape: (1_264, 5)
┌─────────────┬─────────────────────────────────┬───────────┬──────────┬──────────┐
│ metag       ┆ species                         ┆ depth_all ┆ breadth  ┆ n_hashes │
│ ---         ┆ ---                             ┆ ---       ┆ ---      ┆ ---      │
│ str         ┆ str                             ┆ f64       ┆ f64      ┆ i64      │
╞═════════════╪═════════════════════════════════╪═══════════╪══════════╪══════════╡
│ ERR15934940 ┆ s__Cryptobacteroides sp0004326… ┆ 5.256308  ┆ 0.890695 ┆ 5241832  │
│ ERR15934940 ┆ s__Cryptobacteroides sp0004326… ┆ 5.256308  ┆ 0.890695 ┆ 6757251  │
│ ERR15934940 ┆ s__Cryptobacteroides sp0004326… ┆ 5.256308  ┆ 0.890695 ┆ 9212112  │
│ ERR15935028 ┆ s__Cryptobacteroides sp9005469… ┆ 8.122636  ┆ 0.969058 ┆ 4745917  │
│ ERR15935028 ┆ s__Cryptobacteroides sp9005469… ┆ 8.122636  ┆ 0.969058 ┆ 5871776  │
│ …           ┆ …                               ┆ …         ┆ …        ┆ …        │
│ ERR15934513 ┆ s__UBA2868 sp004552595          ┆ 51.646273 ┆ 0.333482 ┆ 7841501  │
│ ERR15934513 ┆ s__UBA2868 sp004552595          ┆ 51.646273 ┆ 0.333482 ┆ 11162227 │
│ ERR15935218 ┆ s__Fimisoma sp002320005         ┆ 12.668152 ┆ 0.859564 ┆ 4607043  │
│ ERR15935218 ┆ s__Fimisoma sp002320005         ┆ 12.668152 ┆ 0.859564 ┆ 5604329  │
│ ERR15935218 ┆ s__Fimisoma sp002320005         ┆ 12.668152 ┆ 0.859564 ┆ 7099224  │
└─────────────┴─────────────────────────────────┴───────────┴──────────┴──────────┘

## Summarize by species (over metagenomes), now.

In [9]:
by_species = filt_df.group_by('species').agg(
    min_breadth=pl.col('breadth').min().round(3),
    med_breadth=pl.col('breadth').median().round(3),
    max_breadth=pl.col('breadth').max().round(3),
    min_depth=pl.col('depth_all').min().round(2),
    med_depth=pl.col('depth_all').median().round(1),
    max_depth=pl.col('depth_all').max().round(1),
)

In [10]:
with pl.Config(tbl_rows=-1):
    print(by_species.sort('min_breadth'))

shape: (16, 7)
┌────────────────────┬─────────────┬─────────────┬─────────────┬───────────┬───────────┬───────────┐
│ species            ┆ min_breadth ┆ med_breadth ┆ max_breadth ┆ min_depth ┆ med_depth ┆ max_depth │
│ ---                ┆ ---         ┆ ---         ┆ ---         ┆ ---       ┆ ---       ┆ ---       │
│ str                ┆ f64         ┆ f64         ┆ f64         ┆ f64       ┆ f64       ┆ f64       │
╞════════════════════╪═════════════╪═════════════╪═════════════╪═══════════╪═══════════╪═══════════╡
│ s__UBA2868         ┆ 0.33        ┆ 0.798       ┆ 0.929       ┆ 5.66      ┆ 19.6      ┆ 52.3      │
│ sp004552595        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Floccifex porci ┆ 0.45        ┆ 0.944       ┆ 0.97        ┆ 11.98     ┆ 31.4      ┆ 67.1      │
│ s__Mogibacterium_A ┆ 0.484       ┆ 0.963       ┆ 0.991       ┆ 8.89      ┆ 24.9      ┆ 80.4      │
│ kristiansen…       ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Ornithospirocha ┆ 0.507       ┆ 0.903       ┆ 0.978       ┆ 1.4       ┆ 5.2       ┆ 14.1      │
│ eta sp022785…      ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Prevotella      ┆ 0.665       ┆ 0.964       ┆ 0.98        ┆ 6.45      ┆ 24.0      ┆ 330.3     │
│ sp002251295        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Cryptobacteroid ┆ 0.681       ┆ 0.841       ┆ 0.887       ┆ 2.13      ┆ 7.2       ┆ 30.9      │
│ es sp0004349…      ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Cryptobacteroid ┆ 0.701       ┆ 0.903       ┆ 0.935       ┆ 2.72      ┆ 7.1       ┆ 18.3      │
│ es sp0004326…      ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__JAFBIX01        ┆ 0.714       ┆ 0.964       ┆ 0.995       ┆ 16.21     ┆ 77.5      ┆ 256.1     │
│ sp021531895        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Fimisoma        ┆ 0.731       ┆ 0.932       ┆ 0.953       ┆ 7.77      ┆ 24.1      ┆ 78.0      │
│ sp002320005        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Colivicinus     ┆ 0.802       ┆ 0.978       ┆ 0.986       ┆ 5.76      ┆ 17.1      ┆ 47.2      │
│ sp002299675        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Prevotella      ┆ 0.838       ┆ 0.901       ┆ 0.951       ┆ 14.67     ┆ 41.0      ┆ 613.9     │
│ sp000434975        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Cryptobacteroid ┆ 0.91        ┆ 0.978       ┆ 0.986       ┆ 3.62      ┆ 11.8      ┆ 67.9      │
│ es sp9005469…      ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Cryptobacteroid ┆ 0.913       ┆ 0.983       ┆ 0.991       ┆ 6.09      ┆ 16.9      ┆ 61.5      │
│ es sp0340892…      ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Lactobacillus   ┆ 0.921       ┆ 0.979       ┆ 0.995       ┆ 38.31     ┆ 1570.7    ┆ 5257.2    │
│ amylovorus         ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Bariatricus     ┆ 0.941       ┆ 0.983       ┆ 0.994       ┆ 17.29     ┆ 58.3      ┆ 193.9     │
│ sp004560705        ┆             ┆             ┆             ┆           ┆           ┆           │
│ s__Sodaliphilus    ┆ 0.965       ┆ 0.976       ┆ 0.983       ┆ 22.86     ┆ 62.6      ┆ 311.4     │
│ sp004557565        ┆             ┆             ┆             ┆           ┆           ┆           │
└────────────────────┴─────────────┴─────────────┴─────────────┴───────────┴───────────┴───────────┘

## APPENDIX: analyze the manysearch data

In [11]:
orig_df = (
    pl.scan_csv('../outputs.PRJEB88111.nanopore/PRJEB88111.x.mags+gtdb.manysearch.csv')
    .with_columns(species_name=pl.col('query_name').str.split(' ').list.slice(1, 2).list.join( " "))
).collect()

In [12]:
CORE_NAMES = [ x.strip() for x in open('../inputs.branchwater/names.list') ]
CORE_NAMES

['s__Bariatricus sp004560705',
 's__Colivicinus sp002299675',
 's__Cryptobacteroides sp000432655',
 's__Cryptobacteroides sp000434935',
 's__Cryptobacteroides sp034089285',
 's__Cryptobacteroides sp900546925',
 's__Fimisoma sp002320005',
 's__Floccifex porci',
 's__JAFBIX01 sp021531895',
 's__Lactobacillus amylovorus',
 's__Mogibacterium_A kristiansenii',
 's__Ornithospirochaeta sp022785155',
 's__Prevotella sp000434975',
 's__Prevotella sp002251295',
 's__Sodaliphilus sp004557565',
 's__UBA2868 sp004552595']

In [13]:
df = (orig_df
      .filter(pl.col('intersect_hashes') >= 20)
      .filter(pl.col('species_name').is_in(CORE_NAMES))
     )

In [14]:
by_acc = df.group_by('match_name').agg(
    n_core=pl.len(),
    med_intersect=pl.col('intersect_hashes').median(),
)
with pl.Config(tbl_rows=-1):
    print(by_acc.sort('n_core'))

shape: (59, 3)
┌─────────────┬────────┬───────────────┐
│ match_name  ┆ n_core ┆ med_intersect │
│ ---         ┆ ---    ┆ ---           │
│ str         ┆ u32    ┆ f64           │
╞═════════════╪════════╪═══════════════╡
│ ERR15909890 ┆ 6      ┆ 46.0          │
│ ERR15909878 ┆ 7      ┆ 64.0          │
│ ERR15909855 ┆ 8      ┆ 31.5          │
│ ERR15909872 ┆ 8      ┆ 49.0          │
│ ERR15909869 ┆ 8      ┆ 70.5          │
│ ERR15909853 ┆ 8      ┆ 54.0          │
│ ERR15909856 ┆ 8      ┆ 55.0          │
│ ERR15909888 ┆ 9      ┆ 60.0          │
│ ERR15909889 ┆ 9      ┆ 46.0          │
│ ERR15909852 ┆ 9      ┆ 97.0          │
│ ERR15909877 ┆ 9      ┆ 76.0          │
│ ERR15909859 ┆ 9      ┆ 50.0          │
│ ERR15909887 ┆ 9      ┆ 61.0          │
│ ERR15909879 ┆ 10     ┆ 63.5          │
│ ERR15909882 ┆ 10     ┆ 88.0          │
│ ERR15909885 ┆ 10     ┆ 41.0          │
│ ERR15909892 ┆ 10     ┆ 33.5          │
│ ERR15909874 ┆ 10     ┆ 63.5          │
│ ERR15909873 ┆ 11     ┆ 66.0          │
│ ERR15909858 ┆ 11     ┆ 52.0          │
│ ERR15909884 ┆ 12     ┆ 47.0          │
│ ERR15909891 ┆ 13     ┆ 58.0          │
│ ERR15909880 ┆ 15     ┆ 70.0          │
│ ERR15935285 ┆ 16     ┆ 960.0         │
│ ERR15934513 ┆ 16     ┆ 1091.0        │
│ ERR15934940 ┆ 16     ┆ 992.0         │
│ ERR15935578 ┆ 16     ┆ 1307.5        │
│ ERR15935081 ┆ 16     ┆ 1084.0        │
│ ERR15936552 ┆ 16     ┆ 1331.5        │
│ ERR15934725 ┆ 16     ┆ 1020.0        │
│ ERR15934927 ┆ 16     ┆ 1131.5        │
│ ERR15934516 ┆ 16     ┆ 1134.0        │
│ ERR15934783 ┆ 16     ┆ 1101.0        │
│ ERR15935218 ┆ 16     ┆ 1118.0        │
│ ERR15934890 ┆ 16     ┆ 914.5         │
│ ERR15936676 ┆ 16     ┆ 1186.5        │
│ ERR15934787 ┆ 16     ┆ 1090.0        │
│ ERR15937726 ┆ 16     ┆ 563.0         │
│ ERR15909871 ┆ 16     ┆ 123.5         │
│ ERR15938761 ┆ 16     ┆ 1295.5        │
│ ERR15934506 ┆ 16     ┆ 1200.0        │
│ ERR15909875 ┆ 16     ┆ 212.5         │
│ ERR15935830 ┆ 16     ┆ 1094.0        │
│ ERR15934865 ┆ 16     ┆ 1387.0        │
│ ERR15934877 ┆ 16     ┆ 1251.0        │
│ ERR15939764 ┆ 16     ┆ 559.5         │
│ ERR15939766 ┆ 16     ┆ 988.0         │
│ ERR15935028 ┆ 16     ┆ 1351.5        │
│ ERR15937724 ┆ 16     ┆ 1210.5        │
│ ERR15909883 ┆ 16     ┆ 173.0         │
│ ERR15934885 ┆ 16     ┆ 1199.0        │
│ ERR15934505 ┆ 16     ┆ 279.0         │
│ ERR15936647 ┆ 16     ┆ 1093.5        │
│ ERR15935141 ┆ 16     ┆ 1489.0        │
│ ERR15936630 ┆ 16     ┆ 1037.0        │
│ ERR15935750 ┆ 16     ┆ 1152.5        │
│ ERR15936522 ┆ 16     ┆ 1110.5        │
│ ERR15909857 ┆ 16     ┆ 231.0         │
│ ERR15934764 ┆ 16     ┆ 1021.0        │
└─────────────┴────────┴───────────────┘

In [15]:
manysearch_join_df = (
    by_acc
    .join(mf_df, left_on='match_name', right_on='name', how='inner')
    .select(['match_name', 'n_core', 'n_hashes', 'med_intersect']) 
)
with pl.Config(tbl_rows=-1):
    print(manysearch_join_df.sort('n_hashes'))

shape: (177, 4)
┌─────────────┬────────┬──────────┬───────────────┐
│ match_name  ┆ n_core ┆ n_hashes ┆ med_intersect │
│ ---         ┆ ---    ┆ ---      ┆ ---           │
│ str         ┆ u32    ┆ i64      ┆ f64           │
╞═════════════╪════════╪══════════╪═══════════════╡
│ ERR15909855 ┆ 8      ┆ 63791    ┆ 31.5          │
│ ERR15909855 ┆ 8      ┆ 65550    ┆ 31.5          │
│ ERR15909855 ┆ 8      ┆ 67653    ┆ 31.5          │
│ ERR15909890 ┆ 6      ┆ 74127    ┆ 46.0          │
│ ERR15909890 ┆ 6      ┆ 76655    ┆ 46.0          │
│ ERR15909888 ┆ 9      ┆ 80173    ┆ 60.0          │
│ ERR15909890 ┆ 6      ┆ 80687    ┆ 46.0          │
│ ERR15909888 ┆ 9      ┆ 82205    ┆ 60.0          │
│ ERR15909878 ┆ 7      ┆ 82496    ┆ 64.0          │
│ ERR15909853 ┆ 8      ┆ 83559    ┆ 54.0          │
│ ERR15909858 ┆ 11     ┆ 83948    ┆ 52.0          │
│ ERR15909878 ┆ 7      ┆ 84293    ┆ 64.0          │
│ ERR15909888 ┆ 9      ┆ 85657    ┆ 60.0          │
│ ERR15909853 ┆ 8      ┆ 85907    ┆ 54.0          │
│ ERR15909858 ┆ 11     ┆ 86362    ┆ 52.0          │
│ ERR15909885 ┆ 10     ┆ 86660    ┆ 41.0          │
│ ERR15909878 ┆ 7      ┆ 86675    ┆ 64.0          │
│ ERR15909853 ┆ 8      ┆ 88404    ┆ 54.0          │
│ ERR15909858 ┆ 11     ┆ 89328    ┆ 52.0          │
│ ERR15909884 ┆ 12     ┆ 89945    ┆ 47.0          │
│ ERR15909892 ┆ 10     ┆ 90012    ┆ 33.5          │
│ ERR15909885 ┆ 10     ┆ 90214    ┆ 41.0          │
│ ERR15909884 ┆ 12     ┆ 93170    ┆ 47.0          │
│ ERR15909892 ┆ 10     ┆ 93477    ┆ 33.5          │
│ ERR15909885 ┆ 10     ┆ 95376    ┆ 41.0          │
│ ERR15909887 ┆ 9      ┆ 95400    ┆ 61.0          │
│ ERR15909872 ┆ 8      ┆ 96175    ┆ 49.0          │
│ ERR15909856 ┆ 8      ┆ 96666    ┆ 55.0          │
│ ERR15909892 ┆ 10     ┆ 96857    ┆ 33.5          │
│ ERR15909884 ┆ 12     ┆ 97902    ┆ 47.0          │
│ ERR15909887 ┆ 9      ┆ 98683    ┆ 61.0          │
│ ERR15909859 ┆ 9      ┆ 98820    ┆ 50.0          │
│ ERR15909879 ┆ 10     ┆ 99256    ┆ 63.5          │
│ ERR15909889 ┆ 9      ┆ 99791    ┆ 46.0          │
│ ERR15909872 ┆ 8      ┆ 100111   ┆ 49.0          │
│ ERR15909856 ┆ 8      ┆ 101637   ┆ 55.0          │
│ ERR15909879 ┆ 10     ┆ 103061   ┆ 63.5          │
│ ERR15909887 ┆ 9      ┆ 104006   ┆ 61.0          │
│ ERR15909889 ┆ 9      ┆ 104174   ┆ 46.0          │
│ ERR15909859 ┆ 9      ┆ 104235   ┆ 50.0          │
│ ERR15909872 ┆ 8      ┆ 104942   ┆ 49.0          │
│ ERR15909891 ┆ 13     ┆ 105338   ┆ 58.0          │
│ ERR15909852 ┆ 9      ┆ 107362   ┆ 97.0          │
│ ERR15909891 ┆ 13     ┆ 107914   ┆ 58.0          │
│ ERR15909877 ┆ 9      ┆ 109269   ┆ 76.0          │
│ ERR15909879 ┆ 10     ┆ 109373   ┆ 63.5          │
│ ERR15909856 ┆ 8      ┆ 109515   ┆ 55.0          │
│ ERR15909891 ┆ 13     ┆ 109728   ┆ 58.0          │
│ ERR15909889 ┆ 9      ┆ 109859   ┆ 46.0          │
│ ERR15909852 ┆ 9      ┆ 112124   ┆ 97.0          │
│ ERR15909877 ┆ 9      ┆ 113444   ┆ 76.0          │
│ ERR15909859 ┆ 9      ┆ 113482   ┆ 50.0          │
│ ERR15909877 ┆ 9      ┆ 117691   ┆ 76.0          │
│ ERR15909869 ┆ 8      ┆ 117720   ┆ 70.5          │
│ ERR15909852 ┆ 9      ┆ 119674   ┆ 97.0          │
│ ERR15909869 ┆ 8      ┆ 122119   ┆ 70.5          │
│ ERR15909874 ┆ 10     ┆ 126140   ┆ 63.5          │
│ ERR15909873 ┆ 11     ┆ 127881   ┆ 66.0          │
│ ERR15909869 ┆ 8      ┆ 128975   ┆ 70.5          │
│ ERR15909874 ┆ 10     ┆ 131381   ┆ 63.5          │
│ ERR15909873 ┆ 11     ┆ 135237   ┆ 66.0          │
│ ERR15909874 ┆ 10     ┆ 138531   ┆ 63.5          │
│ ERR15909873 ┆ 11     ┆ 148451   ┆ 66.0          │
│ ERR15909882 ┆ 10     ┆ 166807   ┆ 88.0          │
│ ERR15909882 ┆ 10     ┆ 176299   ┆ 88.0          │
│ ERR15909882 ┆ 10     ┆ 191103   ┆ 88.0          │
│ ERR15909883 ┆ 16     ┆ 330556   ┆ 173.0         │
│ ERR15909871 ┆ 16     ┆ 331148   ┆ 123.5         │
│ ERR15909880 ┆ 15     ┆ 344543   ┆ 70.0          │
│ ERR15909883 ┆ 16     ┆ 350942   ┆ 173.0         │
│ ERR15909871 ┆ 16     ┆ 363363   ┆ 123.5         │
│ ERR15909880 ┆ 15     ┆ 367608   ┆ 70.0          │
│ ERR15909883 ┆ 16     ┆ 374523   ┆ 173.0         │
│ ERR15909880 ┆ 15     ┆ 398680   ┆ 70.0          │
│ ERR15909871 ┆ 16     ┆ 410704   ┆ 123.5         │
│ ERR15909857 ┆ 16     ┆ 537583   ┆ 231.0         │
│ ERR15909875 ┆ 16     ┆ 549830   ┆ 212.5         │
│ ERR15909857 ┆ 16     ┆ 585246   ┆ 231.0         │
│ ERR15909875 ┆ 16     ┆ 600685   ┆ 212.5         │
│ ERR15909857 ┆ 16     ┆ 657197   ┆ 231.0         │
│ ERR15909875 ┆ 16     ┆ 675900   ┆ 212.5         │
│ ERR15937726 ┆ 16     ┆ 1718243  ┆ 563.0         │
│ ERR15934505 ┆ 16     ┆ 1728118  ┆ 279.0         │
│ ERR15937726 ┆ 16     ┆ 1945884  ┆ 563.0         │
│ ERR15934505 ┆ 16     ┆ 2041477  ┆ 279.0         │
│ ERR15939764 ┆ 16     ┆ 2160093  ┆ 559.5         │
│ ERR15937726 ┆ 16     ┆ 2287871  ┆ 563.0         │
│ ERR15936647 ┆ 16     ┆ 2403517  ┆ 1093.5        │
│ ERR15934505 ┆ 16     ┆ 2535605  ┆ 279.0         │
│ ERR15939764 ┆ 16     ┆ 2568676  ┆ 559.5         │
│ ERR15934787 ┆ 16     ┆ 2569499  ┆ 1090.0        │
│ ERR15936647 ┆ 16     ┆ 2764116  ┆ 1093.5        │
│ ERR15934787 ┆ 16     ┆ 3026107  ┆ 1090.0        │
│ ERR15939764 ┆ 16     ┆ 3188853  ┆ 559.5         │
│ ERR15936647 ┆ 16     ┆ 3293610  ┆ 1093.5        │
│ ERR15934890 ┆ 16     ┆ 3471908  ┆ 914.5         │
│ ERR15935285 ┆ 16     ┆ 3478507  ┆ 960.0         │
│ ERR15934787 ┆ 16     ┆ 3714303  ┆ 1090.0        │
│ ERR15936630 ┆ 16     ┆ 4049740  ┆ 1037.0        │
│ ERR15935578 ┆ 16     ┆ 4099558  ┆ 1307.5        │
│ ERR15935285 ┆ 16     ┆ 4129345  ┆ 960.0         │
│ ERR15934783 ┆ 16     ┆ 4162222  ┆ 1101.0        │
│ ERR15934764 ┆ 16     ┆ 4162409  ┆ 1021.0        │
│ ERR15934890 ┆ 16     ┆ 4283067  ┆ 914.5         │
│ ERR15935081 ┆ 16     ┆ 4306411  ┆ 1084.0        │
│ ERR15934725 ┆ 16     ┆ 4326173  ┆ 1020.0        │
│ ERR15934927 ┆ 16     ┆ 4342405  ┆ 1131.5        │
│ ERR15934516 ┆ 16     ┆ 4426687  ┆ 1134.0        │
│ ERR15935218 ┆ 16     ┆ 4607043  ┆ 1118.0        │
│ ERR15935750 ┆ 16     ┆ 4701541  ┆ 1152.5        │
│ ERR15935028 ┆ 16     ┆ 4745917  ┆ 1351.5        │
│ ERR15938761 ┆ 16     ┆ 4792317  ┆ 1295.5        │
│ ERR15936630 ┆ 16     ┆ 4995914  ┆ 1037.0        │
│ ERR15935578 ┆ 16     ┆ 5062419  ┆ 1307.5        │
│ ERR15935285 ┆ 16     ┆ 5091616  ┆ 960.0         │
│ ERR15935830 ┆ 16     ┆ 5204444  ┆ 1094.0        │
│ ERR15934783 ┆ 16     ┆ 5222114  ┆ 1101.0        │
│ ERR15934764 ┆ 16     ┆ 5225704  ┆ 1021.0        │
│ ERR15934940 ┆ 16     ┆ 5241832  ┆ 992.0         │
│ ERR15935081 ┆ 16     ┆ 5258588  ┆ 1084.0        │
│ ERR15934516 ┆ 16     ┆ 5434576  ┆ 1134.0        │
│ ERR15939766 ┆ 16     ┆ 5483231  ┆ 988.0         │
│ ERR15934725 ┆ 16     ┆ 5499310  ┆ 1020.0        │
│ ERR15934927 ┆ 16     ┆ 5555440  ┆ 1131.5        │
│ ERR15934890 ┆ 16     ┆ 5565766  ┆ 914.5         │
│ ERR15934877 ┆ 16     ┆ 5579319  ┆ 1251.0        │
│ ERR15935218 ┆ 16     ┆ 5604329  ┆ 1118.0        │
│ ERR15935750 ┆ 16     ┆ 5649557  ┆ 1152.5        │
│ ERR15936676 ┆ 16     ┆ 5712078  ┆ 1186.5        │
│ ERR15934506 ┆ 16     ┆ 5718428  ┆ 1200.0        │
│ ERR15935028 ┆ 16     ┆ 5871776  ┆ 1351.5        │
│ ERR15934513 ┆ 16     ┆ 5907208  ┆ 1091.0        │
│ ERR15936522 ┆ 16     ┆ 5962749  ┆ 1110.5        │
│ ERR15938761 ┆ 16     ┆ 6015297  ┆ 1295.5        │
│ ERR15936552 ┆ 16     ┆ 6016801  ┆ 1331.5        │
│ ERR15934885 ┆ 16     ┆ 6084053  ┆ 1199.0        │
│ ERR15935141 ┆ 16     ┆ 6369270  ┆ 1489.0        │
│ ERR15935830 ┆ 16     ┆ 6436877  ┆ 1094.0        │
│ ERR15936630 ┆ 16     ┆ 6478445  ┆ 1037.0        │
│ ERR15935578 ┆ 16     ┆ 6561562  ┆ 1307.5        │
│ ERR15937724 ┆ 16     ┆ 6684361  ┆ 1210.5        │
│ ERR15934940 ┆ 16     ┆ 6757251  ┆ 992.0         │
│ ERR15935081 ┆ 16     ┆ 6758120  ┆ 1084.0        │
│ ERR15939766 ┆ 16     ┆ 6781319  ┆ 988.0         │
│ ERR15934783 ┆ 16     ┆ 6907156  ┆ 1101.0        │
│ ERR15934764 ┆ 16     ┆ 6919147  ┆ 1021.0        │
│ ERR15934516 ┆ 16     ┆ 7011959  ┆ 1134.0        │
│ ERR15936676 ┆ 16     ┆ 7013047  ┆ 1186.5        │
│ ERR15935750 ┆ 16     ┆ 7071769  ┆ 1152.5        │
│ ERR15934506 ┆ 16     ┆ 7079510  ┆ 1200.0        │
│ ERR15934877 ┆ 16     ┆ 7089492  ┆ 1251.0        │
│ ERR15935218 ┆ 16     ┆ 7099224  ┆ 1118.0        │
│ ERR15934725 ┆ 16     ┆ 7387636  ┆ 1020.0        │
│ ERR15936522 ┆ 16     ┆ 7493017  ┆ 1110.5        │
│ ERR15936552 ┆ 16     ┆ 7508712  ┆ 1331.5        │
│ ERR15934885 ┆ 16     ┆ 7562480  ┆ 1199.0        │
│ ERR15934927 ┆ 16     ┆ 7580256  ┆ 1131.5        │
│ ERR15935028 ┆ 16     ┆ 7635873  ┆ 1351.5        │
│ ERR15934865 ┆ 16     ┆ 7660351  ┆ 1387.0        │
│ ERR15934513 ┆ 16     ┆ 7841501  ┆ 1091.0        │
│ ERR15935141 ┆ 16     ┆ 7920196  ┆ 1489.0        │
│ ERR15938761 ┆ 16     ┆ 7952050  ┆ 1295.5        │
│ ERR15935830 ┆ 16     ┆ 8334647  ┆ 1094.0        │
│ ERR15937724 ┆ 16     ┆ 8592579  ┆ 1210.5        │
│ ERR15939766 ┆ 16     ┆ 8826014  ┆ 988.0         │
│ ERR15936676 ┆ 16     ┆ 8985249  ┆ 1186.5        │
│ ERR15934506 ┆ 16     ┆ 9149952  ┆ 1200.0        │
│ ERR15934940 ┆ 16     ┆ 9212112  ┆ 992.0         │
│ ERR15934877 ┆ 16     ┆ 9521552  ┆ 1251.0        │
│ ERR15934865 ┆ 16     ┆ 9639803  ┆ 1387.0        │
│ ERR15934885 ┆ 16     ┆ 9803136  ┆ 1199.0        │
│ ERR15936552 ┆ 16     ┆ 9869116  ┆ 1331.5        │
│ ERR15936522 ┆ 16     ┆ 9878542  ┆ 1110.5        │
│ ERR15935141 ┆ 16     ┆ 10307669 ┆ 1489.0        │
│ ERR15934513 ┆ 16     ┆ 11162227 ┆ 1091.0        │
│ ERR15937724 ┆ 16     ┆ 11738598 ┆ 1210.5        │
│ ERR15934865 ┆ 16     ┆ 12694315 ┆ 1387.0        │
└─────────────┴────────┴──────────┴───────────────┘

### ...and examine table above to find cutoff where the big datasets start <=> all 16 species.